"""
Lattice invariants of a lattice polytope, computed exactly.

For P = conv(points) this module counts and lists the lattice points of the
dilates kP, and gives the Ehrhart polynomial, the h*-vector, the Gorenstein
index with the polar dual of a reflexive P, and the lattice width.
Everything is done in integers and Fractions, from facets certified
complete by the exact hull of feynkit._exact.

The lattice
-----------
P of dimension d is measured in one of two affine lattices:

- "support", the default: alpha_1 + L, with L spanned by the differences of
  the points. It is the lattice of normalized_volume, of the chart of
  lattice_chart and of the lattice ZA generated by the columns (1, alpha_j).
- "ambient": aff(P) cap Z^n = alpha_1 + sat(L), the usual lattice of Ehrhart
  theory.

They agree when PolytopeData.sublattice_index, [sat(L) : L], is 1. Either
way P is written in a chart x = o + S c (see invariant_chart), in which it
is a full-dimensional polytope of Z^d, and kP has the lattice k o + S Z^d.

Lattice points
--------------
Let P_j be the projection of P to the first j chart coordinates, with
certified facets a . y <= b. A point c lies in kP exactly when every prefix
(c_1, ..., c_j) lies in kP_j. Given a prefix in kP_j, each facet of P_(j+1)
with a_(j+1) != 0 bounds c_(j+1); a facet with a_(j+1) = 0 is a facet of
P_j and holds already. Every such prefix extends to a real point of
kP_(j+1), so the walk only visits prefixes of real points of kP. At the last
coordinate the integers in range are counted rather than listed. Interior
points satisfy every inequality strictly at every level, which is exact
because the projection maps the interior of kP_(j+1) onto that of kP_j.
"""

from __future__ import annotations

import math
import shutil
import subprocess
import tempfile
from collections.abc import Iterator, Sequence
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path
from typing import Literal

import numpy as np
import sympy as sp

from . import _exact
from .core.exceptions import ComputationError, ValidationError
from .polytope import LatticeChart, lattice_chart

__all__ = [
    "Lattice",
    "LatticeInvariants",
    "count_lattice_points",
    "ehrhart_polynomial",
    "gorenstein_index",
    "h_star_vector",
    "invariant_chart",
    "is_idp",
    "lattice_invariants",
    "lattice_points",
    "lattice_width",
    "polar_dual",
]

Lattice = Literal["support", "ambient"]

_K = sp.Symbol("k")

# One inequality a . y <= b of a projection P_j, stored as (a_1, ..., a_(j-1)), a_j, b with
# a_j != 0: the part on the prefix, the coefficient of the new coordinate, the offset.
_Bound = tuple[tuple[int, ...], int, int]

PointsLike = Sequence[Sequence[int]] | np.ndarray


# --- arguments ---------------------------------------------------------------


def _check_lattice(lattice: str) -> str:
    if lattice not in ("support", "ambient"):
        raise ValidationError(f"lattice must be 'support' or 'ambient', got {lattice!r}")
    return lattice


def _dilation(k: object) -> int:
    """k as a Python integer of at least 1.

    Raises
    ------
    ValidationError
        If k is a bool, not an integer, or below 1.
    """
    message = f"the dilation factor k must be a positive integer, got {k!r}"
    if isinstance(k, bool):
        raise ValidationError(message)
    try:
        value = _exact._as_int(k, "k")
    except ValidationError:
        raise ValidationError(message) from None
    if value < 1:
        raise ValidationError(message)
    return value


# --- charts ------------------------------------------------------------------


def _saturated_chart(chart: LatticeChart) -> LatticeChart:
    """The chart of the saturation sat(L) of the lattice of chart.

    With B^T W = [0 | H], W unimodular, S = B H^-T is a basis of sat(L) (see
    feynkit.normal_forms._chart). Its rows solve H s_i = b_i, b_i the rows of
    B. The basis is brought into Hermite normal form, the points are solved
    for in it, and the coordinates are shifted to minimum 0, as lattice_chart
    does.

    Raises
    ------
    ComputationError
        If a solve is not integral, which would be a bug.
    """
    d = len(chart.basis)
    n = len(chart.origin)
    if d == 0:
        return chart
    hermite = _exact.hermite_normal_form_with_transform([list(b) for b in chart.basis], n).hermite
    rows = []
    for i in range(n):
        solved = _exact.solve_hermite_scaled(hermite, [b[i] for b in chart.basis])
        if solved is None or solved[1] != 1:
            raise ComputationError("the basis of the saturated lattice is not integral")
        rows.append(solved[0])
    saturated = _exact.hermite_normal_form(rows, d)
    raw = []
    for c in chart.coordinates:
        x = [sum(ct * b[i] for ct, b in zip(c, chart.basis, strict=True)) for i in range(n)]
        solved = _exact.solve_hermite_scaled(saturated, x)
        if solved is None or solved[1] != 1:
            raise ComputationError(f"the chart point {c} is not in the saturated lattice")
        raw.append(solved[0])
    shift = [min(c[t] for c in raw) for t in range(d)]
    basis = tuple(tuple(saturated[i][t] for i in range(n)) for t in range(d))
    origin = tuple(
        o + sum(s * b[i] for s, b in zip(shift, basis, strict=True))
        for i, o in enumerate(chart.origin)
    )
    coordinates = tuple(tuple(c[t] - shift[t] for t in range(d)) for c in raw)
    return LatticeChart(origin=origin, basis=basis, coordinates=coordinates)


def _chart(points: list[tuple[int, ...]], lattice: str) -> LatticeChart:
    chart = lattice_chart(points)
    return _saturated_chart(chart) if lattice == "ambient" else chart


def invariant_chart(points: PointsLike, *, lattice: Lattice = "support") -> LatticeChart:
    """The chart x = o + S c in which the invariants of conv(points) are computed.

    For "support" it is lattice_chart(points), whose basis is the
    Hermite-normal-form basis of the lattice L spanned by the differences of
    the points. For "ambient" the basis is the Hermite-normal-form basis of
    sat(L), the integer points of the linear span of L, and the coordinates
    of the points generate a sublattice of Z^d of index [sat(L) : L]. The
    coordinates are non-negative with minimum 0 in both.

    Raises
    ------
    ValidationError
        If there are no points, a coordinate is not an integer, the points
        do not all have the same number of coordinates, or lattice is not
        "support" or "ambient".
    """
    _check_lattice(lattice)
    pts = _exact.integer_points(points)
    if not pts:
        raise ValidationError("invariant_chart needs at least one point")
    return _chart(pts, lattice)


# --- the polytope in its chart -----------------------------------------------


def _certified_facets(
    coordinates: list[tuple[int, ...]],
) -> tuple[list[_exact.Halfspace], _exact.FaceLattice]:
    """Facets of full-dimensional points of Z^j, j >= 2, certified complete, with the lattice.

    Raises
    ------
    ComputationError
        If the facets fail the completeness certificate, which would be a
        bug.
    """
    halfspaces = _exact.beneath_beyond(coordinates)
    try:
        lattice = _exact.certified_lattice(
            coordinates, [h.mask for h in halfspaces], len(coordinates[0])
        )
    except _exact.CertificateError as exc:
        raise ComputationError(
            f"the facets from beneath-beyond fail the completeness certificate: {exc}"
        ) from exc
    return halfspaces, lattice


def _level(forms: Sequence[tuple[Sequence[int], int]]) -> tuple[_Bound, ...]:
    """The inequalities of a projection that bound its last coordinate."""
    return tuple((tuple(a[:-1]), a[-1], b) for a, b in forms if a[-1])


_Forms = tuple[tuple[tuple[int, ...], int], ...]


@dataclass(frozen=True)
class _Body:
    """A full-dimensional lattice polytope of Z^d, d >= 1, with its projections.

    Attributes
    ----------
    vertices
        The vertices, sorted.
    facets
        (m, b) with m . c <= b, m primitive in Z^d.
    volume
        The normalised volume, d! times the Euclidean volume, or 0 when not
        asked for.
    levels
        levels[j - 1] bounds c_j from the facets of P_j, the projection to
        the first j coordinates.
    """

    vertices: tuple[tuple[int, ...], ...]
    facets: _Forms
    volume: int
    levels: tuple[tuple[_Bound, ...], ...]


def _body(coordinates: Sequence[tuple[int, ...]], *, volume: bool = True) -> _Body:
    """The body of the distinct, sorted, full-dimensional points of Z^d, d >= 1.

    Raises
    ------
    ComputationError
        If a facet list fails its certificate or a volume check fails, which
        would be a bug.
    """
    d = len(coordinates[0])
    low, high = coordinates[0][0], coordinates[-1][0]
    first: _Forms = (((-1,), -low), ((1,), high))
    if d == 1:
        return _Body(((low,), (high,)), first, high - low, (_level(first),))
    points = list(coordinates)
    halfspaces, face_lattice = _certified_facets(points)
    vertices = sorted(
        points[_exact.mask_indices(mask)[0]] for mask, k in face_lattice.dims.items() if k == 0
    )
    size = 0
    if volume:
        size = _exact.simplex_volume(points, _exact.pulling_simplices(face_lattice, points), 1)
    facets = tuple((h.normal, h.offset) for h in halfspaces)
    levels = [_level(first)]
    for j in range(2, d):
        projection, _ = _certified_facets(sorted({v[:j] for v in vertices}))
        levels.append(_level([(h.normal, h.offset) for h in projection]))
    levels.append(_level(facets))
    return _Body(tuple(vertices), facets, size, tuple(levels))


@dataclass(frozen=True)
class _Polytope:
    """P in the chart of its lattice.

    Attributes
    ----------
    chart
        The chart of the chosen lattice.
    points
        The distinct chart points, sorted.
    body
        P in chart coordinates; None for a point.
    """

    chart: LatticeChart
    points: tuple[tuple[int, ...], ...]
    body: _Body | None

    @property
    def dimension(self) -> int:
        return len(self.chart.basis)

    @property
    def vertices(self) -> tuple[tuple[int, ...], ...]:
        return self.points if self.body is None else self.body.vertices

    @property
    def facets(self) -> _Forms:
        return () if self.body is None else self.body.facets

    @property
    def volume(self) -> int:
        return 1 if self.body is None else self.body.volume

    @property
    def levels(self) -> tuple[tuple[_Bound, ...], ...]:
        return () if self.body is None else self.body.levels


def _prepare(points: PointsLike, lattice: str) -> _Polytope:
    """The polytope of the points in the chart of lattice, with its projections.

    Raises
    ------
    ValidationError
        As invariant_chart.
    ComputationError
        If a facet list fails its certificate or a volume check fails, which
        would be a bug.
    """
    _check_lattice(lattice)
    pts = _exact.integer_points(points)
    if not pts:
        raise ValidationError("the lattice invariants need at least one point")
    chart = _chart(pts, lattice)
    coordinates = tuple(sorted(set(chart.coordinates)))
    body = _body(coordinates) if chart.basis else None
    return _Polytope(chart, coordinates, body)


# --- the enumerator ----------------------------------------------------------


def _range(
    level: tuple[_Bound, ...], prefix: Sequence[int], num: int, den: int
) -> tuple[int, int, int, int]:
    """The closed and the strict range of the next coordinate over prefix in (num/den) P_j.

    Each bound a . y <= b of P_j becomes den (head . prefix + a_j y) <= num b,
    so den a_j y <= r with r = num b - den head . prefix, and strictly
    den a_j y <= r - 1. Returns (low, high, strict low, strict high).
    """
    low: int | None = None
    high: int | None = None
    strict_low: int | None = None
    strict_high: int | None = None
    for head, a, b in level:
        r = num * b - den * sum(h * x for h, x in zip(head, prefix, strict=True))
        q = den * a
        if q > 0:
            closed, strict = r // q, (r - 1) // q
            if high is None or closed < high:
                high = closed
            if strict_high is None or strict < strict_high:
                strict_high = strict
        else:
            closed, strict = -(r // -q), -((r - 1) // -q)
            if low is None or closed > low:
                low = closed
            if strict_low is None or strict > strict_low:
                strict_low = strict
    if low is None or high is None or strict_low is None or strict_high is None:
        raise ComputationError("a projection of the polytope is unbounded, which would be a bug")
    return low, high, strict_low, strict_high


def _count(levels: Sequence[tuple[_Bound, ...]], num: int, den: int = 1) -> tuple[int, int]:
    """The numbers of lattice points and of interior lattice points of (num/den) P.

    levels are those of P; with none, P is a point, its own interior.
    """
    if not levels:
        return 1, 1
    last = len(levels) - 1
    closed_total = interior_total = 0
    prefix: list[int] = []

    def walk(j: int, inside: bool) -> None:
        nonlocal closed_total, interior_total
        low, high, strict_low, strict_high = _range(levels[j], prefix, num, den)
        if j == last:
            closed_total += max(0, high - low + 1)
            if inside:
                interior_total += max(0, strict_high - strict_low + 1)
            return
        for value in range(low, high + 1):
            prefix.append(value)
            walk(j + 1, inside and strict_low <= value <= strict_high)
            prefix.pop()

    walk(0, True)
    return closed_total, interior_total


def _points(
    levels: Sequence[tuple[_Bound, ...]], num: int, den: int = 1, *, interior: bool = False
) -> Iterator[tuple[int, ...]]:
    """The lattice points of (num/den) P, P given by its levels, in lexicographic order."""
    if not levels:
        yield ()
        return
    last = len(levels) - 1
    prefix: list[int] = []

    def walk(j: int) -> Iterator[tuple[int, ...]]:
        low, high, strict_low, strict_high = _range(levels[j], prefix, num, den)
        if interior:
            low, high = strict_low, strict_high
        for value in range(low, high + 1):
            prefix.append(value)
            if j == last:
                yield tuple(prefix)
            else:
                yield from walk(j + 1)
            prefix.pop()

    yield from walk(0)


# --- lattice points ----------------------------------------------------------


def lattice_points(
    points: PointsLike, k: int = 1, *, interior: bool = False, lattice: Lattice = "support"
) -> list[tuple[int, ...]]:
    """The lattice points of kP, P = conv(points), in ambient coordinates, sorted.

    A point of kP is k o + S c for c in Z^d, in the chart x = o + S c of
    invariant_chart; with lattice="ambient" these are all the integer points
    of kP. With interior=True only the points of the relative interior are
    listed; a point (d = 0) is its own interior.

    Raises
    ------
    ValidationError
        If there are no points, a coordinate is not an integer, the points
        do not all have the same number of coordinates, k is not a positive
        integer, or lattice is not "support" or "ambient".
    ComputationError
        If a consistency check fails, which would be a bug.
    """
    k = _dilation(k)
    polytope = _prepare(points, lattice)
    chart = polytope.chart
    found = []
    for c in _points(polytope.levels, k, interior=interior):
        found.append(
            tuple(
                k * o + sum(ct * b[i] for ct, b in zip(c, chart.basis, strict=True))
                for i, o in enumerate(chart.origin)
            )
        )
    return sorted(found)


def count_lattice_points(
    points: PointsLike, k: int = 1, *, interior: bool = False, lattice: Lattice = "support"
) -> int:
    """The number of lattice points of kP, or of its relative interior; see lattice_points.

    Raises
    ------
    ValidationError, ComputationError
        As lattice_points.
    """
    k = _dilation(k)
    closed, inner = _count(_prepare(points, lattice).levels, k)
    return inner if interior else closed


# --- Ehrhart polynomial and h*-vector ----------------------------------------


def _interpolate(nodes: Sequence[tuple[int, Fraction]]) -> list[Fraction]:
    """Coefficients, from degree 0, of the polynomial of degree below len(nodes) through them."""
    size = len(nodes)
    total = [Fraction(0)] * size
    for i, (xi, yi) in enumerate(nodes):
        basis = [Fraction(1)]
        scale = Fraction(yi)
        for j, (xj, _) in enumerate(nodes):
            if j == i:
                continue
            basis = [Fraction(0), *basis]
            for t in range(len(basis) - 1):
                basis[t] -= xj * basis[t + 1]
            scale /= xi - xj
        for t, c in enumerate(basis):
            total[t] += scale * c
    return total


def _evaluate(coefficients: Sequence[Fraction], x: int) -> Fraction:
    value = Fraction(0)
    for c in reversed(coefficients):
        value = value * x + c
    return value


def _ehrhart(polytope: _Polytope) -> tuple[Fraction, ...]:
    """The coefficients c_0, ..., c_d of the Ehrhart polynomial.

    L(0) = 1, the leading coefficient is vol / d!, and one walk of kP gives
    L(k) and, by reciprocity, L(-k) = (-1)^d L_interior(k), for k up to
    ceil(d/2). The rest of the polynomial is interpolated through L(0) and
    the next d - 1 values in the order L(1), L(-1), L(2), L(-2), ...; the
    values left over are checked.

    Raises
    ------
    ComputationError
        If a value left over disagrees, which would be a bug.
    """
    d = polytope.dimension
    if d == 0:
        return (Fraction(1),)
    known = {0: 1}
    for k in range(1, math.ceil(d / 2) + 1):
        closed, inner = _count(polytope.levels, k)
        known[k] = closed
        known[-k] = (-1) ** d * inner
    lead = Fraction(polytope.volume, math.factorial(d))
    order = sorted(known, key=lambda x: (abs(x), -x))
    nodes = [(x, known[x] - lead * x**d) for x in order[:d]]
    coefficients = (*_interpolate(nodes), lead)
    for x in order[d:]:
        if _evaluate(coefficients, x) != known[x]:
            raise ComputationError(
                f"the Ehrhart polynomial gives {_evaluate(coefficients, x)} at {x}, "
                f"the count {known[x]}"
            )
    return coefficients


def _h_star(polytope: _Polytope, ehrhart: Sequence[Fraction]) -> tuple[int, ...]:
    """h*_i = sum_j (-1)^j binom(d + 1, j) L(i - j), checked integral and non-negative.

    Raises
    ------
    ComputationError
        If an entry is not a non-negative integer, h*_0 is not 1, or the sum
        is not the volume, which would be a bug.
    """
    d = polytope.dimension
    values = [_evaluate(ehrhart, k) for k in range(d + 1)]
    h_star = [
        sum(((-1) ** j * math.comb(d + 1, j) * values[i - j] for j in range(i + 1)), Fraction(0))
        for i in range(d + 1)
    ]
    if (
        any(h.denominator != 1 or h < 0 for h in h_star)
        or h_star[0] != 1
        or sum(h_star) != polytope.volume
    ):
        raise ComputationError(
            f"the h*-vector {[str(h) for h in h_star]} is not a vector of non-negative integers "
            f"with h*_0 = 1 and sum {polytope.volume}"
        )
    return tuple(int(h) for h in h_star)


def ehrhart_polynomial(points: PointsLike, *, lattice: Lattice = "support") -> sp.Poly:
    """The Ehrhart polynomial L(k) of P = conv(points), in the symbol k over QQ.

    L(k) is the number of lattice points of kP for every integer k >= 1, and
    (-1)^d L(-k) the number in its relative interior. It has degree d, the
    dimension of P, constant term 1 and leading coefficient vol / d!, with
    the volume normalised in the chosen lattice.

    Raises
    ------
    ValidationError
        As invariant_chart.
    ComputationError
        If a consistency check fails, which would be a bug.
    """
    coefficients = _ehrhart(_prepare(points, lattice))
    expr = sum(
        (sp.Rational(c.numerator, c.denominator) * _K**i for i, c in enumerate(coefficients)),
        sp.Integer(0),
    )
    return sp.Poly(expr, _K, domain=sp.QQ)


def h_star_vector(points: PointsLike, *, lattice: Lattice = "support") -> tuple[int, ...]:
    """The h*-vector (h*_0, ..., h*_d) of P = conv(points), trailing zeros included.

    It is defined by sum_(k >= 0) L(k) t^k = h*(t) / (1 - t)^(d + 1), L the
    Ehrhart polynomial. Its entries are non-negative integers with h*_0 = 1,
    h*_d the number of interior lattice points of P and sum the normalised
    volume (Beck and Robins 2015).

    Raises
    ------
    ValidationError
        As invariant_chart.
    ComputationError
        If a consistency check fails, which would be a bug.
    """
    polytope = _prepare(points, lattice)
    return _h_star(polytope, _ehrhart(polytope))


# --- Gorenstein index, reflexivity and the polar dual ------------------------


def _solve(rows: Sequence[Sequence[int]], rhs: Sequence[int]) -> list[Fraction] | None:
    """The solution of rows @ x = rhs over Q, or None when there is none.

    Raises
    ------
    ComputationError
        If the solution is not unique, which for the facet forms of a
        full-dimensional polytope would be a bug.
    """
    width = len(rows[0])
    a = [[Fraction(x) for x in row] + [Fraction(y)] for row, y in zip(rows, rhs, strict=True)]
    pivots: list[int] = []
    r = 0
    for c in range(width):
        pivot = next((i for i in range(r, len(a)) if a[i][c]), None)
        if pivot is None:
            continue
        a[r], a[pivot] = a[pivot], a[r]
        a[r] = [x / a[r][c] for x in a[r]]
        for i in range(len(a)):
            if i != r and a[i][c]:
                factor = a[i][c]
                a[i] = [x - factor * y for x, y in zip(a[i], a[r], strict=True)]
        pivots.append(c)
        r += 1
    if any(row[-1] for row in a[r:]):
        return None
    if r < width:
        raise ComputationError("the facet forms do not determine the Gorenstein point")
    return [a[i][-1] for i in range(width)]


def _gorenstein(polytope: _Polytope) -> tuple[int, tuple[int, ...]] | None:
    """(r, p) with r b_F - m_F . p = 1 for every facet, or None when P is not Gorenstein.

    The homogenised facet forms (b_F, -m_F) span Q^(d+1), so the system has
    at most one rational solution; P is Gorenstein of index r exactly when it
    is integral. A point is reflexive, with r = 1 and p = ().

    Raises
    ------
    ComputationError
        If the solution is not unique or r is not positive, which would be a
        bug.
    """
    if polytope.body is None:
        return 1, ()
    facets = polytope.facets
    solution = _solve([(b, *(-x for x in m)) for m, b in facets], [1] * len(facets))
    if solution is None or any(x.denominator != 1 for x in solution):
        return None
    r, *p = (int(x) for x in solution)
    if r < 1:
        raise ComputationError(f"the Gorenstein system gives r = {r}, which would be a bug")
    return r, tuple(p)


def gorenstein_index(points: PointsLike, *, lattice: Lattice = "support") -> int | None:
    """The Gorenstein index of P = conv(points), or None when P is not Gorenstein.

    With the facets written m_F . c <= b_F, m_F primitive, P is Gorenstein of
    index r when rP has a lattice point p at lattice distance 1 from every
    facet: r b_F - m_F . p = 1 for every F. That linear system has at most one
    rational solution, and r is the index when the solution is integral. P is
    reflexive when r = 1 (Batyrev 1994). A point has index 1.

    Raises
    ------
    ValidationError
        As invariant_chart.
    ComputationError
        If a consistency check fails, which would be a bug.
    """
    found = _gorenstein(_prepare(points, lattice))
    return None if found is None else found[0]


def _polar(polytope: _Polytope) -> tuple[tuple[int, ...], ...] | None:
    found = _gorenstein(polytope)
    if found is None or found[0] != 1:
        return None
    if polytope.body is None:
        return ((),)
    return tuple(sorted(tuple(-x for x in m) for m, _ in polytope.facets))


def polar_dual(
    points: PointsLike, *, lattice: Lattice = "support"
) -> tuple[tuple[int, ...], ...] | None:
    """The vertices of the polar dual of a reflexive P = conv(points), sorted; None otherwise.

    With p the interior lattice point of the reflexive P, the dual
    P* = {y : y . (c - p) >= -1 for every c in P} has the vertices -m_F, one
    per facet m_F . c <= b_F, in the dual of the lattice of invariant_chart.
    P* is reflexive and its dual is P - p. The vertices of P* may span a
    proper sublattice, as those of the cube [-1, 1]^d do, so its invariants
    are to be computed with lattice="ambient". A point has the dual {()}.

    Raises
    ------
    ValidationError
        As invariant_chart.
    ComputationError
        If a consistency check fails, which would be a bug.
    """
    return _polar(_prepare(points, lattice))


# --- lattice width -----------------------------------------------------------


def _spread(vertices: Sequence[Sequence[int]], u: Sequence[int]) -> int:
    heights = [sum(a * b for a, b in zip(u, v, strict=True)) for v in vertices]
    return max(heights) - min(heights)


def _sign_normalised(u: Sequence[int]) -> tuple[int, ...]:
    """u or -u, whichever has its first non-zero entry positive."""
    return tuple(u) if next(x for x in u if x) > 0 else tuple(-x for x in u)


def _width(polytope: _Polytope) -> tuple[int, tuple[int, ...]]:
    """The lattice width of P and the first direction that attains it.

    The coordinate directions and then the facet normals are tried first,
    and w0 is the least width among them; width 1, the least possible, ends
    the search. A direction u of width at most w0 has |u . (v - v')| <= w0 for
    all vertices, so it lies in w0 (P - P)^o, the dilate of the polar of the
    difference body. With the facets g . x <= h of P - P, h > 0, that polar
    is conv(g / h); scaled by D = lcm(h) it is the integer polytope
    Q = conv(D g / h), and the candidates are the non-zero lattice points of
    (w0 / D) Q.
    """
    d = polytope.dimension
    if d == 0:
        return 0, ()
    vertices = polytope.vertices
    axes = [tuple(int(i == j) for j in range(d)) for i in range(d)]
    normals = sorted({_sign_normalised(m) for m, _ in polytope.facets} - set(axes))
    best = min(((_spread(vertices, u), u) for u in axes + normals), key=lambda pair: pair[0])
    if best[0] == 1 or d == 1:
        return best
    differences = sorted(
        {tuple(a - b for a, b in zip(v, w, strict=True)) for v in vertices for w in vertices}
    )
    halfspaces, _ = _certified_facets(differences)
    scale = math.lcm(*(h.offset for h in halfspaces))
    polar = sorted({tuple(scale // h.offset * g for g in h.normal) for h in halfspaces})
    for u in _points(_body(polar, volume=False).levels, best[0], scale):
        if next((x for x in u if x), 0) > 0:
            spread = _spread(vertices, u)
            if spread < best[0]:
                best = (spread, u)
    return best


def lattice_width(
    points: PointsLike, *, lattice: Lattice = "support"
) -> tuple[int, tuple[int, ...]]:
    """The lattice width of P = conv(points) and a direction that attains it.

    The width in the direction u, a non-zero integer vector in the
    coordinates of invariant_chart, is max u . c - min u . c over P; the
    lattice width is the least of these. The search is complete, and the
    direction returned is the first that attains the width among the
    coordinate directions, then the facet normals in lexicographic order,
    then the other candidates in lexicographic order, each with its first
    non-zero entry positive. A point has width 0 in the direction ().

    Raises
    ------
    ValidationError
        As invariant_chart.
    ComputationError
        If a facet list fails its certificate, which would be a bug.
    """
    return _width(_prepare(points, lattice))


# --- IDP and normality -------------------------------------------------------


def _normaliz_binary() -> str | None:
    """The path of the Normaliz binary, or None; the analogue of _singular_binary."""
    return shutil.which("normaliz")


def _resolve_backend(backend: str) -> str | None:
    """The Normaliz binary to use for backend, or None for Python.

    Raises
    ------
    ComputationError
        If backend is unknown, or "normaliz" and the binary is not found.
    """
    if backend not in ("auto", "python", "normaliz"):
        raise ComputationError(
            f"Unknown backend {backend!r}. Choose 'auto', 'python' or 'normaliz'."
        )
    if backend == "python":
        return None
    binary = _normaliz_binary()
    if binary is None and backend == "normaliz":
        raise ComputationError("normaliz backend requested but the normaliz binary was not found")
    return binary


def _idp_python(polytope: _Polytope) -> bool:
    """IDP by the bound of Bruns, Gubeladze and Trung: (k+1)P = kP + P for k <= d - 2."""
    levels = polytope.levels
    base = list(_points(levels, 1))
    previous = set(base)
    for k in range(1, polytope.dimension - 1):
        current = set()
        for x in _points(levels, k + 1):
            if not any(tuple(a - b for a, b in zip(x, y, strict=True)) in previous for y in base):
                return False
            current.add(x)
        previous = current
    return True


def _idp_normaliz(polytope: _Polytope, binary: str) -> bool:
    """IDP from the Hilbert basis Normaliz computes for the cone over P.

    The vertices go in as a Normaliz polytope, whose lattice is Z^(d+1) with
    the grading by the last coordinate. P has IDP exactly when every element
    of the Hilbert basis has degree 1. The number of degree-1 elements is
    checked against the lattice points of P.

    Raises
    ------
    ComputationError
        If Normaliz fails or its output cannot be read or disagrees with the
        count of lattice points.
    """
    d = polytope.dimension
    rows = "\n".join(" ".join(str(x) for x in v) for v in polytope.vertices)
    text = f"amb_space {d + 1}\npolytope {len(polytope.vertices)}\n{rows}\nHilbertBasis\n"
    with tempfile.TemporaryDirectory(prefix="feynkit-normaliz-") as folder:
        project = Path(folder) / "polytope"
        project.with_suffix(".in").write_text(text)
        try:
            run = subprocess.run(
                [binary, "--inv", str(project)], capture_output=True, text=True, check=False
            )
        except OSError as exc:
            raise ComputationError(f"Normaliz failed to start: {exc}") from exc
        invariants = project.with_suffix(".inv")
        if run.returncode != 0 or not invariants.exists():
            message = (run.stderr or run.stdout).strip().splitlines()
            raise ComputationError(
                f"Normaliz failed with status {run.returncode}"
                + (f": {message[-1]}" if message else "")
            )
        values = {}
        for line in invariants.read_text().splitlines():
            parts = line.split()
            if len(parts) == 4 and parts[0] == "integer" and parts[2] == "=":
                values[parts[1]] = int(parts[3])
    if "hilbert_basis_elements" not in values or "degree_1_elements" not in values:
        raise ComputationError("the Normaliz output has no Hilbert basis count")
    closed, _ = _count(polytope.levels, 1)
    if values["degree_1_elements"] != closed:
        raise ComputationError(
            f"Normaliz finds {values['degree_1_elements']} lattice points of P, feynkit {closed}"
        )
    return values["hilbert_basis_elements"] == closed


def _idp(polytope: _Polytope, backend: str) -> bool:
    """IDP of P in its chart; every polytope of dimension at most 2 has it.

    With backend "auto" a failure of Normaliz falls back to Python.

    Raises
    ------
    ComputationError
        As _resolve_backend, or if Normaliz fails with backend "normaliz".
    """
    binary = _resolve_backend(backend)
    if polytope.dimension <= 2:
        return True
    if binary is not None:
        try:
            return _idp_normaliz(polytope, binary)
        except ComputationError:
            if backend == "normaliz":
                raise
    return _idp_python(polytope)


def is_idp(points: PointsLike, *, lattice: Lattice = "support", backend: str = "auto") -> bool:
    """Whether P = conv(points) has the integer decomposition property.

    P has IDP when every lattice point of kP is a sum of k lattice points of
    P, for every k >= 1. By Bruns, Gubeladze and Trung (1997) the lattice
    points of (k+1)P are sums of those of kP and of P for every k >= d - 1,
    so it suffices to check k = 1, ..., d - 2. Every polytope of dimension at
    most 2 has IDP.

    Parameters
    ----------
    backend
        "python", the reference, which lists the dilates; "normaliz", the
        Normaliz binary, which computes the Hilbert basis of the cone over
        P in exact arithmetic; or "auto", which uses Normaliz when it is
        installed and falls back to Python when it is not or fails.

    Raises
    ------
    ValidationError
        As invariant_chart.
    ComputationError
        If backend is unknown, "normaliz" is asked for and the binary is
        missing or fails, or a consistency check fails.
    """
    return _idp(_prepare(points, lattice), backend)


@dataclass(frozen=True)
class LatticeInvariants:
    """The lattice invariants of a lattice polytope P of dimension d.

    Every field but normal belongs to the chosen lattice, in whose chart
    (invariant_chart) the width direction is given.

    Attributes
    ----------
    lattice
        "support" or "ambient".
    dimension
        d.
    lattice_points, interior_points
        The numbers of lattice points of P and of its relative interior.
    ehrhart
        The coefficients c_0, ..., c_d of the Ehrhart polynomial.
    h_star
        h*_0, ..., h*_d, trailing zeros included.
    gorenstein_index
        The Gorenstein index, or None when P is not Gorenstein.
    reflexive
        Whether P is reflexive, that is Gorenstein of index 1.
    lattice_width, width_direction
        The lattice width and the first direction that attains it; see
        lattice_width.
    idp
        Whether P has the integer decomposition property.
    support_is_saturated
        Whether the points given are all the lattice points of P.
    normal
        Whether the monoid N A generated by the columns (1, alpha_j) is
        normal, that is saturated in the group Z A. It is computed in the
        support lattice whatever the lattice chosen: N A is normal exactly
        when the support holds every lattice point of P in the support
        lattice and P has IDP there. Then C[N A] is Cohen-Macaulay (Hochster
        1972).
    """

    lattice: Lattice
    dimension: int
    lattice_points: int
    interior_points: int
    ehrhart: tuple[Fraction, ...]
    h_star: tuple[int, ...]
    gorenstein_index: int | None
    reflexive: bool
    lattice_width: int
    width_direction: tuple[int, ...]
    idp: bool
    support_is_saturated: bool
    normal: bool


def lattice_invariants(
    points: PointsLike, *, lattice: Lattice = "support", backend: str = "auto"
) -> LatticeInvariants:
    """Every lattice invariant of P = conv(points) in one record; see LatticeInvariants.

    backend is that of is_idp.

    Raises
    ------
    ValidationError
        As invariant_chart.
    ComputationError
        As is_idp, or if a consistency check fails.
    """
    polytope = _prepare(points, lattice)
    closed, inner = _count(polytope.levels, 1)
    ehrhart = _ehrhart(polytope)
    found = _gorenstein(polytope)
    width, direction = _width(polytope)
    idp = _idp(polytope, backend)
    saturated = closed == len(polytope.points)
    if lattice == "support" or polytope.chart == lattice_chart(_exact.integer_points(points)):
        normal = saturated and idp
    else:
        support = _prepare(points, "support")
        normal = _count(support.levels, 1)[0] == len(support.points) and _idp(support, backend)
    return LatticeInvariants(
        lattice=lattice,
        dimension=polytope.dimension,
        lattice_points=closed,
        interior_points=inner,
        ehrhart=ehrhart,
        h_star=_h_star(polytope, ehrhart),
        gorenstein_index=None if found is None else found[0],
        reflexive=found is not None and found[0] == 1,
        lattice_width=width,
        width_direction=direction,
        idp=idp,
        support_is_saturated=saturated,
        normal=normal,
    )
