"""
Lattice invariants of a lattice polytope, computed exactly.

For P = conv(points) this module counts and lists the lattice points of the
dilates kP, and gives the Ehrhart polynomial and the h*-vector. Everything is
done in integers and Fractions, from facets certified complete by the exact
hull of feynkit._exact.

The lattice
-----------
P of dimension d is measured in one of two affine lattices:

- "support", the default: alpha_1 + L, with L spanned by the differences of
  the points. It is the lattice of normalized_volume, of the chart of
  lattice_chart and of the lattice ZA generated by the columns (1, alpha_j).
- "ambient": aff(P) cap Z^n = alpha_1 + sat(L), the usual lattice of Ehrhart
  theory.

They agree when PolytopeData.sublattice_index, [sat(L) : L], is 1. Either
way P is written in a chart x = o + S c (see invariant_chart), in which it
is a full-dimensional polytope of Z^d, and kP has the lattice k o + S Z^d.

Lattice points
--------------
Let P_j be the projection of P to the first j chart coordinates, with
certified facets a . y <= b. A point c lies in kP exactly when every prefix
(c_1, ..., c_j) lies in kP_j. Given a prefix in kP_j, each facet of P_(j+1)
with a_(j+1) != 0 bounds c_(j+1); a facet with a_(j+1) = 0 is a facet of
P_j and holds already. Every such prefix extends to a real point of
kP_(j+1), so the walk only visits prefixes of real points of kP. At the last
coordinate the integers in range are counted rather than listed. Interior
points satisfy every inequality strictly at every level, which is exact
because the projection maps the interior of kP_(j+1) onto that of kP_j.
"""

from __future__ import annotations

import math
from collections.abc import Iterator, Sequence
from dataclasses import dataclass
from fractions import Fraction
from typing import Literal

import numpy as np
import sympy as sp

from . import _exact
from .core.exceptions import ComputationError, ValidationError
from .polytope import LatticeChart, lattice_chart

__all__ = [
    "Lattice",
    "count_lattice_points",
    "ehrhart_polynomial",
    "h_star_vector",
    "invariant_chart",
    "lattice_points",
]

Lattice = Literal["support", "ambient"]

_K = sp.Symbol("k")

# One inequality a . y <= b of a projection P_j, stored as (a_1, ..., a_(j-1)), a_j, b with
# a_j != 0: the part on the prefix, the coefficient of the new coordinate, the offset.
_Bound = tuple[tuple[int, ...], int, int]

PointsLike = Sequence[Sequence[int]] | np.ndarray


# --- arguments ---------------------------------------------------------------


def _check_lattice(lattice: str) -> str:
    if lattice not in ("support", "ambient"):
        raise ValidationError(f"lattice must be 'support' or 'ambient', got {lattice!r}")
    return lattice


def _dilation(k: object) -> int:
    """k as a Python integer of at least 1.

    Raises
    ------
    ValidationError
        If k is a bool, not an integer, or below 1.
    """
    message = f"the dilation factor k must be a positive integer, got {k!r}"
    if isinstance(k, bool):
        raise ValidationError(message)
    try:
        value = _exact._as_int(k, "k")
    except ValidationError:
        raise ValidationError(message) from None
    if value < 1:
        raise ValidationError(message)
    return value


# --- charts ------------------------------------------------------------------


def _saturated_chart(chart: LatticeChart) -> LatticeChart:
    """The chart of the saturation sat(L) of the lattice of chart.

    With B^T W = [0 | H], W unimodular, S = B H^-T is a basis of sat(L) (see
    feynkit.normal_forms._chart). Its rows solve H s_i = b_i, b_i the rows of
    B. The basis is brought into Hermite normal form, the points are solved
    for in it, and the coordinates are shifted to minimum 0, as lattice_chart
    does.

    Raises
    ------
    ComputationError
        If a solve is not integral, which would be a bug.
    """
    d = len(chart.basis)
    n = len(chart.origin)
    if d == 0:
        return chart
    hermite = _exact.hermite_normal_form_with_transform([list(b) for b in chart.basis], n).hermite
    rows = []
    for i in range(n):
        solved = _exact.solve_hermite_scaled(hermite, [b[i] for b in chart.basis])
        if solved is None or solved[1] != 1:
            raise ComputationError("the basis of the saturated lattice is not integral")
        rows.append(solved[0])
    saturated = _exact.hermite_normal_form(rows, d)
    raw = []
    for c in chart.coordinates:
        x = [sum(ct * b[i] for ct, b in zip(c, chart.basis, strict=True)) for i in range(n)]
        solved = _exact.solve_hermite_scaled(saturated, x)
        if solved is None or solved[1] != 1:
            raise ComputationError(f"the chart point {c} is not in the saturated lattice")
        raw.append(solved[0])
    shift = [min(c[t] for c in raw) for t in range(d)]
    basis = tuple(tuple(saturated[i][t] for i in range(n)) for t in range(d))
    origin = tuple(
        o + sum(s * b[i] for s, b in zip(shift, basis, strict=True))
        for i, o in enumerate(chart.origin)
    )
    coordinates = tuple(tuple(c[t] - shift[t] for t in range(d)) for c in raw)
    return LatticeChart(origin=origin, basis=basis, coordinates=coordinates)


def _chart(points: list[tuple[int, ...]], lattice: str) -> LatticeChart:
    chart = lattice_chart(points)
    return _saturated_chart(chart) if lattice == "ambient" else chart


def invariant_chart(points: PointsLike, *, lattice: Lattice = "support") -> LatticeChart:
    """The chart x = o + S c in which the invariants of conv(points) are computed.

    For "support" it is lattice_chart(points), whose basis is the
    Hermite-normal-form basis of the lattice L spanned by the differences of
    the points. For "ambient" the basis is the Hermite-normal-form basis of
    sat(L), the integer points of the linear span of L, and the coordinates
    of the points generate a sublattice of Z^d of index [sat(L) : L]. The
    coordinates are non-negative with minimum 0 in both.

    Raises
    ------
    ValidationError
        If there are no points, a coordinate is not an integer, the points
        do not all have the same number of coordinates, or lattice is not
        "support" or "ambient".
    """
    _check_lattice(lattice)
    pts = _exact.integer_points(points)
    if not pts:
        raise ValidationError("invariant_chart needs at least one point")
    return _chart(pts, lattice)


# --- the polytope in its chart -----------------------------------------------


def _certified_facets(
    coordinates: list[tuple[int, ...]],
) -> tuple[list[_exact.Halfspace], _exact.FaceLattice]:
    """Facets of full-dimensional points of Z^j, j >= 2, certified complete, with the lattice.

    Raises
    ------
    ComputationError
        If the facets fail the completeness certificate, which would be a
        bug.
    """
    halfspaces = _exact.beneath_beyond(coordinates)
    try:
        lattice = _exact.certified_lattice(
            coordinates, [h.mask for h in halfspaces], len(coordinates[0])
        )
    except _exact.CertificateError as exc:
        raise ComputationError(
            f"the facets from beneath-beyond fail the completeness certificate: {exc}"
        ) from exc
    return halfspaces, lattice


def _level(forms: Sequence[tuple[Sequence[int], int]]) -> tuple[_Bound, ...]:
    """The inequalities of a projection that bound its last coordinate."""
    return tuple((tuple(a[:-1]), a[-1], b) for a, b in forms if a[-1])


@dataclass(frozen=True)
class _Polytope:
    """P in the chart of its lattice, with what the invariants need.

    Attributes
    ----------
    chart
        The chart of the chosen lattice.
    points
        The distinct chart points, sorted.
    vertices
        The vertices in chart coordinates, sorted.
    facets
        (m, b) with m . c <= b, m primitive in Z^d; empty below dimension 1.
    volume
        The normalised volume in Z^d: d! times the Euclidean volume in the
        chart.
    levels
        levels[j - 1] bounds the coordinate c_j from the facets of P_j.
    """

    chart: LatticeChart
    points: tuple[tuple[int, ...], ...]
    vertices: tuple[tuple[int, ...], ...]
    facets: tuple[tuple[tuple[int, ...], int], ...]
    volume: int
    levels: tuple[tuple[_Bound, ...], ...]

    @property
    def dimension(self) -> int:
        return len(self.chart.basis)


def _prepare(points: PointsLike, lattice: str) -> _Polytope:
    """The polytope of the points in the chart of lattice, with its projections.

    Raises
    ------
    ValidationError
        As invariant_chart.
    ComputationError
        If a facet list fails its certificate or a volume check fails, which
        would be a bug.
    """
    _check_lattice(lattice)
    pts = _exact.integer_points(points)
    if not pts:
        raise ValidationError("the lattice invariants need at least one point")
    chart = _chart(pts, lattice)
    coordinates = sorted(set(chart.coordinates))
    d = len(chart.basis)
    if d == 0:
        return _Polytope(chart, tuple(coordinates), tuple(coordinates), (), 1, ())
    if d == 1:
        low, high = coordinates[0][0], coordinates[-1][0]
        facets: list[tuple[tuple[int, ...], int]] = [((-1,), -low), ((1,), high)]
        return _Polytope(
            chart,
            tuple(coordinates),
            ((low,), (high,)),
            tuple(facets),
            high - low,
            (_level(facets),),
        )
    halfspaces, face_lattice = _certified_facets(coordinates)
    vertices = sorted(
        coordinates[_exact.mask_indices(mask)[0]] for mask, k in face_lattice.dims.items() if k == 0
    )
    simplices = _exact.pulling_simplices(face_lattice, coordinates)
    volume = _exact.simplex_volume(coordinates, simplices, 1)
    facets = [(h.normal, h.offset) for h in halfspaces]
    low, high = vertices[0][0], vertices[-1][0]
    levels = [_level([((-1,), -low), ((1,), high)])]
    for j in range(2, d):
        projected = sorted({v[:j] for v in vertices})
        projection, _ = _certified_facets(projected)
        levels.append(_level([(h.normal, h.offset) for h in projection]))
    levels.append(_level(facets))
    return _Polytope(
        chart, tuple(coordinates), tuple(vertices), tuple(facets), volume, tuple(levels)
    )


# --- the enumerator ----------------------------------------------------------


def _range(
    level: tuple[_Bound, ...], prefix: Sequence[int], num: int, den: int
) -> tuple[int, int, int, int]:
    """The closed and the strict range of the next coordinate over prefix in (num/den) P_j.

    Each bound a . y <= b of P_j becomes den (head . prefix + a_j y) <= num b,
    so den a_j y <= r with r = num b - den head . prefix, and strictly
    den a_j y <= r - 1. Returns (low, high, strict low, strict high).
    """
    low: int | None = None
    high: int | None = None
    strict_low: int | None = None
    strict_high: int | None = None
    for head, a, b in level:
        r = num * b - den * sum(h * x for h, x in zip(head, prefix, strict=True))
        q = den * a
        if q > 0:
            closed, strict = r // q, (r - 1) // q
            if high is None or closed < high:
                high = closed
            if strict_high is None or strict < strict_high:
                strict_high = strict
        else:
            closed, strict = -(r // -q), -((r - 1) // -q)
            if low is None or closed > low:
                low = closed
            if strict_low is None or strict > strict_low:
                strict_low = strict
    if low is None or high is None or strict_low is None or strict_high is None:
        raise ComputationError("a projection of the polytope is unbounded, which would be a bug")
    return low, high, strict_low, strict_high


def _count(polytope: _Polytope, num: int, den: int = 1) -> tuple[int, int]:
    """The numbers of lattice points and of interior lattice points of (num/den) P."""
    levels = polytope.levels
    if not levels:
        return 1, 1
    last = len(levels) - 1
    closed_total = interior_total = 0
    prefix: list[int] = []

    def walk(j: int, inside: bool) -> None:
        nonlocal closed_total, interior_total
        low, high, strict_low, strict_high = _range(levels[j], prefix, num, den)
        if j == last:
            closed_total += max(0, high - low + 1)
            if inside:
                interior_total += max(0, strict_high - strict_low + 1)
            return
        for value in range(low, high + 1):
            prefix.append(value)
            walk(j + 1, inside and strict_low <= value <= strict_high)
            prefix.pop()

    walk(0, True)
    return closed_total, interior_total


def _points(
    polytope: _Polytope, num: int, den: int = 1, *, interior: bool = False
) -> Iterator[tuple[int, ...]]:
    """The lattice points of (num/den) P in chart coordinates, in lexicographic order."""
    levels = polytope.levels
    if not levels:
        yield ()
        return
    last = len(levels) - 1
    prefix: list[int] = []

    def walk(j: int) -> Iterator[tuple[int, ...]]:
        low, high, strict_low, strict_high = _range(levels[j], prefix, num, den)
        if interior:
            low, high = strict_low, strict_high
        for value in range(low, high + 1):
            prefix.append(value)
            if j == last:
                yield tuple(prefix)
            else:
                yield from walk(j + 1)
            prefix.pop()

    yield from walk(0)


# --- lattice points ----------------------------------------------------------


def lattice_points(
    points: PointsLike, k: int = 1, *, interior: bool = False, lattice: Lattice = "support"
) -> list[tuple[int, ...]]:
    """The lattice points of kP, P = conv(points), in ambient coordinates, sorted.

    A point of kP is k o + S c for c in Z^d, in the chart x = o + S c of
    invariant_chart; with lattice="ambient" these are all the integer points
    of kP. With interior=True only the points of the relative interior are
    listed; a point (d = 0) is its own interior.

    Raises
    ------
    ValidationError
        If there are no points, a coordinate is not an integer, the points
        do not all have the same number of coordinates, k is not a positive
        integer, or lattice is not "support" or "ambient".
    ComputationError
        If a consistency check fails, which would be a bug.
    """
    k = _dilation(k)
    polytope = _prepare(points, lattice)
    chart = polytope.chart
    found = []
    for c in _points(polytope, k, interior=interior):
        found.append(
            tuple(
                k * o + sum(ct * b[i] for ct, b in zip(c, chart.basis, strict=True))
                for i, o in enumerate(chart.origin)
            )
        )
    return sorted(found)


def count_lattice_points(
    points: PointsLike, k: int = 1, *, interior: bool = False, lattice: Lattice = "support"
) -> int:
    """The number of lattice points of kP, or of its relative interior; see lattice_points.

    Raises
    ------
    ValidationError, ComputationError
        As lattice_points.
    """
    k = _dilation(k)
    closed, inner = _count(_prepare(points, lattice), k)
    return inner if interior else closed


# --- Ehrhart polynomial and h*-vector ----------------------------------------


def _interpolate(nodes: Sequence[tuple[int, Fraction]]) -> list[Fraction]:
    """Coefficients, from degree 0, of the polynomial of degree below len(nodes) through them."""
    size = len(nodes)
    total = [Fraction(0)] * size
    for i, (xi, yi) in enumerate(nodes):
        basis = [Fraction(1)]
        scale = Fraction(yi)
        for j, (xj, _) in enumerate(nodes):
            if j == i:
                continue
            basis = [Fraction(0), *basis]
            for t in range(len(basis) - 1):
                basis[t] -= xj * basis[t + 1]
            scale /= xi - xj
        for t, c in enumerate(basis):
            total[t] += scale * c
    return total


def _evaluate(coefficients: Sequence[Fraction], x: int) -> Fraction:
    value = Fraction(0)
    for c in reversed(coefficients):
        value = value * x + c
    return value


def _ehrhart(polytope: _Polytope) -> tuple[Fraction, ...]:
    """The coefficients c_0, ..., c_d of the Ehrhart polynomial.

    L(0) = 1, the leading coefficient is vol / d!, and one walk of kP gives
    L(k) and, by reciprocity, L(-k) = (-1)^d L_interior(k), for k up to
    ceil(d/2). The rest of the polynomial is interpolated through L(0) and
    the next d - 1 values in the order L(1), L(-1), L(2), L(-2), ...; the
    values left over are checked.

    Raises
    ------
    ComputationError
        If a value left over disagrees, which would be a bug.
    """
    d = polytope.dimension
    if d == 0:
        return (Fraction(1),)
    known = {0: 1}
    for k in range(1, math.ceil(d / 2) + 1):
        closed, inner = _count(polytope, k)
        known[k] = closed
        known[-k] = (-1) ** d * inner
    lead = Fraction(polytope.volume, math.factorial(d))
    order = sorted(known, key=lambda x: (abs(x), -x))
    nodes = [(x, known[x] - lead * x**d) for x in order[:d]]
    coefficients = (*_interpolate(nodes), lead)
    for x in order[d:]:
        if _evaluate(coefficients, x) != known[x]:
            raise ComputationError(
                f"the Ehrhart polynomial gives {_evaluate(coefficients, x)} at {x}, "
                f"the count {known[x]}"
            )
    return coefficients


def _h_star(polytope: _Polytope, ehrhart: Sequence[Fraction]) -> tuple[int, ...]:
    """h*_i = sum_j (-1)^j binom(d + 1, j) L(i - j), checked integral and non-negative.

    Raises
    ------
    ComputationError
        If an entry is not a non-negative integer, h*_0 is not 1, or the sum
        is not the volume, which would be a bug.
    """
    d = polytope.dimension
    values = [_evaluate(ehrhart, k) for k in range(d + 1)]
    h_star = [
        sum(((-1) ** j * math.comb(d + 1, j) * values[i - j] for j in range(i + 1)), Fraction(0))
        for i in range(d + 1)
    ]
    if (
        any(h.denominator != 1 or h < 0 for h in h_star)
        or h_star[0] != 1
        or sum(h_star) != polytope.volume
    ):
        raise ComputationError(
            f"the h*-vector {[str(h) for h in h_star]} is not a vector of non-negative integers "
            f"with h*_0 = 1 and sum {polytope.volume}"
        )
    return tuple(int(h) for h in h_star)


def ehrhart_polynomial(points: PointsLike, *, lattice: Lattice = "support") -> sp.Poly:
    """The Ehrhart polynomial L(k) of P = conv(points), in the symbol k over QQ.

    L(k) is the number of lattice points of kP for every integer k >= 1, and
    (-1)^d L(-k) the number in its relative interior. It has degree d, the
    dimension of P, constant term 1 and leading coefficient vol / d!, with
    the volume normalised in the chosen lattice.

    Raises
    ------
    ValidationError
        As invariant_chart.
    ComputationError
        If a consistency check fails, which would be a bug.
    """
    coefficients = _ehrhart(_prepare(points, lattice))
    expr = sum(
        (sp.Rational(c.numerator, c.denominator) * _K**i for i, c in enumerate(coefficients)),
        sp.Integer(0),
    )
    return sp.Poly(expr, _K, domain=sp.QQ)


def h_star_vector(points: PointsLike, *, lattice: Lattice = "support") -> tuple[int, ...]:
    """The h*-vector (h*_0, ..., h*_d) of P = conv(points), trailing zeros included.

    It is defined by sum_(k >= 0) L(k) t^k = h*(t) / (1 - t)^(d + 1), L the
    Ehrhart polynomial. Its entries are non-negative integers with h*_0 = 1,
    h*_d the number of interior lattice points of P and sum the normalised
    volume (Beck and Robins 2015).

    Raises
    ------
    ValidationError
        As invariant_chart.
    ComputationError
        If a consistency check fails, which would be a bug.
    """
    polytope = _prepare(points, lattice)
    return _h_star(polytope, _ehrhart(polytope))
