"""
Lattice polytopes: the face lattice, facet inequalities and normalised volume.

A polytope P = conv(points) with integer points is described by its faces,
each given as the indices of all the points lying on it, by its facet
inequalities and by its normalised volume, all computed in integer
arithmetic.

The facets come from an integer beneath-beyond construction, or on request
from Qhull or Normaliz candidates, each verified exactly. The list is
certified complete before anything is derived from it: every edge of the
face lattice the candidates generate has two vertices, every face of
dimension at least 2 has a candidate facet, and along every chain R < F < Q
exactly two candidate facets of Q contain R. A Qhull or Normaliz list that
fails the certificate is replaced by beneath-beyond, and a failure there
raises ComputationError.

For a full-dimensional P each facet is m . x <= b with m primitive in Z^n
and pointing outwards. A lower-dimensional P is handled in its lattice chart
x = o + B c, where its points generate Z^d affinely. Its facets relative to
the affine hull are lifted to primitive ambient forms mu . x <= b, which
with the affine-hull equations cut out P; PolytopeData.facets stays empty
and PolytopeData.relative_facets holds them. Each facet also carries its
lattice index g_F, the gcd of b - m . alpha_j over the points, so that
(b, -m) / g_F is the facet form primitive with respect to the lattice ZA
generated by the homogenised points (1, alpha_j).

The normalised volume is measured in the lattice L the differences of the
points span, from a pulling triangulation of the certified face lattice.
For a full-dimensional configuration, generic coefficients and non-resonant
beta it is the holonomic rank of the associated GKZ system. Below full
dimension the rows of the homogenised A are linearly dependent, and for
generic beta the system has no non-zero solutions.
"""

from __future__ import annotations

import importlib.util
import math
from collections.abc import Sequence
from dataclasses import dataclass, field
from fractions import Fraction

import numpy as np

from . import _exact
from .core.exceptions import ComputationError, ValidationError

__all__ = [
    "Facet",
    "LatticeChart",
    "PolytopeData",
    "faces",
    "lattice_chart",
    "lattice_coordinates",
    "normalized_volume",
    "polytope_data",
]


# --- data types --------------------------------------------------------------


@dataclass(frozen=True)
class LatticeChart:
    """Lattice coordinates x = o + B c for conv(points).

    Attributes
    ----------
    origin
        o, an integer point of the affine hull.
    basis
        The d columns of B, each of length n: the Hermite-normal-form basis, in
        SymPy's convention, of the lattice L spanned by the differences of the
        points.
    coordinates
        c_j for each point, with alpha_j = o + B c_j. Every coordinate is
        non-negative with minimum 0, and the c_j generate Z^d affinely.
    """

    origin: tuple[int, ...]
    basis: tuple[tuple[int, ...], ...]
    coordinates: tuple[tuple[int, ...], ...]

    def to_ambient(self, c: Sequence[int]) -> tuple[int, ...]:
        """The ambient point o + B c.

        Raises
        ------
        ValidationError
            If c does not have one entry per basis vector, or an entry is not
            an integer.
        """
        if len(c) != len(self.basis):
            raise ValidationError(f"chart coordinates have length {len(self.basis)}, got {len(c)}")
        entries = [_exact._as_int(x, "the chart point") for x in c]
        return tuple(
            o + sum(e * b[k] for e, b in zip(entries, self.basis, strict=True))
            for k, o in enumerate(self.origin)
        )


@dataclass(frozen=True)
class Facet:
    """One facet of a lattice polytope P: normal . x <= offset for every x in P.

    For a full-dimensional P the normal m is primitive in Z^n and points
    outwards. For a lower-dimensional P the facet is relative to the affine
    hull, and the normal mu is a primitive integer form; the inequalities of
    all the relative facets, with the equations in PolytopeData.affine_hull,
    cut out P. mu is unique modulo the forms vanishing on the affine hull,
    and a canonical representative is chosen.

    Attributes
    ----------
    normal
        The primitive integer normal, m or mu.
    offset
        The right-hand side b.
    point_indices
        Indices into PolytopeData.points of the points on the facet, those
        with normal . x = offset.
    lattice_normal, lattice_offset
        The facet as m' . c <= b' in the lattice chart PolytopeData.chart, with
        m' primitive in Z^d, so that B^T normal = lattice_index * m' and
        offset - normal . o = lattice_index * b'. None for a Facet built by
        hand.
    lattice_index
        g_F, the gcd over the points of offset - normal . alpha_j. For a facet
        from polytope_data the form homogenised_form / g_F is primitive with
        respect to the lattice ZA generated by the columns (1, alpha_j). A
        Facet built by hand has lattice_index 1 unless one is given, and its
        lattice_form is then primitive on ZA exactly when g_F = 1 for that
        facet, which holds for every facet when ZA = Z^(n+1).
    """

    normal: tuple[int, ...]
    offset: int
    point_indices: tuple[int, ...]
    lattice_normal: tuple[int, ...] | None = field(default=None, kw_only=True)
    lattice_offset: int | None = field(default=None, kw_only=True)
    lattice_index: int = field(default=1, kw_only=True)

    @property
    def homogenised_form(self) -> tuple[int, ...]:
        """(b, -m_1, ..., -m_n): the form l(y_0, y) = b y_0 - m . y, zero on the facet's columns."""
        return (self.offset, *(-m for m in self.normal))

    @property
    def lattice_form(self) -> tuple[Fraction, ...]:
        """homogenised_form / g_F: non-negative on the columns and zero exactly on F.

        For a facet from polytope_data it is primitive on ZA. For a Facet built
        by hand with the default lattice_index 1 it is homogenised_form, which
        is primitive on ZA exactly when g_F = 1 for that facet, which holds for
        every facet when ZA = Z^(n+1). For a lower-dimensional P it is defined
        modulo the affine-hull forms.
        """
        return tuple(Fraction(x, self.lattice_index) for x in self.homogenised_form)


@dataclass(frozen=True)
class PolytopeData:
    """The face lattice, facet inequalities and volume of conv(points).

    Attributes
    ----------
    points
        The points, in the order they were given; not only the vertices.
    ambient_dimension
        Number of coordinates of each point.
    dimension
        Affine dimension of the polytope.
    vertex_indices
        Indices of the points that are vertices.
    faces
        Every face as (dimension, indices of the points on it), including the
        vertices and the polytope itself.
    facets
        The codimension-one faces as inequalities; empty unless the polytope
        is full-dimensional.
    normalized_volume
        Volume normalised so that a simplex whose edges form a basis of the
        lattice L spanned by the differences of the points has volume 1,
        computed exactly.
    relative_facets
        The facets relative to the affine hull, for every polytope of
        dimension at least 1; equal to facets when the polytope is
        full-dimensional.
    affine_hull
        Rows (h_0, h_1, ..., h_n) with h_0 + h_1 x_1 + ... + h_n x_n = 0 on
        the polytope; empty when it is full-dimensional. The vectors
        (h_1, ..., h_n), taken as columns, are a basis in Hermite normal form
        of the integer forms vanishing on L; h_0, fixed by the first point, is
        not part of that Hermite normal form.
    chart
        The lattice chart x = o + B c; see LatticeChart.
    smith_invariants
        The non-zero Smith invariants of the difference matrix, as
        AConfiguration.smith_invariants gives them.
    """

    points: tuple[tuple[int, ...], ...]
    ambient_dimension: int
    dimension: int
    vertex_indices: tuple[int, ...]
    faces: tuple[tuple[int, tuple[int, ...]], ...]
    facets: tuple[Facet, ...]
    normalized_volume: int
    relative_facets: tuple[Facet, ...]
    affine_hull: tuple[tuple[int, ...], ...]
    chart: LatticeChart
    smith_invariants: tuple[int, ...]

    @property
    def sublattice_index(self) -> int:
        """[sat(L) : L], the product of the Smith invariants; [Z^n : L] when full-dimensional."""
        return math.prod(self.smith_invariants)

    @property
    def is_full_dimensional(self) -> bool:
        """Whether the polytope spans its ambient space."""
        return self.dimension == self.ambient_dimension

    @property
    def f_vector(self) -> tuple[int, ...]:
        """Number of faces of each dimension, from 0 up to the dimension."""
        counts = [0] * (self.dimension + 1)
        for d, _idx in self.faces:
            counts[d] += 1
        return tuple(counts)

    @property
    def vertices(self) -> tuple[tuple[int, ...], ...]:
        """The vertices, in the order of :attr:`vertex_indices`."""
        return tuple(self.points[i] for i in self.vertex_indices)


# --- backends ----------------------------------------------------------------

_GENERATORS = ("python", "qhull", "normaliz")


def _pynormaliz_available() -> bool:
    """Whether PyNormaliz can be imported; the analogue of _4ti2_binary and _singular_binary."""
    return importlib.util.find_spec("PyNormaliz") is not None


def _resolve_backend(backend: str) -> str:
    """The facet generator for backend; "auto" is "python" until Normaliz has been timed."""
    if backend == "auto":
        return "python"
    if backend not in _GENERATORS:
        raise ComputationError(
            f"Unknown backend {backend!r}. Choose 'auto', 'python', 'qhull' or 'normaliz'."
        )
    if backend == "normaliz" and not _pynormaliz_available():
        raise ComputationError(
            "normaliz backend requested but PyNormaliz is not installed. "
            "Install it with: pip install PyNormaliz"
        )
    return backend


def _qhull_candidates(coords: list[tuple[int, ...]]) -> list[_exact.Halfspace] | None:
    """Facet candidates from Qhull, each verified exactly; None when Qhull fails.

    Each Qhull facet contributes its simplex and the points within 1e-7 of its
    equation, and verify_facet picks d affinely independent points from them:
    Qhull triangulates non-simplicial facets and may return flat simplices, so
    the simplex alone will not do. Rejected candidates are dropped, and a set
    of associated points already verified is skipped. Coordinates too large
    for a float count as a Qhull failure.
    """
    from scipy.spatial import ConvexHull, QhullError

    try:
        x = np.asarray(coords, dtype=float)
        hull = ConvexHull(x)
    except (QhullError, ValueError, OverflowError):
        return None
    everything = range(len(coords))
    seen: set[frozenset[int]] = set()
    found: dict[tuple[tuple[int, ...], int], _exact.Halfspace] = {}
    for simplex, equation in zip(hull.simplices, hull.equations, strict=True):
        near = np.flatnonzero(np.abs(x @ equation[:-1] + equation[-1]) < 1e-7)
        associated = list(dict.fromkeys([*map(int, simplex), *map(int, near)]))
        key = frozenset(associated)
        if key in seen:
            continue
        seen.add(key)
        halfspace = _exact.verify_facet(coords, associated, everything)
        if halfspace is not None:
            found.setdefault((halfspace.normal, halfspace.offset), halfspace)
    return list(found.values())


def _normaliz_candidates(coords: list[tuple[int, ...]]) -> list[_exact.Halfspace] | None:
    """Facet candidates from PyNormaliz's support hyperplanes, verified exactly.

    The points go in as vertices with the homogenising coordinate 1 last, and
    each hyperplane lambda, with lambda . (x, 1) >= 0 on P, contributes the
    points on which it vanishes. Returns None when anything inside PyNormaliz
    fails: the import, the cone or its hyperplanes. Its own errors,
    NormalizError and NormalizInterfaceError, are classes of its compiled
    module that derive directly from Exception, and its input conversion
    raises ordinary Python errors too, so the calls into it are guarded by one
    broad except. That costs nothing: every candidate is verified, and a
    failure only means falling back to beneath-beyond.
    """
    try:
        import PyNormaliz

        cone = PyNormaliz.Cone(vertices=[[*p, 1] for p in coords])
        forms = [[int(v) for v in form] for form in cone.SupportHyperplanes()]
    except Exception:
        return None
    everything = range(len(coords))
    found: dict[tuple[tuple[int, ...], int], _exact.Halfspace] = {}
    for form in forms:
        if len(form) != len(coords[0]) + 1:
            continue
        *linear, constant = form
        associated = [j for j, p in enumerate(coords) if _exact.dot(linear, p) + constant == 0]
        halfspace = _exact.verify_facet(coords, associated, everything)
        if halfspace is not None:
            found.setdefault((halfspace.normal, halfspace.offset), halfspace)
    return list(found.values())


def _certified_hull(
    coords: list[tuple[int, ...]], backend: str
) -> tuple[list[_exact.Halfspace], _exact.FaceLattice, str]:
    """Verified, certified facets of full-dimensional coords, the lattice, and the generator used.

    "qhull" and "normaliz" fall back to beneath-beyond when their generator
    fails or their list fails the certificate. On the "python" path a failed
    certificate is a bug and raises.
    """
    dimension = len(coords[0])
    if backend in ("qhull", "normaliz"):
        candidates = (
            _qhull_candidates(coords) if backend == "qhull" else _normaliz_candidates(coords)
        )
        if candidates is not None:
            try:
                lattice = _exact.certified_lattice(coords, [h.mask for h in candidates], dimension)
            except _exact.CertificateError:
                pass
            else:
                return candidates, lattice, backend
    halfspaces = _exact.beneath_beyond(coords)
    try:
        lattice = _exact.certified_lattice(coords, [h.mask for h in halfspaces], dimension)
    except _exact.CertificateError as exc:
        raise ComputationError(
            "the facets from beneath-beyond fail the completeness certificate, which is a bug "
            f"in feynkit: {exc}"
        ) from exc
    return halfspaces, lattice, "python"


# --- lattice chart -----------------------------------------------------------


def _differences(points: Sequence[Sequence[int]]) -> list[list[int]]:
    """The difference matrix: one row p - points[0] for each later point p."""
    base = points[0]
    return [[a - b for a, b in zip(p, base, strict=True)] for p in points[1:]]


def lattice_chart(points: Sequence[Sequence[int]] | np.ndarray) -> LatticeChart:
    """The lattice chart x = o + B c of conv(points).

    The columns of B are the Hermite normal form, in SymPy's convention, of
    the matrix whose columns are the differences alpha_j - alpha_1, so they
    are a basis of the lattice L those differences span. Each point is
    alpha_j = o + B c_j with c_j in Z^d, shifted so that every coordinate has
    minimum 0; in the chart the points generate Z^d affinely.

    Raises
    ------
    ValidationError
        If there are no points, points is not a sequence of coordinate
        sequences or a two-dimensional array, a coordinate is not an integer,
        or the points do not all have the same number of coordinates.
    ComputationError
        If a point is not in the lattice spanned by the differences, which
        would be a bug.
    """
    pts = _exact.integer_points(points)
    if not pts:
        raise ValidationError("lattice_chart needs at least one point")
    base = pts[0]
    ambient = len(base)
    columns = _differences(pts)
    hermite = _exact.hermite_normal_form(
        [[row[k] for row in columns] for k in range(ambient)], len(columns)
    )
    rank = len(hermite[0]) if hermite else 0
    basis = tuple(tuple(hermite[k][t] for k in range(ambient)) for t in range(rank))
    raw: list[list[int]] = []
    for point in pts:
        solved = _exact.solve_hermite_scaled(
            hermite, [a - b for a, b in zip(point, base, strict=True)]
        )
        if solved is None or solved[1] != 1:
            raise ComputationError(
                f"point {point} is not in the lattice spanned by the differences"
            )
        raw.append(solved[0])
    shift = [min(c[t] for c in raw) for t in range(rank)]
    coordinates = tuple(tuple(c[t] - shift[t] for t in range(rank)) for c in raw)
    origin = tuple(
        base[k] + sum(s * b[k] for s, b in zip(shift, basis, strict=True)) for k in range(ambient)
    )
    return LatticeChart(origin=origin, basis=basis, coordinates=coordinates)


def lattice_coordinates(pts: Sequence[Sequence[int]] | np.ndarray) -> list[tuple[int, ...]]:
    """Integer coordinates of the points in the lattice their differences span.

    The coordinates of lattice_chart(pts): non-negative, in the
    Hermite-normal-form basis of the difference lattice.

    Raises
    ------
    ValidationError
        From lattice_chart: if there are no points, pts is not a sequence of
        coordinate sequences or a two-dimensional array, a coordinate is not
        an integer, or the points do not all have the same number of
        coordinates.
    ComputationError
        From lattice_chart: if a point is not in the lattice spanned by the
        differences, which would be a bug.
    """
    return list(lattice_chart(pts).coordinates)


# --- certified hull ----------------------------------------------------------


@dataclass(frozen=True)
class _Hull:
    """The certified facets and face lattice from which every result is derived.

    coordinates are ambient when in_chart is false (P full-dimensional of
    dimension at least 2, or a point) and chart coordinates otherwise; the
    halfspaces are facets in those coordinates.
    """

    points: tuple[tuple[int, ...], ...]
    dimension: int
    in_chart: bool
    coordinates: tuple[tuple[int, ...], ...]
    halfspaces: tuple[_exact.Halfspace, ...]
    lattice: _exact.FaceLattice
    generator: str

    @property
    def faces(self) -> list[tuple[int, tuple[int, ...]]]:
        """Every face as (dimension, indices), sorted by dimension and then indices."""
        return sorted(
            (k, tuple(_exact.mask_indices(mask))) for mask, k in self.lattice.dims.items()
        )


def _segment(
    coordinates: list[tuple[int, ...]],
) -> tuple[list[_exact.Halfspace], _exact.FaceLattice]:
    """A segment 0 <= c <= c_max in its chart coordinate c: two vertices, -c <= 0, c <= c_max."""
    top = (1 << len(coordinates)) - 1
    c_max = max(c[0] for c in coordinates)
    low = sum(1 << j for j, c in enumerate(coordinates) if c[0] == 0)
    high = sum(1 << j for j, c in enumerate(coordinates) if c[0] == c_max)
    lattice = _exact.FaceLattice(top, {top: 1, low: 0, high: 0}, {top: tuple(sorted((low, high)))})
    return [_exact.Halfspace((-1,), 0, low), _exact.Halfspace((1,), c_max, high)], lattice


def _hull(points: list[tuple[int, ...]], backend: str, chart: LatticeChart | None = None) -> _Hull:
    """The certified hull of the non-empty points.

    A full-dimensional polytope of dimension at least 2 is handled in ambient
    coordinates, every other polytope of dimension at least 1 in its lattice
    chart, where it is full-dimensional. Points and segments are closed-form.
    """
    backend = _resolve_backend(backend)
    ambient = len(points[0])
    dimension = _exact.affine_rank(points)
    top = (1 << len(points)) - 1
    if dimension == 0:
        lattice = _exact.FaceLattice(top, {top: 0}, {})
        return _Hull(tuple(points), 0, False, tuple(points), (), lattice, "closed form")
    in_chart = dimension < ambient or dimension == 1
    if in_chart:
        coordinates = list((chart if chart is not None else lattice_chart(points)).coordinates)
    else:
        coordinates = points
    if dimension == 1:
        halfspaces, lattice = _segment(coordinates)
        generator = "closed form"
    else:
        halfspaces, lattice, generator = _certified_hull(coordinates, backend)
    return _Hull(
        tuple(points),
        dimension,
        in_chart,
        tuple(coordinates),
        tuple(halfspaces),
        lattice,
        generator,
    )


# --- facet forms -------------------------------------------------------------


@dataclass(frozen=True)
class _Lift:
    """What lifting chart forms to ambient forms needs; see _lift_form."""

    origin: tuple[int, ...]
    basis: tuple[tuple[int, ...], ...]
    hermite: list[list[int]]  # H, the Hermite normal form of B^T, d x d
    preimages: list[list[int]]  # u_1, ..., u_d in Z^n with B^T u_t = column t of H
    kernel: list[list[int]]  # Hermite normal form of the forms vanishing on L, n x (n - d)
    affine_hull: tuple[tuple[int, ...], ...]


def _lift_data(points: list[tuple[int, ...]], chart: LatticeChart) -> _Lift:
    """The Hermite normal form of B^T with its transform, and the forms vanishing on L.

    B^T U = [0 | H] with U unimodular: the first n - d columns of U are a basis
    of the integer forms vanishing on L, and the last d are the preimages u_t.
    That basis is put into Hermite normal form, which depends only on L, so
    the affine-hull equations come out canonical and as small as L allows,
    whatever the size of U. Taking B^T, d x n, rather than the difference
    matrix keeps the cost independent of the number of points.
    """
    ambient = len(points[0])
    transposed = _exact.hermite_normal_form_with_transform([list(b) for b in chart.basis], ambient)
    vanishing = transposed.kernel
    kernel = _exact.hermite_normal_form(
        [[v[i] for v in vanishing] for i in range(ambient)], len(vanishing)
    )
    affine_hull = tuple(
        (
            -sum(kernel[i][t] * points[0][i] for i in range(ambient)),
            *(kernel[i][t] for i in range(ambient)),
        )
        for t in range(len(vanishing))
    )
    return _Lift(
        chart.origin, chart.basis, transposed.hermite, transposed.image, kernel, affine_hull
    )


def _lift_form(lift: _Lift, normal: Sequence[int], offset: int) -> tuple[tuple[int, ...], int, int]:
    """Lift the chart facet normal . c <= offset to (mu, b, t), with mu . x <= b.

    t is the least positive integer with t * normal in B^T Z^n: solve H y =
    normal over Q, H the Hermite normal form of B^T, and take the least common
    denominator of y. Then mu = sum_s t y_s u_s satisfies B^T mu = t * normal;
    it is reduced modulo the forms vanishing on L, and b = mu . o +
    t * offset. mu is primitive and t is the lattice index of the lifted facet.

    Raises
    ------
    ComputationError
        If the form does not lift or the lift fails its check, which would be
        a bug.
    """
    solved = _exact.solve_hermite_scaled(lift.hermite, normal)
    if solved is None:
        raise ComputationError(
            f"the chart form {tuple(normal)} does not lift to the ambient lattice"
        )
    scaled, t = solved
    ambient = len(lift.origin)
    mu = [
        sum(z * u[i] for z, u in zip(scaled, lift.preimages, strict=True)) for i in range(ambient)
    ]
    mu = _exact.reduce_modulo(mu, lift.kernel)
    if [_exact.dot(b, mu) for b in lift.basis] != [t * m for m in normal]:
        raise ComputationError(
            f"lifting the chart form {tuple(normal)} failed its check B^T mu = t m'"
        )
    return tuple(mu), _exact.dot(mu, lift.origin) + t * offset, t


def _relative_facet(lift: _Lift, halfspace: _exact.Halfspace) -> Facet:
    """A facet computed in chart coordinates, lifted to the ambient lattice."""
    mu, beta, t = _lift_form(lift, halfspace.normal, halfspace.offset)
    return Facet(
        mu,
        beta,
        tuple(_exact.mask_indices(halfspace.mask)),
        lattice_normal=halfspace.normal,
        lattice_offset=halfspace.offset,
        lattice_index=t,
    )


def _ambient_facet(chart: LatticeChart, halfspace: _exact.Halfspace) -> Facet:
    """A facet m . x <= b computed in ambient coordinates, with its chart form and lattice index.

    g_F is the gcd of B^T m, the gcd of m over L; then m' = B^T m / g_F and
    b' = (b - m . o) / g_F.

    Raises
    ------
    ComputationError
        If the facet has no integral chart form, which would be a bug.
    """
    image = [_exact.dot(b, halfspace.normal) for b in chart.basis]
    g = math.gcd(*image)
    rest = halfspace.offset - _exact.dot(halfspace.normal, chart.origin)
    if g == 0 or rest % g:
        raise ComputationError(
            f"the facet {halfspace.normal} . x <= {halfspace.offset} has no integral chart form"
        )
    return Facet(
        halfspace.normal,
        halfspace.offset,
        tuple(_exact.mask_indices(halfspace.mask)),
        lattice_normal=tuple(x // g for x in image),
        lattice_offset=rest // g,
        lattice_index=g,
    )


# --- public API --------------------------------------------------------------


def faces(
    pts: np.ndarray | Sequence[Sequence[int]], *, backend: str = "auto"
) -> list[tuple[int, tuple[int, ...]]]:
    """All faces of conv(pts) as (dimension, indices of the points on the face).

    Includes the vertices and the polytope itself, sorted by dimension and
    then indices. Every point on a face is listed in it, repeated points
    included. The facets are computed and certified complete in integer
    arithmetic; see polytope_data for backend.

    Raises
    ------
    ValidationError
        If pts is not a sequence of coordinate sequences or a two-dimensional
        array, a coordinate is not an integer, or the points do not all have
        the same number of coordinates.
    ComputationError
        If backend is unknown or unavailable, or the facets from beneath-beyond
        fail the completeness certificate, which would be a bug.
    """
    points = _exact.integer_points(pts)
    if not points:
        _resolve_backend(backend)
        return []
    return _hull(points, backend).faces


def polytope_data(
    points: Sequence[Sequence[int]] | np.ndarray, *, backend: str = "auto"
) -> PolytopeData:
    """Face lattice, facet inequalities and normalised volume of conv(points).

    Parameters
    ----------
    points
        Integer points, one row per point; repeated points are allowed.
    backend
        Where facet candidates come from: "python" (beneath-beyond, the
        reference), "qhull" (scipy's Qhull, falling back to "python" when it
        fails or its list is incomplete), "normaliz" (PyNormaliz, which must
        be installed; same fallback) or "auto", which is "python". Every
        candidate is verified and the list certified complete in integer
        arithmetic, so every backend returns the same PolytopeData.

    Raises
    ------
    ValidationError
        If there are no points, points is not a sequence of coordinate
        sequences or a two-dimensional array, a coordinate is not an integer,
        or the points do not all have the same number of coordinates.
    ComputationError
        If backend is unknown, if "normaliz" is requested without PyNormaliz,
        or if a consistency check fails (the completeness certificate on the
        "python" path, a simplex determinant in the volume that is not a
        positive multiple of [Z^n : L], or a facet form that does not carry
        over between the chart and Z^n), which would be a bug.
    """
    pts = _exact.integer_points(points)
    if not pts:
        raise ValidationError("polytope_data needs at least one point")
    ambient = len(pts[0])
    chart = lattice_chart(pts)
    hull = _hull(pts, backend, chart)
    # The rows of B^T are a basis of the lattice the rows of the difference matrix span, so the
    # two matrices have the same non-zero Smith invariants; B^T has d rows, not one per point.
    smith = tuple(_exact.smith_invariants([list(b) for b in chart.basis], ambient))
    lift = _lift_data(pts, chart)
    if hull.in_chart:
        relative = [_relative_facet(lift, h) for h in hull.halfspaces]
    else:
        relative = [_ambient_facet(chart, h) for h in hull.halfspaces]
    relative.sort(key=lambda f: f.point_indices)
    all_faces = tuple(hull.faces)
    return PolytopeData(
        points=tuple(pts),
        ambient_dimension=ambient,
        dimension=hull.dimension,
        vertex_indices=tuple(sorted(idx[0] for k, idx in all_faces if k == 0)),
        faces=all_faces,
        facets=tuple(relative) if hull.dimension == ambient else (),
        normalized_volume=_volume(hull, math.prod(smith)),
        relative_facets=tuple(relative),
        affine_hull=lift.affine_hull,
        chart=chart,
        smith_invariants=smith,
    )


def normalized_volume(
    points: Sequence[Sequence[int]] | np.ndarray, *, backend: str = "auto"
) -> int:
    """Normalised volume of conv(points) in the lattice L its differences span.

    A d-simplex whose edge vectors form a basis of L has volume 1. The volume
    is the sum of |det(s_1 - s_0, ..., s_d - s_0)| over the pulling
    triangulation of the certified face lattice. When conv(points) is
    full-dimensional the determinants are taken in ambient coordinates and
    divided by [Z^n : L], the product of the Smith invariants of the
    difference matrix. Otherwise they are taken in the lattice chart, where
    the points generate Z^d. A point has volume 1, and the result is always
    positive. See polytope_data for backend.

    Raises
    ------
    ValidationError
        If there are no points, points is not a sequence of coordinate
        sequences or a two-dimensional array, a coordinate is not an integer,
        or the points do not all have the same number of coordinates.
    ComputationError
        If backend is unknown or unavailable, or a consistency check fails (the
        completeness certificate on the "python" path, or a simplex
        determinant that is not a positive multiple of [Z^n : L]), which
        would be a bug.
    """
    pts = _exact.integer_points(points)
    if not pts:
        raise ValidationError("normalized_volume needs at least one point")
    return _volume(_hull(pts, backend))


def _volume(hull: _Hull, index: int | None = None) -> int:
    """The normalised volume from the pulling triangulation of hull's certified lattice.

    In ambient coordinates the determinants are divided by index, [Z^n : L],
    which is computed from the Smith invariants of the difference matrix when
    not given; polytope_data passes the product it has already computed. In
    chart coordinates the points generate Z^d, the divisor is 1 and index is
    not used.
    """
    if hull.dimension == 0:
        return 1
    if hull.dimension == 1:
        return max(c[0] for c in hull.coordinates)
    if hull.in_chart:
        divisor = 1
    elif index is not None:
        divisor = index
    else:
        divisor = math.prod(_exact.smith_invariants(_differences(hull.points), len(hull.points[0])))
    simplices = _exact.pulling_simplices(hull.lattice, hull.points)
    return _exact.simplex_volume(hull.coordinates, simplices, divisor)
