"""
Normal cones of faces, smooth orbit charts and smooth subdivisions of cones.

Let P be a lattice polytope and L the lattice its differences span, so that
P sits in the lattice chart of :func:`~feynkit.polytope.polytope_data`, with
coordinates in Z^d, d the dimension of P. The inner normal cone of a face F is
generated by the inner normals of the facets of P through F; these cones form
the inner normal fan of P (Cox, Little and Schenck, Toric Varieties, AMS 2011,
abbreviated CLS11, Thm 2.3.2, p. 77). Here the generators are the primitive
facet forms of the chart, negated, so the cone lives in the dual lattice
N = Z^d, and its rays are the facet normals, one per facet through F. The
charts live in the lattice L the point differences span, so when L has index
above 1 in Z^n the chart torus is a quotient of the ambient one.

A cone is smooth when its rays extend to a basis of N. Then its affine toric
variety U_sigma, the chart of X_P around the orbit O_F, is
C^r x (C^*)^(d-r), r the number of rays, and a Laurent polynomial G supported
on P becomes g = x^(-v) G, a polynomial in the coordinates y_1, ..., y_r of
C^r and a Laurent polynomial in the torus coordinates t_1, ..., t_(d-r); see
:class:`OrbitChart`.

A cone that is not smooth is replaced by a smooth subdivision, built in two
steps. A regular triangulation of the rays, by a random lifting of seeded
integer heights, gives simplicial cones that use no new rays. Each simplicial
cone of multiplicity above 1 is then removed by a star (stellar) subdivision
at a non-zero lattice point of its fundamental parallelepiped, applied to the
whole fan. The multiplicity of the cone it was done for drops, and the cones
it creates have strictly smaller multiplicity (CLS11 Thm 11.1.9, p. 520, and
its proof on pp. 520 and 521; the point exists by Prop. 11.1.8(b), p. 519). Only the
cone of F is subdivided: the preimage of the orbit O_F under the toric
morphism of a subdivision is the union of the orbits O_tau with tau a cone
whose relative interior lies in that of sigma (CLS11 Lemma 3.3.21(b),
p. 135).

All arithmetic is exact, on Python integers and fractions.
"""

from __future__ import annotations

import itertools
import math
import random
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from fractions import Fraction
from typing import Any

import sympy as sp

from . import _exact
from .core.exceptions import ComputationError, ValidationError
from .polytope import PolytopeData

__all__ = [
    "NormalCone",
    "OrbitChart",
    "normal_cone",
    "orbit_cones",
    "orbit_chart",
    "smooth_subdivision",
]


# --- data types --------------------------------------------------------------


@dataclass(frozen=True)
class NormalCone:
    """The inner normal cone of a face, or a cone of a subdivision of it.

    Attributes
    ----------
    face
        Indices into PolytopeData.points of the points on the face, as in
        PolytopeData.faces.
    rays
        The generators, primitive integer vectors in Z^d, d = lattice_dimension;
        for a cone from :func:`normal_cone` the negated chart normals of the
        facets through the face, in the order of PolytopeData.relative_facets.
        Empty for the cone {0} of the polytope itself.
    simplicial
        Whether the rays are linearly independent.
    smooth
        Whether the rays are linearly independent and extend to a basis of
        Z^d, so that the toric chart of the cone is C^r x (C^*)^(d-r).
    lattice_dimension
        d, the dimension of the polytope: the length of each ray.
    """

    face: tuple[int, ...]
    rays: tuple[tuple[int, ...], ...]
    simplicial: bool
    smooth: bool
    lattice_dimension: int = 0

    @property
    def multiplicity(self) -> int | None:
        """The index of the lattice the rays generate in its saturation; None unless simplicial.

        This is mult(sigma) of CLS11 (11.1.5), p. 519, with N_sigma the
        span of the rays intersected with Z^d; it is 1 exactly when the cone
        is smooth (CLS11 Prop. 11.1.8(a), p. 519).
        """
        if not self.simplicial:
            return None
        return _multiplicity(self.rays, self.lattice_dimension)


@dataclass(frozen=True)
class OrbitChart:
    """A chart C^r_y x (C^*)^(d-r)_t around the orbit O_F, for a smooth cone.

    Let u_1, ..., u_r be the rays and w_1, ..., w_(d-r) the vectors of
    torus_basis, so that (w_1, ..., w_(d-r), u_1, ..., u_r) is a basis of Z^d.
    Its dual basis (m_1, ..., m_d) of the lattice of exponents gives the
    coordinates t_k = x^(m_k) and y_i = x^(m_(d-r+i)). A point alpha of P,
    written in the chart coordinates of the polytope, has exponent
    <w_k, alpha - v> in t_k and <u_i, alpha - v> in y_i; the second kind is
    non-negative because u_i is an inner normal at the face of v.

    Attributes
    ----------
    face
        As in NormalCone.
    rays
        The rays u_1, ..., u_r of the cone, which give the normal directions.
    torus_basis
        w_1, ..., w_(d-r), integer vectors completing the rays to a basis of
        Z^d; they give the torus coordinates. They complete a basis of the
        saturated span of the normal cone of the face, so they depend on the
        face only, not on the piece of a subdivision the rays come from.
    vertex
        v, a vertex of the face, in the chart coordinates of the polytope.
    """

    face: tuple[int, ...]
    rays: tuple[tuple[int, ...], ...]
    torus_basis: tuple[tuple[int, ...], ...]
    vertex: tuple[int, ...]

    @property
    def normal_dimension(self) -> int:
        """r, the number of y coordinates."""
        return len(self.rays)

    @property
    def torus_dimension(self) -> int:
        """d - r, the number of t coordinates."""
        return len(self.torus_basis)

    def local_equation(self, terms: Mapping[Sequence[int], Any]) -> dict[tuple[int, ...], Any]:
        """The polynomial g(t, y) = x^(-v) G of G = sum c_alpha x^alpha, as a dictionary.

        Parameters
        ----------
        terms
            The terms of G: exponent alpha in the chart coordinates of the
            polytope (PolytopeData.chart.coordinates gives them for its
            points) mapped to the coefficient. Repeated exponents are not
            possible in a mapping; coefficients may be anything that adds and
            compares with 0, and zero ones are dropped.

        Returns
        -------
        dict
            Exponents (a_1, ..., a_(d-r), b_1, ..., b_r) of t_1 ... t_(d-r)
            y_1 ... y_r, mapped to the coefficient. The b_i are non-negative;
            the a_k may be negative, g being a Laurent polynomial in t.

        Raises
        ------
        ValidationError
            If an exponent is not a sequence of d integers, or a term has a
            negative exponent in some y_i, which means that its exponent
            lies outside the cone's dual, so not in a polytope with this face
            and cone.
        """
        if not isinstance(terms, Mapping):
            raise ValidationError("terms must be a mapping from exponents to coefficients")
        d = self.normal_dimension + self.torus_dimension
        rows = self.torus_basis + self.rays
        out: dict[tuple[int, ...], Any] = {}
        for alpha, coefficient in terms.items():
            point = _int_vector(alpha, d, "an exponent")
            shifted = [a - b for a, b in zip(point, self.vertex, strict=True)]
            exponent = tuple(_exact.dot(row, shifted) for row in rows)
            if any(e < 0 for e in exponent[self.torus_dimension :]):
                raise ValidationError(
                    f"the exponent {tuple(point)} has a negative y exponent {exponent}: "
                    "it does not lie in the polytope the chart belongs to"
                )
            out[exponent] = out[exponent] + coefficient if exponent in out else coefficient
        return {k: c for k, c in out.items() if c != 0}


# --- exact helpers -----------------------------------------------------------


def _int_vector(vector: object, length: int, what: str) -> tuple[int, ...]:
    """vector as a tuple of length integers.

    Raises
    ------
    ValidationError
        If it is not a sequence of that length of integers.
    """
    try:
        entries = list(vector)  # type: ignore[call-overload]
    except TypeError:
        raise ValidationError(f"{what} must be a sequence of integers, got {vector!r}") from None
    if len(entries) != length:
        raise ValidationError(f"{what} must have {length} entries, got {len(entries)}")
    return tuple(_exact._as_int(x, what) for x in entries)


def _coefficients(basis: Sequence[Sequence[int]], target: Sequence[int]) -> list[Fraction] | None:
    """c with sum c_i basis_i = target, or None; the basis vectors are independent."""
    k, d = len(basis), len(target)
    rows = [[Fraction(basis[i][r]) for i in range(k)] + [Fraction(target[r])] for r in range(d)]
    pivots: list[int] = []
    row = 0
    for col in range(k):
        found = next((r for r in range(row, d) if rows[r][col] != 0), None)
        if found is None:
            return None
        rows[row], rows[found] = rows[found], rows[row]
        inv = 1 / rows[row][col]
        rows[row] = [x * inv for x in rows[row]]
        for r in range(d):
            if r != row and rows[r][col] != 0:
                f = rows[r][col]
                rows[r] = [x - f * y for x, y in zip(rows[r], rows[row], strict=True)]
        pivots.append(col)
        row += 1
    if any(rows[r][k] != 0 for r in range(row, d)):
        return None
    return [rows[i][k] for i in range(k)]


def _multiplicity(rays: Sequence[Sequence[int]], d: int) -> int:
    """The product of the Smith invariants of independent rays: [sat : lattice they span]."""
    return math.prod(_exact.smith_invariants([list(r) for r in rays], d)) if rays else 1


def _rank(rays: Sequence[Sequence[int]]) -> int:
    return _exact.rank([list(r) for r in rays]) if rays else 0


def _is_smooth(rays: Sequence[Sequence[int]], d: int) -> bool:
    """Whether independent rays extend to a basis of Z^d: all Smith invariants are 1."""
    if not rays:
        return True
    invariants = _exact.smith_invariants([list(r) for r in rays], d)
    return len(invariants) == len(rays) and all(x == 1 for x in invariants)


def _make_cone(face: tuple[int, ...], rays: Sequence[Sequence[int]], d: int) -> NormalCone:
    rows = tuple(tuple(r) for r in rays)
    simplicial = _rank(rows) == len(rows)
    return NormalCone(face, rows, simplicial, simplicial and _is_smooth(rows, d), d)


def _saturated_basis(rays: Sequence[Sequence[int]], d: int) -> list[list[int]]:
    """A basis of span(rays) intersected with Z^d: the kernel of the kernel."""
    if not rays:
        return []
    forms = _exact.hermite_normal_form_with_transform([list(r) for r in rays], d).kernel
    return (
        _exact.hermite_normal_form_with_transform(forms, d).kernel
        if forms
        else [[int(i == j) for j in range(d)] for i in range(d)]
    )


def _parallelepiped_points(
    rays: Sequence[Sequence[int]], d: int
) -> list[tuple[tuple[int, ...], tuple[Fraction, ...]]]:
    """The non-zero lattice points sum lambda_i u_i, 0 <= lambda_i < 1, of a simplicial cone.

    There are mult(sigma) - 1 of them (CLS11 Prop. 11.1.8(b), p. 519). The
    classes of the saturated lattice modulo the lattice of the rays form a
    finite group, generated by the basis vectors of the saturated lattice; the
    fractional part of the coefficients over the rays represents each class.
    Returns each point with its lambda, sorted.

    Raises
    ------
    ComputationError
        If a saturated basis vector is not in the span of the rays or a
        point is not integral, which would be a bug.
    """
    generators = []
    for b in _saturated_basis(rays, d):
        c = _coefficients(rays, b)
        if c is None:
            raise ComputationError("a saturated basis vector is not in the span of the rays")
        generators.append(tuple(x - math.floor(x) for x in c))
    zero = (Fraction(0),) * len(rays)
    group = {zero}
    frontier = [zero]
    while frontier:
        element = frontier.pop()
        for g in generators:
            new = tuple((x + y) % 1 for x, y in zip(element, g, strict=True))
            if new not in group:
                group.add(new)
                frontier.append(new)
    out = []
    for lam in sorted(group):
        if lam == zero:
            continue
        exact = [sum(f * r[k] for f, r in zip(lam, rays, strict=True)) for k in range(d)]
        if any(x.denominator != 1 for x in exact):
            raise ComputationError("the parallelepiped point is not integral")
        out.append((tuple(int(x) for x in exact), lam))
    return out


def _completion(rays: Sequence[Sequence[int]], d: int) -> list[list[int]]:
    """Vectors completing smooth rays to a basis of Z^d, as rows.

    With A the rays as rows, A U = [0 | I] for a unimodular U from the column
    Hermite form, since the columns of A span Z^r; then the last r rows of
    U^(-1) are the rays and the first d - r complete them.
    """
    r = len(rays)
    form = _exact.hermite_normal_form_with_transform([list(u) for u in rays], d)
    inverse = sp.Matrix(form.transform).inv()
    rows = [[int(inverse[i, j]) for j in range(d)] for i in range(d)]
    if rows[d - r :] != [list(u) for u in rays]:
        raise ComputationError("the Hermite transform does not return the rays")
    return rows[: d - r]


# --- normal cones and charts -------------------------------------------------


def _face_key(data: PolytopeData, face: Sequence[int]) -> tuple[int, ...]:
    """face as the sorted index tuple of a face of data.

    Raises
    ------
    ValidationError
        If data is not a PolytopeData, face is not a sequence of point
        indices, or its set of indices is not that of a face.
    """
    if not isinstance(data, PolytopeData):
        raise ValidationError("data must be a PolytopeData")
    try:
        indices = {_exact._as_int(i, "a face index") for i in face}
    except TypeError:
        raise ValidationError("face must be a sequence of point indices") from None
    for _dim, idx in data.faces:
        if set(idx) == indices:
            return tuple(idx)
    raise ValidationError(f"{sorted(indices)} are not the point indices of a face of the polytope")


def normal_cone(data: PolytopeData, face: Sequence[int]) -> NormalCone:
    """The inner normal cone of a face of the polytope, in the lattice chart.

    The rays are the negated chart normals of the facets through the face,
    as in the inner normal fan of CLS11 Thm 2.3.2, p. 77. For the polytope
    itself the cone is {0}, with no rays.

    Parameters
    ----------
    data
        The polytope, from :func:`~feynkit.polytope.polytope_data`.
    face
        The point indices of a face, as in data.faces; the order is free.

    Raises
    ------
    ValidationError
        If data is not a PolytopeData or face is not a face.
    ComputationError
        If a facet has no chart normal, which would be a bug.
    """
    key = _face_key(data, face)
    members = set(key)
    rays = []
    for facet in data.relative_facets:
        if facet.lattice_normal is None:
            raise ComputationError("a facet of the polytope has no chart normal")
        if members <= set(facet.point_indices):
            rays.append(tuple(-x for x in facet.lattice_normal))
    return _make_cone(key, rays, len(data.chart.basis))


def _minimal_set(data: PolytopeData, u: Sequence[int]) -> set[int]:
    """The indices of the points of the polytope where the form u is least."""
    values = [_exact.dot(u, c) for c in data.chart.coordinates]
    least = min(values)
    return {i for i, x in enumerate(values) if x == least}


def orbit_chart(
    data: PolytopeData, face: Sequence[int], cone: NormalCone | None = None
) -> OrbitChart:
    """The chart C^r x (C^*)^(d-r) of the orbit of a face, for a smooth cone.

    By default the cone is the normal cone of the face, which must be smooth.
    For a face whose cone is not, pass a smooth piece of
    ``smooth_subdivision(normal_cone(data, face))`` as cone: its rays are then
    the normal coordinates y of the chart of the subdivided variety. The torus
    basis is one completion, fixed by the face alone, of a basis of the
    saturated span of its normal cone, so the torus coordinates t are the same
    on every chart over the orbit O_F.

    Raises
    ------
    ValidationError
        If face is not a face of data, or the cone is not smooth, not a cone
        of this face, not of the dimension of the normal cone of the face, or
        has a ray outside the normal cone.
    """
    base = normal_cone(data, face)
    if cone is None:
        if not base.smooth:
            raise ValidationError(
                f"the normal cone of the face {list(base.face)} is not smooth: "
                "pass a smooth piece of its subdivision as cone"
            )
        cone = base
    else:
        if not isinstance(cone, NormalCone) or cone.face != base.face:
            raise ValidationError("cone must be a NormalCone of the same face")
        if not cone.smooth:
            raise ValidationError("cone is not smooth: subdivide it with smooth_subdivision")
        if cone.lattice_dimension != base.lattice_dimension or len(cone.rays) != _rank(base.rays):
            raise ValidationError("cone must have as many rays as the dimension of the normal cone")
        if any(not set(base.face) <= _minimal_set(data, u) for u in cone.rays):
            raise ValidationError("a ray of cone is not in the normal cone of the face")
    vertex_index = min(set(base.face) & set(data.vertex_indices))
    vertex = tuple(data.chart.coordinates[vertex_index])
    d = base.lattice_dimension
    torus = _completion(_saturated_basis(base.rays, d), d)
    return OrbitChart(base.face, cone.rays, tuple(tuple(w) for w in torus), vertex)


# --- smooth subdivision ------------------------------------------------------


def _regular_cells(
    rays: Sequence[Sequence[int]], k: int, heights: Sequence[int]
) -> list[tuple[int, ...]] | None:
    """Index sets of the cones of the regular subdivision for the heights; None if non-generic.

    A set S of k independent rays spans a cell exactly when the linear form
    lambda with lambda(u_s) = h_s has lambda(u_j) <= h_j for every other ray; a tie
    for some j means the subdivision is not simplicial, and the heights are
    rejected.
    """
    n = len(rays)
    cells = []
    for subset in itertools.combinations(range(n), k):
        basis = [rays[i] for i in subset]
        if _rank(basis) < k:
            continue
        below = True
        for j in range(n):
            if j in subset:
                continue
            c = _coefficients(basis, rays[j])
            if c is None:
                below = False
                break
            gap = heights[j] - sum(ci * heights[i] for ci, i in zip(c, subset, strict=True))
            if gap < 0:
                below = False
                break
            if gap == 0:
                return None
        if below:
            cells.append(subset)
    return cells


def _triangulate(
    rays: Sequence[tuple[int, ...]], rng: random.Random
) -> list[tuple[tuple[int, ...], ...]]:
    """The maximal cones of a regular triangulation of the cone on rays, by random lifting."""
    k = _rank(rays)
    if k == len(rays):
        return [tuple(rays)]
    for _attempt in range(50):
        heights = [rng.randint(1, 10**6) for _ in rays]
        cells = _regular_cells(rays, k, heights)
        if cells:
            return [tuple(rays[i] for i in cell) for cell in cells]
    raise ComputationError("no generic lifting found for the triangulation")


def smooth_subdivision(
    cone: NormalCone, *, seed: int = 0, max_cones: int = 5000
) -> tuple[NormalCone, ...]:
    """A subdivision of a pointed cone into smooth cones, using the face's rays and new ones.

    A regular triangulation of the rays by a seeded random lifting gives
    simplicial cones. A cone sigma of largest multiplicity above 1 is then
    removed by a star subdivision of the whole fan at a non-zero lattice point
    v = sum lambda_i u_i, 0 <= lambda_i < 1, of its fundamental parallelepiped;
    this replaces sigma, and each cone containing the minimal face of sigma
    that holds v, by cones of smaller multiplicity, and the process repeats
    (CLS11 Thm 11.1.9 and its proof, pp. 520-521). The proof works for any such
    v; here v is drawn from the seed among the points with the least sum of the
    lambda_i, which keeps the number of cones small. The result is the set of
    maximal cones, sorted by their rays; their union is the cone, and they meet
    in common faces. A smooth cone is returned unchanged. Another seed can give
    another triangulation or other points, so another subdivision.

    Parameters
    ----------
    cone
        A pointed cone, as from :func:`normal_cone`. It must be pointed;
        this is not checked.
    seed
        The seed of the random lifting and of the choice of points.
    max_cones
        The most cones the fan may have along the way.

    Raises
    ------
    ValidationError
        If cone is not a NormalCone, or seed or max_cones is not an integer.
    ComputationError
        If no generic lifting is found in 50 tries, or the fan passes
        max_cones cones; the message then starts with ``undecided: ``.
    """
    if not isinstance(cone, NormalCone):
        raise ValidationError("cone must be a NormalCone")
    seed = _exact._as_int(seed, "seed")
    max_cones = _exact._as_int(max_cones, "max_cones")
    d = cone.lattice_dimension
    if cone.smooth:
        return (cone,)
    for r in cone.rays:
        if len(r) != d:
            raise ValidationError(f"every ray must have {d} entries")
    rng = random.Random(seed)
    cones = _triangulate(cone.rays, rng)
    multiplicity = {c: _multiplicity(c, d) for c in cones}
    while True:
        if len(cones) > max_cones:
            raise ComputationError(
                f"undecided: the subdivision passed {max_cones} cones before it was smooth"
            )
        worst = max(cones, key=lambda c: (multiplicity[c], c))
        if multiplicity[worst] == 1:
            break
        points = _parallelepiped_points(worst, d)
        least = min(sum(lam) for _point, lam in points)
        point, lam = rng.choice([x for x in points if sum(x[1]) == least])
        support = {ray for ray, f in zip(worst, lam, strict=True) if f != 0}
        updated: list[tuple[tuple[int, ...], ...]] = []
        for sigma in cones:
            if support <= set(sigma):
                for u in sigma:
                    if u in support:
                        new = tuple(r for r in sigma if r != u) + (point,)
                        if new not in multiplicity:
                            multiplicity[new] = _multiplicity(new, d)
                        updated.append(new)
            else:
                updated.append(sigma)
        cones = updated
    pieces = sorted(tuple(sorted(c)) for c in cones)
    return tuple(_make_cone(cone.face, c, d) for c in pieces)


def orbit_cones(
    data: PolytopeData, pieces: Sequence[NormalCone]
) -> tuple[tuple[tuple[int, ...], ...], ...]:
    """The cones tau of a subdivision whose relative interior lies in that of the face's cone.

    These index the orbits O_tau of the subdivided toric variety above the
    orbit O_F (CLS11 Lemma 3.3.21(b), p. 135). Each is returned once, as its
    sorted rays, from the smallest to the largest; the cone {0} of the
    polytope itself gives the empty tuple. The point sum of the rays of tau is
    in the relative interior of the cone of F exactly when the points of the
    polytope where it is smallest are those of F.

    Raises
    ------
    ValidationError
        If pieces is empty, data is not a PolytopeData, or the pieces are
        not cones of one face of data.
    """
    if not pieces or not all(isinstance(c, NormalCone) for c in pieces):
        raise ValidationError("pieces must be a non-empty sequence of NormalCone")
    key = _face_key(data, pieces[0].face)
    if any(c.face != key for c in pieces):
        raise ValidationError("the pieces must all belong to one face")
    found: set[tuple[tuple[int, ...], ...]] = set()
    for piece in pieces:
        if not piece.simplicial:
            raise ValidationError("the pieces must be simplicial")
        for size in range(len(piece.rays) + 1):
            for subset in itertools.combinations(piece.rays, size):
                total = [sum(u[k] for u in subset) for k in range(piece.lattice_dimension)]
                if _minimal_set(data, total) == set(key):
                    found.add(tuple(sorted(subset)))
    return tuple(sorted(found, key=lambda t: (len(t), t)))
