"""
Dissertation: GKZ A-configuration analysis.

Compares the massless triangle and triple-K conformal 3-point integral as
GKZ A-configurations, probing three levels of equivalence:

  1. Unimodular equivalence (GL_n(Z) + translation), same GKZ D-module.
  2. Affine equivalence (GL_n(Q) + translation), same combinatorial type.
  3. Finite-index lattice map, integer linear map of index > 1.

Also computes the intrinsic lattice model (Hermite normal form basis and Smith
invariants) of each configuration, and the unimodular automorphism groups of
their Newton polytopes.

Run with:
    uv run python examples/dissertation_configuration_analysis.py
"""

import sympy as sp

from feynkit.a_configuration import finite_index_map, intrinsic_lattice_model
from feynkit.artifacts.dissertation import (
    banana3_a_config,
    four_point_simplex_a_config,
    triangle_a_config,
    triple_k_a_config,
)

SEP = "-" * 72


def print_section(title: str) -> None:
    print()
    print(SEP)
    print(f"  {title}")
    print(SEP)


def describe_config(name: str, cfg) -> None:
    hull = cfg.newton_polytope_points
    print(f"\n{name}")
    print(
        f"  A-matrix shape : {cfg.matrix.shape[0]} x {cfg.matrix.shape[1]}"
        f"  (homogenized={cfg.is_homogenized})"
    )
    print(f"  Ambient dim    : {cfg.ambient_dim}")
    print(f"  # monomials    : {cfg.n_points}")
    print(f"  Affine dim     : {cfg.affine_dim}")
    print(f"  Smith invariants: {cfg.smith_invariants}")
    print(f"  Hull vertices  : {len(hull)}")
    for pt in hull:
        print(f"    {pt}")


def describe_intrinsic(name: str, model) -> None:
    print(f"\nIntrinsic model, {name}")
    print(f"  Base point      : {model.base_point}")
    print(f"  Affine rank     : {model.intrinsic_rank}")
    print(f"  Smith invariants: {model.smith_invariants}")
    print(f"  Intrinsic coords ({len(model.intrinsic_coords)} points):")
    for c in model.intrinsic_coords:
        print(f"    {c}")


# ------------------------------------------------------------------------------
# Load configurations
# ------------------------------------------------------------------------------

print_section("Configurations")

tri = triangle_a_config()
tpk = triple_k_a_config()
ban = banana3_a_config()
s4 = four_point_simplex_a_config()

describe_config("Triangle (massless, 1-loop)", tri)
describe_config("Triple-K (conformal 3-point)", tpk)
describe_config("Banana-3 (massless)", ban)
describe_config("4-simplex (standard)", s4)


# ------------------------------------------------------------------------------
# Smith invariants, lattice classification
# ------------------------------------------------------------------------------

print_section("Smith Normal Form Invariants")

print("""
The Smith invariants classify the lattice generated by the difference vectors
of a point configuration, an invariant of the integer point set independent
of the ambient embedding.

Two configurations can be unimodularly equivalent only if their Smith
invariants agree.  Different invariants prove non-unimodular equivalence.
""")

print(f"  Triangle : Smith invariants = {tri.smith_invariants}")
print("             -> spans the full lattice Z^3  (all invariants = 1)")
print()
print(f"  Triple-K : Smith invariants = {tpk.smith_invariants}")
print("             -> spans the even-sum sublattice  (last invariant = 2)")
print("             -> index 2 in Z^3 : only points with x+y+z == 0 (mod 2)")
print()
print("  Smith invariants DIFFER -> triangle and triple-K are NOT unimodularly equivalent.")


# ------------------------------------------------------------------------------
# Unimodular equivalence (Liu-Cai)
# ------------------------------------------------------------------------------

print_section("Unimodular Equivalence (Liu-Cai)")

result_uni = tri.is_unimodular_equivalent_to(tpk)
print(f"\nTriangle ~= Triple-K  (unimodular) : {result_uni.equivalent}")
if result_uni.equivalent:
    print(f"  Witness U : {result_uni.witness_map.tolist()}")
else:
    print("  (No unimodular map exists, confirmed by Smith invariant mismatch.)")

result_uni_self = tri.is_unimodular_equivalent_to(tri)
print(f"\nTriangle ~= Triangle  (unimodular) : {result_uni_self.equivalent}")
if result_uni_self.witness_map is not None:
    print(f"  Witness U : {result_uni_self.witness_map.tolist()}")


# ------------------------------------------------------------------------------
# Affine equivalence
# ------------------------------------------------------------------------------

print_section("Affine Equivalence (rational)")

result_aff = tri.is_affinely_equivalent_to(tpk)
print(f"\nTriangle ~= Triple-K  (affine/rational) : {result_aff.equivalent}")
print("""
Interpretation:
  There exists an invertible rational affine map taking the triangle Newton
  polytope to the triple-K Newton polytope.  Specifically, the linear map

      M = [[0, 1, 1],
           [1, 0, 1],
           [1, 1, 0]]

  sends every triangle point to a triple-K point (verified below).
  det(M) = 2, so M is NOT in GL_3(Z) and the map is NOT unimodular.
""")


# ------------------------------------------------------------------------------
# Finite-index map
# ------------------------------------------------------------------------------

print_section("Finite-Index Lattice Map")

result_fim = finite_index_map(tri, tpk)
print("\nfinite_index_map(triangle -> triple-K)")
print(f"  found           : {result_fim.found}")
print(f"  determinant     : {result_fim.determinant}")
print(f"  is_unimodular   : {result_fim.is_unimodular}")
if result_fim.witness_matrix is not None:
    print("  witness M       :")
    M = result_fim.witness_matrix
    for row in M.tolist():
        print(f"                    {row}")
    t = result_fim.translation
    print(f"  translation t   : {[int(x) for x in t]}")
    print(f"  column perm     : {result_fim.column_permutation}")

print("""
A finite-index map M with |det(M)| = 2 means:
  - The image M(Z^3) is a sublattice of index 2 in Z^3.
  - The triple-K points all lie in that sublattice.
  - The two configurations have the same combinatorial shape (hence affinely
    equivalent) but the triple-K lives in a coarser lattice environment.
  - Their GKZ D-modules are related but not isomorphic over Z, they have the
    same holonomic rank but different torsion structure at the prime 2.
""")

# Manual verification.
M_known = sp.Matrix([[0, 1, 1], [1, 0, 1], [1, 1, 0]])
t_known = sp.zeros(3, 1)
tpk_set = {tuple(int(x) for x in row) for row in tpk.affine_points}
all_ok = all(
    tuple(int(x) for x in M_known * sp.Matrix(pt.tolist()) + t_known) in tpk_set
    for pt in tri.affine_points
)
print(f"  Verification (M_known applied to all triangle points in triple-K): {all_ok}")


# ------------------------------------------------------------------------------
# Intrinsic lattice models
# ------------------------------------------------------------------------------

print_section("Intrinsic Lattice Models")

print("""
The intrinsic model expresses each configuration in the Hermite normal form
basis of the lattice its difference vectors span, with its first point as
origin.
""")

model_tri = intrinsic_lattice_model(tri)
model_tpk = intrinsic_lattice_model(tpk)

describe_intrinsic("Triangle", model_tri)
describe_intrinsic("Triple-K", model_tpk)

print("""
Observation:
  The intrinsic coordinates are expressed in the Hermite normal form basis of
  the lattice of each configuration separately.  Because the bases differ, the
  coordinate sets differ even though the configurations are rationally
  affinely equivalent.

  The Smith invariants are basis-independent invariants:
    Triangle [1,1,1] -> spans Z^3 (full lattice, index 1).
    Triple-K [1,1,2] -> last generator scaled by 2 (sublattice, index 2 in Z^3).

  This index-2 discrepancy is the precise sense in which the triangle and
  triple-K GKZ systems differ as integer lattice objects.
""")


# ------------------------------------------------------------------------------
# Polytope automorphisms
# ------------------------------------------------------------------------------

print_section("Polytope Automorphism Groups")

auts_tri = tri.automorphisms()
auts_tpk = tpk.automorphisms()
auts_ban = ban.automorphisms()


def _group_name(order: int) -> str:
    return {1: "trivial", 2: "Z/2", 6: "S_3", 8: "D_4", 24: "S_4", 48: "B_3"}.get(order, "?")


print(f"\nTriangle  : |Aut(P)| = {auts_tri.order}  ({_group_name(auts_tri.order)})")
print(f"  Vertex orbits : {auts_tri.vertex_orbits}")

print(f"\nTriple-K  : |Aut(P)| = {auts_tpk.order}  ({_group_name(auts_tpk.order)})")
print(f"  Vertex orbits : {auts_tpk.vertex_orbits}")

print(f"\nBanana-3  : |Aut(P)| = {auts_ban.order}  ({_group_name(auts_ban.order)})")
print(f"  Vertex orbits : {auts_ban.vertex_orbits}")

# Derive the interpretation dynamically from the computed values.
aut_same = auts_tri.order == auts_tpk.order
_aut_interp = (
    f"""
Both Newton polytopes have |Aut(P)| = {auts_tri.order} = {_group_name(auts_tri.order)}.
This is not a coincidence: both polytopes are cross-polytopes (octahedra) in R^3.

  Triangle centred at (1/2, 1/2, 1/2):  vertices are three antipodal pairs
    +/-(1/2,1/2,-1/2), +/-(1/2,-1/2,1/2), +/-(-1/2,1/2,1/2) in integer coordinates.

  Triple-K centred at (1, 1, 1):  vertices are exactly +/-e_1, +/-e_2, +/-e_3 relative
    to the centre, the standard integer cross-polytope.

The automorphism group of any 3-dimensional cross-polytope is the hyperoctahedral
group B_3 of order 48 (the symmetry group of the octahedron / cube), so both
polytopes correctly carry |Aut(P)| = 48.

The same |Aut(P)| is consistent with affine equivalence, they are the same
abstract convex body.  What distinguishes them is purely their lattice embedding:
  - Triangle: centred at a half-integer point; its vertices span Z^3 (Smith [1,1,1]).
  - Triple-K: centred at an integer point; its vertices span the even-sum sublattice
    {{x+y+z == 0 mod 2}} of index 2 in Z^3 (Smith [1,1,2]).
The Smith invariants capture this sublattice difference; |Aut(P)| alone does not.
"""
    if aut_same
    else f"""
Triangle |Aut(P)| = {auts_tri.order}, Triple-K |Aut(P)| = {auts_tpk.order}.
These differ, confirming the two polytopes have different unimodular symmetry groups.
"""
)
print(_aut_interp)


# ------------------------------------------------------------------------------
# Summary table
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# Normalized lattice volume (= GKZ holonomic rank)
# ------------------------------------------------------------------------------

print_section("Normalized Lattice Volume (GKZ Holonomic Rank)")

vol_tri = tri.normalized_volume
vol_tpk = tpk.normalized_volume
vol_ban = ban.normalized_volume
vol_s4 = s4.normalized_volume

print(f"""
The normalised lattice volume of the Newton polytope equals the holonomic rank
of the GKZ D-module for generic parameters beta (Klausen 2020, Theorem 2.2).
This is the number of independent A-hypergeometric series in any basis;
for a Feynman integral it counts the master integrals at generic kinematics.

  Triangle   : vol = {vol_tri}  (4 independent Gamma-series / master integrals)
  Triple-K   : vol = {vol_tpk}  (same, the index-2 sublattice rescales the measure)
  Banana-3   : vol = {vol_ban}
  4-simplex  : vol = {vol_s4}

Triangle and triple-K have the same normalised volume even though their
Euclidean volumes differ by a factor of 2.  This is because the triple-K
spans a sublattice of index 2, so the lattice-normalised volume is
  vol_0 = 3! x Euclidean_volume / sublattice_index = 6 x (4/3) / 2 = 4.
The two GKZ systems are isomorphic over Q and have the same holonomic rank.
""")


# ------------------------------------------------------------------------------
# Summary table
# ------------------------------------------------------------------------------

print_section("Summary")

_snf_same = tri.smith_invariants == tpk.smith_invariants
_uni_same = result_uni.equivalent
_aff_same = result_aff.equivalent
_fim_det = result_fim.determinant if result_fim.found else " - "
_aut_same_s = "YES" if aut_same else "NO"
_vol_same = vol_tri == vol_tpk

print(f"""  Configuration pair: Triangle  vs  Triple-K

  Relation                        Result   Comment
  --------------------------------------------------------------------------
  Smith invariants equal?         {"YES" if _snf_same else "NO":<6}   {tri.smith_invariants} vs {tpk.smith_invariants}
  Unimodularly equivalent?        {"YES" if _uni_same else "NO":<6}   {"Witness found" if _uni_same else "Ruled out by Smith invariants"}
  Affinely equivalent (over Q)?   {"YES" if _aff_same else "NO":<6}   {"Witness found" if _aff_same else "Not equivalent"}
  Finite-index map (det)?         {"YES (" + str(_fim_det) + ")" if result_fim.found else "NO":<8} Index-{_fim_det} sublattice embedding
  Normalized volume (GKZ rank)    {vol_tri} vs {vol_tpk:<3}  {"Same" if _vol_same else "Different"}, same holonomic rank
  |Aut(P)| same?                  {_aut_same_s:<6}   {auts_tri.order} vs {auts_tpk.order}, both cross-polytopes (B_3)

  Physical meaning:
  - Both Newton polytopes are cross-polytopes (octahedra) with |Aut(P)| = 48 = B_3.
    This confirms they are abstractly the same convex body, consistent with
    affine equivalence.  The distinction is entirely in the lattice embedding.
  - Smith invariants [1,1,1] != [1,1,2] prove non-unimodular equivalence:
    the triangle spans Z^3 while the triple-K spans the even-sum sublattice.
  - The finite-index map M = [[0,1,1],[1,0,1],[1,1,0]] (det 2) provides an
    explicit change of basis: A_triple-K = M * A_triangle (up to column
    permutation), relating the two GKZ A-matrices.
  - Normalized volume = {vol_tri} for both: same holonomic rank, same master-integral
    count at generic kinematics.  The GKZ systems are isomorphic over Q.
  - Over Z they are NOT isomorphic: the 2-torsion in the lattice quotient
    Z^3 / (even-sum sublattice) ~= Z/2 is the residual difference.
""")
