"""
The Lee-Pomeransky GKZ system of G.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

import sympy as sp

from .._latex_kit import _LATEX_EULER_MELLIN, LatexDocument, _latex_vector
from .._report_shared import append_signed, count_noun, signed_terms
from .._text_kit import (
    _INDENT,
    _TEXT_EULER_MELLIN,
    TextDocument,
    _blocks,
    _break,
    _expressions,
    _matrix,
    _paragraph,
    _room,
    _str,
    _text_equation,
    _text_vector,
)
from ..latex import to_latex, to_latex_split
from ._base import Section, SummaryPart

if TYPE_CHECKING:
    from ..report import AnalysisReport, BuildContext


@dataclass(frozen=True)
class GKZ:
    """The Lee-Pomeransky GKZ system.

    Attributes
    ----------
    a_matrix, beta, z_variables
        The A-matrix, the parameter vector and the coefficient variables.
    euler_rows
        One (row of A, beta_r) pair per row, so that a renderer can write
        the Euler operator sum_j A_rj theta_j - beta_r.
    toric_generators
        Generators of the toric ideal of A.
    """

    a_matrix: sp.Matrix
    beta: tuple[sp.Expr, ...]
    z_variables: tuple[sp.Symbol, ...]
    euler_rows: tuple[tuple[tuple[int, ...], sp.Expr], ...]
    toric_generators: tuple[sp.Expr, ...]


def build(ctx: BuildContext) -> GKZ:
    fi = ctx.integral
    system = fi.gkz
    a_matrix = system.a_matrix
    beta = tuple(system.beta_parameters)
    euler_rows = tuple(
        (tuple(int(x) for x in a_matrix.row(r)), beta[r]) for r in range(a_matrix.rows)
    )
    return GKZ(
        a_matrix=a_matrix,
        beta=beta,
        z_variables=tuple(system.z_variables),
        euler_rows=euler_rows,
        toric_generators=tuple(fi.toric_ideal.generators),
    )


def text(_report: AnalysisReport, gkz: GKZ, doc: TextDocument) -> str:
    operators = []
    for r, (row, beta_r) in enumerate(gkz.euler_rows):
        terms = signed_terms([(a, f"theta_{j}") for j, a in enumerate(row, start=1)])
        operator = append_signed(terms, -beta_r, _str)
        operators.append(_text_equation(f"E_{r}", _break(operator, _room(f"E_{r}"))))
    blocks = [
        _paragraph(
            "Writing G = sum_j z_j u^alpha_j and treating the coefficients z_j as independent "
            "variables gives the Euler-Mellin integral"
        ),
        f"{_INDENT}{_TEXT_EULER_MELLIN},",
        _paragraph(
            "the Lee-Pomeransky integral without its prefactor, which the GKZ system "
            "annihilates. The system has the matrix"
        ),
        _matrix("A", gkz.a_matrix),
        _paragraph(
            "whose column j is (1, alpha_j). The parameter vector is "
            "beta = (-D/2, -nu_1, ..., -nu_N), the value the Euler equations require for the "
            f"Lee-Pomeransky integral{doc.cite('delacruz2019', 'klausen2020')}. Here"
        ),
        _text_vector("beta", gkz.beta, "."),
        _paragraph(
            "The Euler operators are built from theta_j = z_j d/dz_j, which measures the "
            "degree in z_j. The operators E_r = sum_j A_{rj} theta_j - beta_r annihilate I_A: "
            "row 0 states that I_A is homogeneous of degree -D/2 in the z_j, and row i that "
            "it has degree -nu_i under z_j -> lambda^(A_{ij}) z_j, which a rescaling of u_i "
            "absorbs:"
        ),
        "\n".join(operators),
    ]
    generators = gkz.toric_generators
    if not generators:
        blocks.append("The toric ideal is trivial.")
        return _blocks(*blocks)
    blocks += [
        _paragraph(
            f"The toric ideal of A is generated by {count_noun(len(generators), 'binomial')}. "
            "Each binomial z^k - z^l, with A k = A l, gives the operator "
            "(d/dz)^k - (d/dz)^l; these annihilators of I_A form an analogue of "
            f"integration-by-parts relations for it{doc.cite('chestnov2022')}, and the "
            "specialisation to physical coefficients is a separate step. The generators are"
        ),
        _expressions(generators),
    ]
    return _blocks(*blocks)


def latex(_report: AnalysisReport, gkz: GKZ, doc: LatexDocument) -> str:
    operators = []
    for r, (row, beta_r) in enumerate(gkz.euler_rows):
        terms = signed_terms([(a, f"\\theta_{{{j}}}") for j, a in enumerate(row, start=1)])
        operators.append(f"E_{{{r}}} &= {append_signed(terms, -beta_r, to_latex)}")
    parts = [
        "\\label{sec:gkz-system}",
        "Writing $G = \\sum_j z_j u^{\\alpha_j}$ and treating the coefficients $z_j$ as "
        "independent variables gives the Euler-Mellin integral",
        "\\begin{equation*}",
        _LATEX_EULER_MELLIN + ",",
        "\\end{equation*}",
        "the Lee-Pomeransky integral without its prefactor, which the GKZ system annihilates. "
        "The system has the matrix",
        "\\begin{equation*}",
        "A = " + doc.matrix(gkz.a_matrix),
        "\\end{equation*}",
        "whose column $j$ is $(1, \\alpha_j)$. The parameter vector is "
        "$\\beta = (-D/2, -\\nu_1, \\ldots, -\\nu_N)$, the value the Euler equations require "
        f"for the Lee-Pomeransky integral{doc.cite('delacruz2019', 'klausen2020')}. Here",
        "\\begin{equation*}",
        "\\beta = " + _latex_vector(gkz.beta) + ".",
        "\\end{equation*}",
        "The Euler operators are built from $\\theta_j = z_j \\partial_{z_j}$, which measures "
        "the degree in $z_j$. The operators $E_r = \\sum_j A_{rj}\\theta_j - \\beta_r$ "
        "annihilate $I_A$: row $0$ states that $I_A$ is homogeneous of degree $-D/2$ in the "
        "$z_j$, and row $i$ that it has degree $-\\nu_i$ under "
        "$z_j \\mapsto \\lambda^{A_{ij}} z_j$, which a rescaling of $u_i$ absorbs:",
        "\\begin{align*}",
        " \\\\\n".join(operators),
        "\\end{align*}",
    ]
    generators = gkz.toric_generators
    if not generators:
        parts.append("The toric ideal is trivial.")
        return "\n".join(parts)
    parts += [
        f"The toric ideal of $A$ is generated by {count_noun(len(generators), 'binomial')}. Each "
        "binomial $z^{k} - z^{l}$, with $Ak = Al$, gives the operator "
        "$\\partial^{k} - \\partial^{l}$; these annihilators of $I_A$ form an analogue of "
        f"integration-by-parts relations for it{doc.cite('chestnov2022')}, and the "
        "specialisation to physical coefficients is a separate step. The generators are",
        "\\begin{gather*}",
        " \\\\\n".join(to_latex_split(g) for g in generators),
        "\\end{gather*}",
    ]
    return "\n".join(parts)


def summary(gkz: GKZ) -> list[tuple[str, str]]:
    return [("Toric generators", str(len(gkz.toric_generators)))]


SECTION = Section(
    name="gkz",
    heading="GKZ system",
    build=build,
    text=text,
    latex=latex,
    summary=(SummaryPart(90, summary),),
)
