"""
Gröbner basis utilities for polynomial computations.

Provides helper functions for working with Gröbner bases and ideal manipulations.
"""

from __future__ import annotations

import sympy as sp

from ..core.exceptions import ComputationError


def compute_groebner_basis(
    polynomials: list[sp.Expr],
    variables: list[sp.Symbol],
    order: str = "lex",
    method: str | None = None,
) -> list[sp.Expr]:
    """
    Compute Gröbner basis for a set of polynomials.

    Parameters
    ----------
    polynomials : List[sp.Expr]
        List of polynomials generating the ideal.
    variables : List[sp.Symbol]
        Variables in the polynomial ring.
    order : str, default "lex"
        Monomial order: 'lex', 'grlex', or 'grevlex'.
    method : Optional[str], default None
        Method to use: 'buchberger', 'f5b', or None (automatic).

    Returns
    -------
    List[sp.Expr]
        Gröbner basis for the ideal.

    Raises
    ------
    ComputationError
        If Gröbner basis computation fails.

    Notes
    -----
    Monomial Orders:
    - 'lex': Lexicographic order (good for elimination)
    - 'grlex': Graded lexicographic order (faster, smaller basis)
    - 'grevlex': Graded reverse lexicographic order (often fastest)

    Examples
    --------
    >>> x, y = sp.symbols('x y')
    >>> polys = [x**2 + y**2 - 1, x - y]
    >>> basis = compute_groebner_basis(polys, [x, y], order='lex')
    """
    try:
        if method is not None:
            basis = sp.groebner(polynomials, *variables, order=order, method=method)
        else:
            basis = sp.groebner(polynomials, *variables, order=order)

        # Convert to list of expressions
        return [g.as_expr() if hasattr(g, "as_expr") else g for g in basis]

    except Exception as e:
        raise ComputationError(f"Gröbner basis computation failed: {e}") from e


def reduce_polynomial(
    polynomial: sp.Expr,
    basis: list[sp.Expr],
    variables: list[sp.Symbol],
) -> sp.Expr:
    """
    Reduce a polynomial modulo a Gröbner basis.

    Parameters
    ----------
    polynomial : sp.Expr
        Polynomial to reduce.
    basis : List[sp.Expr]
        Gröbner basis for the ideal.
    variables : List[sp.Symbol]
        Variables in the polynomial ring.

    Returns
    -------
    sp.Expr
        Reduced polynomial (remainder after division by basis).

    Notes
    -----
    The reduced polynomial is the unique remainder when dividing by
    the Gröbner basis. If the result is 0, the polynomial is in the ideal.

    Examples
    --------
    >>> x, y = sp.symbols('x y')
    >>> basis = [x**2 - 1, y - x]
    >>> poly = x**3 + y**2
    >>> reduced = reduce_polynomial(poly, basis, [x, y])
    """
    try:
        # Use SymPy's reduced function
        remainder = sp.reduced(polynomial, basis, variables)[1]
        return remainder
    except Exception as e:
        raise ComputationError(f"Polynomial reduction failed: {e}") from e


def is_in_ideal(
    polynomial: sp.Expr,
    basis: list[sp.Expr],
    variables: list[sp.Symbol],
) -> bool:
    """
    Check if a polynomial is in the ideal generated by a Gröbner basis.

    Parameters
    ----------
    polynomial : sp.Expr
        Polynomial to test.
    basis : List[sp.Expr]
        Gröbner basis for the ideal.
    variables : List[sp.Symbol]
        Variables in the polynomial ring.

    Returns
    -------
    bool
        True if polynomial is in the ideal, False otherwise.

    Notes
    -----
    A polynomial is in the ideal if and only if its remainder
    after division by the Gröbner basis is 0.

    Examples
    --------
    >>> x, y = sp.symbols('x y')
    >>> basis = [x - y]
    >>> is_in_ideal(x**2 - y**2, basis, [x, y])
    True
    """
    reduced = reduce_polynomial(polynomial, basis, variables)
    return bool(reduced == 0)


def ideal_quotient(
    _ideal1: list[sp.Expr],
    _ideal2: list[sp.Expr],
    _variables: list[sp.Symbol],
) -> list[sp.Expr]:
    """
    Compute the ideal quotient I1 : I2.

    Parameters
    ----------
    ideal1 : List[sp.Expr]
        Generators of first ideal I1.
    ideal2 : List[sp.Expr]
        Generators of second ideal I2.
    variables : List[sp.Symbol]
        Variables in the polynomial ring.

    Returns
    -------
    List[sp.Expr]
        Generators for the quotient ideal.

    Notes
    -----
    The ideal quotient I1 : I2 consists of all polynomials f such that
    f · g is in I1 for all g in I2.

    This is a placeholder implementation. Full implementation would require
    more sophisticated ideal theory algorithms.
    """
    raise NotImplementedError("Ideal quotient computation not yet implemented")
