"""
Gröbner basis utilities for polynomial computations.

Provides helper functions for working with Gröbner bases and ideal manipulations.
"""

from __future__ import annotations

import sympy as sp

from ..core.exceptions import ComputationError


def compute_groebner_basis(
    polynomials: list[sp.Expr],
    variables: list[sp.Symbol],
    order: str = "lex",
    method: str | None = None,
) -> list[sp.Expr]:
    """
    Compute Gröbner basis for a set of polynomials.

    Parameters
    ----------
    polynomials : List[sp.Expr]
        List of polynomials generating the ideal.
    variables : List[sp.Symbol]
        Variables in the polynomial ring.
    order : str, default "lex"
        Monomial order: 'lex', 'grlex', or 'grevlex'.
    method : Optional[str], default None
        Method to use: 'buchberger', 'f5b', or None (automatic).

    Returns
    -------
    List[sp.Expr]
        Gröbner basis for the ideal.

    Raises
    ------
    ComputationError
        If Gröbner basis computation fails.

    Notes
    -----
    Monomial Orders:
    - 'lex': Lexicographic order (good for elimination)
    - 'grlex': Graded lexicographic order (faster, smaller basis)
    - 'grevlex': Graded reverse lexicographic order (often fastest)

    Examples
    --------
    >>> x, y = sp.symbols('x y')
    >>> polys = [x**2 + y**2 - 1, x - y]
    >>> basis = compute_groebner_basis(polys, [x, y], order='lex')
    """
    try:
        if method is not None:
            basis = sp.groebner(polynomials, *variables, order=order, method=method)
        else:
            basis = sp.groebner(polynomials, *variables, order=order)

        # Convert to list of expressions
        return [g.as_expr() if hasattr(g, "as_expr") else g for g in basis]

    except Exception as e:
        raise ComputationError(f"Gröbner basis computation failed: {e}") from e


def reduce_polynomial(
    polynomial: sp.Expr,
    basis: list[sp.Expr],
    variables: list[sp.Symbol],
    order: str = "lex",
) -> sp.Expr:
    """
    Reduce a polynomial modulo a Gröbner basis.

    Parameters
    ----------
    polynomial : sp.Expr
        Polynomial to reduce.
    basis : List[sp.Expr]
        Gröbner basis for the ideal.
    variables : List[sp.Symbol]
        Variables in the polynomial ring.
    order : str, default "lex"
        Monomial order; must match the order the basis was computed in.

    Returns
    -------
    sp.Expr
        Reduced polynomial (remainder after division by basis).

    Notes
    -----
    The reduced polynomial is the unique remainder when dividing by
    the Gröbner basis. If the result is 0, the polynomial is in the ideal.

    Examples
    --------
    >>> x, y = sp.symbols('x y')
    >>> basis = [x**2 - 1, y - x]
    >>> poly = x**3 + y**2
    >>> reduced = reduce_polynomial(poly, basis, [x, y])
    """
    try:
        # Use SymPy's reduced function
        remainder = sp.reduced(polynomial, basis, *variables, order=order)[1]
        return remainder
    except Exception as e:
        raise ComputationError(f"Polynomial reduction failed: {e}") from e


def is_in_ideal(
    polynomial: sp.Expr,
    basis: list[sp.Expr],
    variables: list[sp.Symbol],
    order: str = "lex",
) -> bool:
    """
    Check if a polynomial is in the ideal generated by a Gröbner basis.

    Parameters
    ----------
    polynomial : sp.Expr
        Polynomial to test.
    basis : List[sp.Expr]
        Gröbner basis for the ideal.
    variables : List[sp.Symbol]
        Variables in the polynomial ring.
    order : str, default "lex"
        Monomial order; must match the order the basis was computed in.

    Returns
    -------
    bool
        True if polynomial is in the ideal, False otherwise.

    Notes
    -----
    A polynomial is in the ideal if and only if its remainder
    after division by the Gröbner basis is 0.

    Examples
    --------
    >>> x, y = sp.symbols('x y')
    >>> basis = [x - y]
    >>> is_in_ideal(x**2 - y**2, basis, [x, y])
    True
    """
    reduced = reduce_polynomial(polynomial, basis, variables, order=order)
    return bool(reduced == 0)


def _reduced_basis(generators: list[sp.Expr], variables: list[sp.Symbol]) -> list[sp.Expr]:
    """Reduced grevlex Gröbner basis of the ideal, dropping zero generators."""
    gens = [sp.expand(g) for g in generators if sp.expand(g) != 0]
    if not gens:
        return []
    return list(sp.groebner(gens, *variables, order="grevlex").exprs)


def intersect_ideals(
    ideal1: list[sp.Expr],
    ideal2: list[sp.Expr],
    variables: list[sp.Symbol],
) -> list[sp.Expr]:
    """
    Compute generators of the intersection of I1 and I2.

    Uses the elimination formula ``I1 cap I2 = (t I1 + (1 - t) I2) cap k[x]``
    with a fresh variable ``t`` eliminated by a lex Gröbner basis.

    Returns
    -------
    List[sp.Expr]
        Reduced grevlex Gröbner basis of the intersection (empty for the zero ideal).
    """
    gens1 = _reduced_basis(ideal1, variables)
    gens2 = _reduced_basis(ideal2, variables)
    if not gens1 or not gens2:
        return []
    t = sp.Dummy("t")
    mixed = [t * g for g in gens1] + [(1 - t) * g for g in gens2]
    basis = sp.groebner(mixed, t, *variables, order="lex")
    eliminated = [g for g in basis.exprs if not g.has(t)]
    return _reduced_basis(eliminated, variables)


def ideal_quotient(
    ideal1: list[sp.Expr],
    ideal2: list[sp.Expr],
    variables: list[sp.Symbol],
) -> list[sp.Expr]:
    """
    Compute the ideal quotient I1 : I2.

    Parameters
    ----------
    ideal1 : List[sp.Expr]
        Generators of first ideal I1.
    ideal2 : List[sp.Expr]
        Generators of second ideal I2.
    variables : List[sp.Symbol]
        Variables in the polynomial ring.

    Returns
    -------
    List[sp.Expr]
        Reduced grevlex Gröbner basis of the quotient ideal. The zero ideal is
        returned as ``[]`` and the whole ring as ``[1]``.

    Notes
    -----
    The ideal quotient I1 : I2 consists of all polynomials f such that
    f g is in I1 for all g in I2. It is computed as the intersection over the
    generators g of I2 of I1 : g, with I1 : g = (1/g) (I1 cap <g>), where each
    intersection is obtained by elimination (Cox, Little and O'Shea, Ideals,
    Varieties, and Algorithms, section 4.4).

    Raises
    ------
    ComputationError
        If a Gröbner basis computation fails.
    """
    gens1 = _reduced_basis(ideal1, variables)
    gens2 = _reduced_basis(ideal2, variables)
    if not gens1:
        return []
    if not gens2:
        return [sp.Integer(1)]

    try:
        result: list[sp.Expr] | None = None
        for g in gens2:
            common = intersect_ideals(gens1, [g], variables)
            quotient_g = [sp.cancel(h / g) for h in common]
            result = (
                quotient_g if result is None else intersect_ideals(result, quotient_g, variables)
            )
        assert result is not None
        return _reduced_basis(result, variables)
    except Exception as e:  # pragma: no cover - defensive wrapper around SymPy
        raise ComputationError(f"Ideal quotient computation failed: {e}") from e
