"""
Toric ideal computation for Feynman integrals.

This module provides algebraic methods for analysing Feynman integrals through
toric ideal theory. The toric ideal associated with the GKZ A-matrix encodes
polynomial relations among the monomial coefficients, which correspond to
integration-by-parts (IBP) identities for Feynman integrals.
"""

from __future__ import annotations

import sympy as sp

from ..core.exceptions import ComputationError


def compute_toric_ideal_generators(a_matrix: sp.Matrix) -> list[sp.Expr]:
    """
    Compute generators of the toric ideal associated with the A-matrix.

    The toric ideal I_A a subset of mathbb{C}[z_1, ..., z_m] consists of all polynomial relations
    among the variables z_j that are compatible with the monomial structure
    encoded by A. These relations correspond to IBP identities for Feynman integrals.

    The algorithm works by:
    1. Introducing auxiliary variables t_i for each row of A
    2. Creating a parametrisation: z_j = prod_i t_i^(A[i,j])
    3. Computing a Gröbner basis with elimination order
    4. Extracting polynomials that depend only on z variables

    Parameters
    ----------
    a_matrix : sp.Matrix
        The GKZ A-matrix of size r × m, where:
        - r = n+1 (number of rows, typically n = number of edges)
        - m = number of monomials in the polynomial support

        Each column of A represents the exponent vector of a monomial
        in the Lee-Pomeransky polynomial G(u).

    Returns
    -------
    List[sp.Expr]
        List of polynomial generators for the toric ideal I_A.
        These are polynomials in variables {z_1, z_2, ..., z_m} that
        generate all polynomial relations in the ideal.

        Each generator represents a syzygy (relation) among the monomials,
        which translates to an IBP identity for the Feynman integral.

    Raises
    ------
    ComputationError
        If Gröbner basis computation fails.

    Notes
    -----
    **Mathematical Background:**

    The toric ideal I_A is defined as the kernel of the ring homomorphism:
        phi: mathbb{C}[z_1,...,z_m] to mathbb{C}[t_1,...,t_r]
        z_j mapsto t^(A[:,j]) = t_1^(A[1,j]) · t_2^(A[2,j]) · ... · t_r^(A[r,j])

    Equivalently, I_A = ⟨z^u - z^v : A·u = A·v⟩, the ideal generated by
    all binomials z^u - z^v where u, v ∈ mathbb{N}^m satisfy A·u = A·v.

    Physical Interpretation:

    For Feynman integrals:
    - Each z_j represents a particular momentum configuration
    - Relations in I_A correspond to IBP identities
    - Generators give a minimal set of reduction relations
    - The variety V(I_A) parametrises master integrals

    Computational Approach:

    We use Buchberger's algorithm via SymPy's Gröbner basis computation:
    1. Create the ideal ⟨z_j - t^(A[:,j])⟩ for all j
    2. Compute Gröbner basis with 'lex' order (t's eliminated first)
    3. Extract polynomials in the basis involving only z variables

    The lexicographic term order "lex" with t > z ensures elimination of t variables.

    Computational Complexity:

    Gröbner basis computation can be expensive (doubly exponential in worst case).
    For Feynman integrals with many edges (large m), consider:
    - Using specialised IBP reduction software
    - Computing only a partial basis
    - Exploiting problem-specific structure (symmetries, etc.)

    Examples
    --------
    >>> import sympy as sp
    >>> # Simple example: 2×3 matrix
    >>> A = sp.Matrix([[1, 1, 1], [0, 1, 2]])
    >>> gens = compute_toric_ideal_generators(A)
    >>> print(gens)
    [z_1*z_3 - z_2**2]
    >>> # This means: monomial 1 times monomial 3 equals monomial 2 squared

    >>> # For a bubble diagram A-matrix
    >>> # A = [[1, 1, 1],
    >>> #      [2, 1, 0],
    >>> #      [0, 1, 2]]
    >>> A_bubble = sp.Matrix([[1, 1, 1], [2, 1, 0], [0, 1, 2]])
    >>> gens = compute_toric_ideal_generators(A_bubble)
    >>> # Returns relations like: z_1*z_3 - z_2^2 (from exponent balance)

    References
    ----------
    .. [1] Cox, D., Little, J., O'Shea, D. (2015). "Ideals, Varieties, and
            Algorithms." 4th ed., Springer.
    .. [2] Sturmfels, B. (1996). "Gröbner Bases and Convex Polytopes."
            American Mathematical Society.
    .. [3] Schabinger, R.M. (2012). "A new algorithm for the generation of
            unitarity-compatible integration by parts relations."
            JHEP 01, 077.
    """
    try:
        # Get dimensions of A-matrix
        num_rows, num_cols = a_matrix.shape  # r × m

        # === Create symbolic variables ===
        # z variables: one for each column of A (each monomial in support)
        z_vars = sp.symbols(" ".join([f"z_{j + 1}" for j in range(num_cols)]))
        if num_cols == 1:
            z_vars = (z_vars,)  # Ensure it's a tuple

        # t variables: one for each row of A (parametrising the toric variety)
        t_vars = sp.symbols(" ".join([f"t_{i}" for i in range(num_rows)]))
        if num_rows == 1:
            t_vars = (t_vars,)  # Ensure it's a tuple

        # === Construct the parametrisation polynomials ===
        # For each column j of A, create polynomial: z_j - prod_i t_i^(A[i,j])
        parametrisation_polys = []

        for j in range(num_cols):
            # Build monomial: prod_i t_i^(A[i,j])
            monomial = sp.Integer(1)
            for i in range(num_rows):
                exponent = int(a_matrix[i, j])
                if exponent > 0:
                    monomial *= t_vars[i] ** exponent

            # Create relation: z_j - monomial = 0
            parametrisation_polys.append(z_vars[j] - monomial)

        # === Compute Gröbner basis with elimination order ===
        # Use lexicographic order with t > z to eliminate t variables
        # Variables ordered as: t_0, t_1, ..., t_{r-1}, z_1, z_2, ..., z_m
        all_vars = list(t_vars) + list(z_vars)

        # Compute Gröbner basis using Buchberger's algorithm
        # The "lex" order ensures t variables are eliminated first
        try:
            groebner_basis = sp.groebner(
                parametrisation_polys, *all_vars, order="lex", method="buchberger"
            )
        except Exception:
            # If buchberger fails, try without specifying method
            groebner_basis = sp.groebner(parametrisation_polys, *all_vars, order="lex")

        # === Extract toric ideal generators ===
        # Keep only polynomials that involve no t variables (pure z-polynomials)
        toric_gens = []

        for g in groebner_basis:
            poly = g.as_expr() if hasattr(g, "as_expr") else g
            if poly.free_symbols.isdisjoint(set(t_vars)):
                toric_gens.append(sp.expand(poly))

        return toric_gens

    except Exception as e:
        raise ComputationError(f"Failed to compute toric ideal generators: {e}") from e


def count_generators(generators: list[sp.Expr]) -> int:
    """
    Count the number of generators in the toric ideal.

    Parameters
    ----------
    generators : List[sp.Expr]
        List of toric ideal generators.

    Returns
    -------
    int
        Number of generators.

    Examples
    --------
    >>> A = sp.Matrix([[1, 1, 1], [0, 1, 2]])
    >>> gens = compute_toric_ideal_generators(A)
    >>> count_generators(gens)
    1
    """
    return len(generators)


def is_binomial_ideal(generators: list[sp.Expr]) -> bool:
    """
    Check if the toric ideal is binomial (all generators have at most 2 terms).

    Parameters
    ----------
    generators : List[sp.Expr]
        List of toric ideal generators.

    Returns
    -------
    bool
        True if all generators are binomials.

    Notes
    -----
    Toric ideals are always binomial in theory, but Gröbner basis computation
    might produce polynomials with more terms depending on the term order.

    Examples
    --------
    >>> A = sp.Matrix([[1, 1, 1], [0, 1, 2]])
    >>> gens = compute_toric_ideal_generators(A)
    >>> is_binomial_ideal(gens)
    True
    """
    for gen in generators:
        # Count terms in expanded polynomial
        expanded = sp.expand(gen)
        poly = sp.Poly(expanded)
        if len(poly.terms()) > 2:
            return False
    return True


def extract_binomial_form(generator: sp.Expr) -> tuple[sp.Expr, sp.Expr]:
    """
    Extract the two monomials from a binomial generator z^u - z^v.

    Parameters
    ----------
    generator : sp.Expr
        A binomial generator (polynomial with exactly 2 terms).

    Returns
    -------
    tuple[sp.Expr, sp.Expr]
        The two monomials (positive_term, negative_term).

    Raises
    ------
    ComputationError
        If generator is not a binomial.

    Examples
    --------
    >>> z1, z2, z3 = sp.symbols('z1 z2 z3')
    >>> gen = z1*z3 - z2**2
    >>> pos, neg = extract_binomial_form(gen)
    >>> print(pos, neg)
    z1*z3 z2**2
    """
    expanded = sp.expand(generator)
    poly = sp.Poly(expanded)
    terms = poly.terms()

    if len(terms) != 2:
        raise ComputationError(f"Generator is not binomial, has {len(terms)} terms: {generator}")

    # Extract the two monomials
    (exp1, coeff1), (exp2, coeff2) = terms

    # Reconstruct monomials
    vars_list = poly.gens
    mono1 = sp.prod([v**e for v, e in zip(vars_list, exp1)])
    mono2 = sp.prod([v**e for v, e in zip(vars_list, exp2)])

    # Determine which is positive
    if coeff1 > 0:
        return mono1, mono2
    else:
        return mono2, mono1
