"""
Toric ideal computation for Feynman integrals.

This module provides algebraic methods for analysing Feynman integrals through
toric ideal theory. The toric ideal associated with the GKZ A-matrix encodes
polynomial relations among the monomial coefficients. Each binomial z^u - z^v
gives the operator d^u - d^v, with d_j = d/dz_j, which annihilates the
generalised Feynman integral: an analogue of integration-by-parts (IBP)
relations, not an IBP relation itself (Chestnov et al. 2022).
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile

import sympy as sp

from ..core.exceptions import ComputationError


def _4ti2_binary() -> str | None:
    """Return the path to the 4ti2 markov binary, or None if not installed."""
    return shutil.which("markov") or shutil.which("4ti2-markov")


def compute_toric_ideal_generators(
    a_matrix: sp.Matrix,
    backend: str = "auto",
) -> list[sp.Expr]:
    """
    Compute generators of the toric ideal associated with the A-matrix.

    The toric ideal I_A in C[z_1, ..., z_m] consists of all polynomial relations
    among the variables z_j that are compatible with the monomial structure
    encoded by A. Its binomials give the toric operators of the GKZ system,
    an analogue of IBP relations rather than IBP relations.

    Parameters
    ----------
    a_matrix : sp.Matrix
        The GKZ A-matrix of size r x m, where:
        - r = n+1 (number of rows, typically n = number of edges)
        - m = number of monomials in the polynomial support

        Each column of A represents the exponent vector of a monomial
        in the Lee-Pomeransky polynomial G(u).
    backend : str
        Which backend to use: ``"auto"`` (use 4ti2 if installed, else SymPy),
        ``"4ti2"`` (require 4ti2), or ``"sympy"`` (always use SymPy/Buchberger).

    Returns
    -------
    List[sp.Expr]
        List of polynomial generators for the toric ideal I_A.
        These are polynomials in variables {z_1, z_2, ..., z_m} that
        generate all polynomial relations in the ideal.

        Each generator z^u - z^v gives the operator d^u - d^v, with
        d_j = d/dz_j, which annihilates the generalised Feynman integral: an
        analogue of integration-by-parts (IBP) relations, not an IBP relation
        (Chestnov et al. 2022).

    Raises
    ------
    ComputationError
        If Gröbner basis computation fails or the requested backend is unavailable.

    Notes
    -----
    **Mathematical Background:**

    The toric ideal I_A is defined as the kernel of the ring homomorphism:
        phi: C[z_1,...,z_m] -> C[t_1,...,t_r]
        z_j -> t^(A[:,j]) = t_1^(A[1,j]) * t_2^(A[2,j]) * ... * t_r^(A[r,j])

    Equivalently, I_A = <z^u - z^v : A*u = A*v>, the ideal generated by
    all binomials z^u - z^v where u, v in N^m satisfy A*u = A*v.

    Physical Interpretation:

    For Feynman integrals:
    - z_j is the coefficient of the j-th monomial of G, a function of the
      masses and external momenta
    - each binomial z^u - z^v gives the toric operator d^u - d^v, which
      annihilates the generalised integral with the z_j independent; these
      operators are an analogue of IBP relations, not IBP relations
      (Chestnov et al. 2022)
    - the number of master integrals is the Euler characteristic of the
      complement of {G = 0} in the torus, at most n! times the Euclidean
      volume of the Newton polytope, which is its normalised volume when the
      exponent differences span Z^n (Bitoun, Bogner, Klausen, Panzer 2019);
      the toric ideal does not count them

    **Backends:**

    The ``"4ti2"`` backend calls the external ``markov`` binary from the 4ti2
    software package.  It computes the minimal Markov basis of I_A, which is
    the minimal generating set of the toric ideal, smaller than the Gröbner
    basis for n>=4 (e.g. 10 vs 11 for the box, 30 vs 36 for the pentagon).
    Install with ``sudo pacman -S 4ti2`` (Arch) or ``sudo apt install 4ti2``.

    The ``"sympy"`` backend uses Buchberger's algorithm via SymPy with a
    lexicographic elimination order (t-variables first).  It is self-contained
    but doubly-exponential in the worst case.

    Examples
    --------
    >>> import sympy as sp
    >>> # Simple example: 2 x 3 matrix
    >>> A = sp.Matrix([[1, 1, 1], [0, 1, 2]])
    >>> gens = compute_toric_ideal_generators(A)
    >>> print(gens)
    [z_1*z_3 - z_2**2]
    >>> # This means: monomial 1 times monomial 3 equals monomial 2 squared

    >>> # For a bubble diagram A-matrix
    >>> # A = [[1, 1, 1],
    >>> #      [2, 1, 0],
    >>> #      [0, 1, 2]]
    >>> A_bubble = sp.Matrix([[1, 1, 1], [2, 1, 0], [0, 1, 2]])
    >>> gens = compute_toric_ideal_generators(A_bubble)
    >>> # Returns relations like: z_1*z_3 - z_2^2 (from exponent balance)

    References
    ----------
    .. [1] Cox, D., Little, J., O'Shea, D. (2015). "Ideals, Varieties, and
            Algorithms." 4th ed., Springer.
    .. [2] Sturmfels, B. (1996). "Gröbner Bases and Convex Polytopes."
            American Mathematical Society.
    .. [3] Schabinger, R.M. (2012). "A new algorithm for the generation of
            unitarity-compatible integration by parts relations."
            JHEP 01, 077.
    .. [4] 4ti2 team (2008). "4ti2, A software package for algebraic,
            geometric and combinatorial problems on linear spaces."
            https://4ti2.github.io/
    """
    if backend == "auto":
        backend = "4ti2" if _4ti2_binary() else "sympy"

    if backend == "4ti2":
        binary = _4ti2_binary()
        if binary is None:
            raise ComputationError(
                "4ti2 backend requested but 'markov' binary not found. "
                "Install with: sudo pacman -S 4ti2"
            )
        return _compute_4ti2_backend(a_matrix, binary)

    if backend == "sympy":
        return _compute_sympy_backend(a_matrix)

    raise ComputationError(f"Unknown backend {backend!r}. Choose 'auto', '4ti2', or 'sympy'.")


def _compute_4ti2_backend(a_matrix: sp.Matrix, binary: str) -> list[sp.Expr]:
    """Compute minimal toric ideal generators by calling the 4ti2 markov binary.

    The markov basis is the minimal generating set of I_A (the Markov basis),
    which is smaller than or equal to the Gröbner basis for any term order.
    For n-gons: groebner gives 2/11/36/91/196 while markov gives 2/10/30/70/140
    for n=3..7, so the difference is significant for larger diagrams.
    """
    num_rows, num_cols = a_matrix.shape

    z_vars = sp.symbols(" ".join(f"z_{j + 1}" for j in range(num_cols)))
    if num_cols == 1:
        z_vars = (z_vars,)

    with tempfile.TemporaryDirectory() as tmpdir:
        prefix = os.path.join(tmpdir, "input")
        mat_path = prefix + ".mat"

        with open(mat_path, "w") as f:
            f.write(f"{num_rows} {num_cols}\n")
            for i in range(num_rows):
                f.write(" ".join(str(int(a_matrix[i, j])) for j in range(num_cols)) + "\n")

        result = subprocess.run(
            [binary, prefix],
            capture_output=True,
            text=True,
            timeout=600,
        )
        if result.returncode != 0:
            raise ComputationError(
                f"4ti2 markov failed (exit {result.returncode}): {result.stderr.strip()}"
            )

        mar_path = prefix + ".mar"
        if not os.path.exists(mar_path):
            raise ComputationError(f"4ti2 markov produced no output file at {mar_path}")

        with open(mar_path) as f:
            lines = [ln for ln in f.read().splitlines() if ln.strip()]

    n_gens, _n_vars = map(int, lines[0].split())

    generators = []
    for line in lines[1 : n_gens + 1]:
        v = list(map(int, line.split()))
        pos = sp.Integer(1)
        neg = sp.Integer(1)
        for i, vi in enumerate(v):
            if vi > 0:
                pos *= z_vars[i] ** vi
            elif vi < 0:
                neg *= z_vars[i] ** (-vi)
        generators.append(sp.expand(pos - neg))

    return generators


def _compute_sympy_backend(a_matrix: sp.Matrix) -> list[sp.Expr]:
    """Compute toric ideal generators via SymPy's Buchberger algorithm."""
    try:
        num_rows, num_cols = a_matrix.shape

        z_vars = sp.symbols(" ".join(f"z_{j + 1}" for j in range(num_cols)))
        if num_cols == 1:
            z_vars = (z_vars,)

        t_vars = sp.symbols(" ".join(f"t_{i}" for i in range(num_rows)))
        if num_rows == 1:
            t_vars = (t_vars,)

        parametrisation_polys = []
        for j in range(num_cols):
            monomial = sp.Integer(1)
            for i in range(num_rows):
                exponent = int(a_matrix[i, j])
                if exponent > 0:
                    monomial *= t_vars[i] ** exponent
            parametrisation_polys.append(z_vars[j] - monomial)

        all_vars = list(t_vars) + list(z_vars)

        try:
            groebner_basis = sp.groebner(
                parametrisation_polys, *all_vars, order="lex", method="buchberger"
            )
        except Exception:
            groebner_basis = sp.groebner(parametrisation_polys, *all_vars, order="lex")

        toric_gens = []
        for g in groebner_basis:
            poly = g.as_expr() if hasattr(g, "as_expr") else g
            if poly.free_symbols.isdisjoint(set(t_vars)):
                toric_gens.append(sp.expand(poly))

        return toric_gens

    except Exception as e:
        raise ComputationError(f"Failed to compute toric ideal generators: {e}") from e


def count_generators(generators: list[sp.Expr]) -> int:
    """
    Count the number of generators in the toric ideal.

    Parameters
    ----------
    generators : List[sp.Expr]
        List of toric ideal generators.

    Returns
    -------
    int
        Number of generators.

    Examples
    --------
    >>> A = sp.Matrix([[1, 1, 1], [0, 1, 2]])
    >>> gens = compute_toric_ideal_generators(A)
    >>> count_generators(gens)
    1
    """
    return len(generators)


def is_binomial_ideal(generators: list[sp.Expr]) -> bool:
    """
    Check if the toric ideal is binomial (all generators have at most 2 terms).

    Parameters
    ----------
    generators : List[sp.Expr]
        List of toric ideal generators.

    Returns
    -------
    bool
        True if all generators are binomials.

    Notes
    -----
    Toric ideals are always binomial in theory, but Gröbner basis computation
    might produce polynomials with more terms depending on the term order.

    Examples
    --------
    >>> A = sp.Matrix([[1, 1, 1], [0, 1, 2]])
    >>> gens = compute_toric_ideal_generators(A)
    >>> is_binomial_ideal(gens)
    True
    """
    for gen in generators:
        expanded = sp.expand(gen)
        poly = sp.Poly(expanded)
        if len(poly.terms()) > 2:
            return False
    return True


def extract_binomial_form(generator: sp.Expr) -> tuple[sp.Expr, sp.Expr]:
    """
    Extract the two monomials from a binomial generator z^u - z^v.

    Parameters
    ----------
    generator : sp.Expr
        A binomial generator (polynomial with exactly 2 terms).

    Returns
    -------
    tuple[sp.Expr, sp.Expr]
        The two monomials (positive_term, negative_term).

    Raises
    ------
    ComputationError
        If generator is not a binomial.

    Examples
    --------
    >>> z1, z2, z3 = sp.symbols('z1 z2 z3')
    >>> gen = z1*z3 - z2**2
    >>> pos, neg = extract_binomial_form(gen)
    >>> print(pos, neg)
    z1*z3 z2**2
    """
    expanded = sp.expand(generator)
    poly = sp.Poly(expanded)
    terms = poly.terms()

    if len(terms) != 2:
        raise ComputationError(f"Generator is not binomial, has {len(terms)} terms: {generator}")

    (exp1, coeff1), (exp2, coeff2) = terms

    vars_list = poly.gens
    mono1 = sp.prod([v**e for v, e in zip(vars_list, exp1, strict=True)])
    mono2 = sp.prod([v**e for v, e in zip(vars_list, exp2, strict=True)])

    if coeff1 > 0:
        return mono1, mono2
    else:
        return mono2, mono1
