"""
Decisions the LaTeX and text renderers of an analysis report share.

The two renderers state the same facts in the same order with the same
citations. What they have to agree on lives here, so that they cannot drift
apart: the sections a report shows and their headings, the bibliography and
the order of first citation, the integrands written in U, F and G, the split
of G into its U and F parts, the factors the Landau section lists and the
sentences free of maths that both print verbatim. The wording helpers join
lists and count nouns the same way for both.

The bibliography entries are LaTeX source; the text renderer strips the
markup.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from fractions import Fraction
from typing import NamedTuple

import sympy as sp

from ..landau import LimitSurface
from ..point_count import TorusCount
from ..resonance import EpsilonSet, FacetResonance
from .latex import factor_energy_scale
from .report import (
    GKZ,
    RESONANCE_WINDOW,
    AnalysisReport,
    Conventions,
    Landau,
    Polytope,
    Representations,
    Resonance,
    Schwinger,
    Symmetries,
)

__all__ = [
    "CITATIONS",
    "MAX_PAIRS_SHOWN",
    "NOT_COMPUTED",
    "TORUS_HEADING",
    "Citations",
    "LandauFactors",
    "LimitFactors",
    "Templates",
    "append_signed",
    "count_noun",
    "count_polynomial",
    "display_factors",
    "epsilon_set",
    "f_block_sentence",
    "face_names",
    "in_squared_masses",
    "integrand_templates",
    "join_words",
    "kinematic_class_sentence",
    "landau_factors",
    "lattice_normality",
    "limit_factors",
    "limit_sentences",
    "not_computed",
    "primes_left_out",
    "render_sections",
    "resonance_forms",
    "resonance_paragraphs",
    "resonance_rows",
    "resonance_windows",
    "signed_terms",
    "skipped_faces",
    "sorted_factors",
    "split_g",
    "torus_skipped_faces",
]


CITATIONS: dict[str, str] = {
    "weinzierl2022": (
        "S. Weinzierl, \\emph{Feynman Integrals: A Comprehensive Treatment for Students and "
        "Researchers}, Springer, 2022, arXiv:2201.03593."
    ),
    "leepomeransky2013": (
        "R.N. Lee and A.A. Pomeransky, \\emph{Critical points and number of master integrals}, "
        "JHEP 11 (2013) 165, arXiv:1308.6676."
    ),
    "lee2013": (
        "R.N. Lee, \\emph{LiteRed 1.4: a powerful tool for the reduction of the multiloop "
        "integrals}, J. Phys. Conf. Ser. 523 (2014) 012059, arXiv:1310.1145."
    ),
    "klausen2020": (
        "R.P. Klausen, \\emph{Hypergeometric series representations of Feynman integrals by "
        "GKZ hypergeometric systems}, JHEP 04 (2020) 121, arXiv:1910.08651."
    ),
    "klausen2023": (
        "R.P. Klausen, \\emph{Hypergeometric Feynman Integrals}, PhD thesis, Johannes Gutenberg "
        "University Mainz, arXiv:2302.13184 (2023)."
    ),
    "delacruz2019": (
        "L. de la Cruz, \\emph{Feynman integrals as A-hypergeometric functions}, "
        "JHEP 12 (2019) 123, arXiv:1907.00507."
    ),
    "fms2019": (
        "J. Forsg\\aa rd, L.F. Matusevich and A. Sobieska, \\emph{On transformations of "
        "A-hypergeometric functions}, Funkcialaj Ekvacioj 62 (2019) 319, arXiv:1703.03036."
    ),
    "delacruz2024": (
        "L. de la Cruz, \\emph{Polytope symmetries of Feynman integrals}, "
        "Phys. Lett. B 854 (2024) 138744, arXiv:2404.03564."
    ),
    "bbkp2017": (
        "T. Bitoun, C. Bogner, R.P. Klausen and E. Panzer, \\emph{Feynman integral relations "
        "from parametric annihilators}, Lett. Math. Phys. 109 (2019) 497--564, "
        "arXiv:1712.09215."
    ),
    "chestnov2022": (
        "V. Chestnov, F. Gasparotto, M.K. Mandal, P. Mastrolia, S.J. Matsubara-Heo, "
        "H.J. Munch and N. Takayama, \\emph{Macaulay matrix for Feynman integrals: linear "
        "relations and intersection numbers}, JHEP 09 (2022) 187, arXiv:2204.12983."
    ),
    "adolphson1994": (
        "A. Adolphson, \\emph{Hypergeometric functions and rings generated by monomials}, "
        "Duke Math. J. 73 (1994) 269--290."
    ),
    "mmw2005": (
        "L.F. Matusevich, E. Miller and U. Walther, \\emph{Homological methods for "
        "hypergeometric families}, J. Amer. Math. Soc. 18 (2005) 919, arXiv:math/0406383."
    ),
    "tellander2023": (
        "F. Tellander and M. Helmer, \\emph{Cohen-Macaulay property of Feynman integrals}, "
        "Commun. Math. Phys. 399 (2023) 1021--1037, arXiv:2108.01410."
    ),
    "walther2022": (
        "U. Walther, \\emph{On Feynman graphs, matroids, and GKZ-systems}, "
        "Lett. Math. Phys. 112 (2022) 120, arXiv:2206.05378."
    ),
    "gkz1994": (
        "I.M. Gelfand, M.M. Kapranov and A.V. Zelevinsky, \\emph{Discriminants, Resultants, "
        'and Multidimensional Determinants}, Birkh\\"auser, 1994.'
    ),
    "dhpt2023": (
        "C. Dlapa, M. Helmer, G. Papathanasiou and F. Tellander, \\emph{Symbol alphabets from "
        "the Landau singular locus}, JHEP 10 (2023) 161, arXiv:2304.02629."
    ),
    "fmt2023": (
        "C. Fevola, S. Mizera and S. Telen, \\emph{Landau singularities revisited: "
        "computational algebraic geometry for Feynman integrals}, Phys. Rev. Lett. 132 (2024) "
        "101601, arXiv:2311.14669."
    ),
    "jimenez2026": (
        "M. Jimenez-Santacruz, C. Lopez-Arcos and A. Quintero Velez, \\emph{Canonical "
        "differential equations for Feynman integrals from $\\mathcal{A}$-hypergeometric "
        "systems in the Schwinger representation}, arXiv:2609.16107."
    ),
    "katz2008": (
        "T. Hausel and F. Rodriguez-Villegas, \\emph{Mixed Hodge polynomials of character "
        "varieties}, with an appendix by N.M. Katz, Invent. Math. 174 (2008) 555--624, "
        "arXiv:math/0612668."
    ),
    "fmt2024": (
        "C. Fevola, S. Mizera and S. Telen, \\emph{Principal Landau determinants}, "
        "Comput. Phys. Commun. 303 (2024) 109278, arXiv:2311.16219."
    ),
    "beckrobins2015": (
        "Beck and Robins, \\emph{Computing the Continuous Discretely}, 2nd ed., Undergraduate "
        "Texts in Mathematics, Springer, 2015, doi:10.1007/978-1-4939-2969-6."
    ),
    "bgt1997": (
        "Bruns, Gubeladze and Trung, \\emph{Normal polytopes, triangulations, and Koszul "
        "algebras}, J. reine angew. Math. 485 (1997) 123--160, doi:10.1515/crll.1997.485.123."
    ),
    "hochster1972": (
        "Hochster, \\emph{Rings of invariants of tori, Cohen-Macaulay rings generated by "
        "monomials, and polytopes}, Ann. of Math. 96 (1972) 318--337, doi:10.2307/1970791."
    ),
    "batyrev1994": (
        "Batyrev, \\emph{Dual polyhedra and mirror symmetry for Calabi-Yau hypersurfaces in "
        "toric varieties}, J. Algebraic Geom. 3 (1994) 493--545, arXiv:alg-geom/9310003."
    ),
    "schulze2012": (
        "M. Schulze and U. Walther, \\emph{Resonance equals reducibility for A-hypergeometric "
        "systems}, Algebra Number Theory 6 (2012) 527, arXiv:1009.3569."
    ),
    "britto2026": (
        "R. Britto, T.W. Grimm and A. Hoefnagels, \\emph{Resonance and differential reduction "
        "of Feynman integrals}, JHEP 09 (2026) 018, arXiv:2606.09978."
    ),
}

# The symmetry section writes out at most this many symmetry pairs.
MAX_PAIRS_SHOWN = 10

# What the Newton polytope section says feynkit leaves uncomputed when P is full-dimensional.
NOT_COMPUTED = (
    "feynkit computes neither the holonomic rank at the physical point nor the Euler "
    "characteristic, and produces no series solutions, Pfaffian system or restriction to "
    "physical kinematics."
)

# The heading of the point-count section, which the text report also uses to refer to it.
TORUS_HEADING = "Candidate Euler characteristic from point counts"


class Citations:
    """The works a document cites, in the order of first citation."""

    def __init__(self) -> None:
        self.keys: list[str] = []

    def add(self, *keys: str) -> None:
        """Record a citation of ``keys``, each of which needs a bibliography entry."""
        for key in keys:
            if key not in CITATIONS:
                raise KeyError(f"No bibliography entry for {key!r}")
            if key not in self.keys:
                self.keys.append(key)


def render_sections(
    report: AnalysisReport,
    *,
    summary: Callable[[], str],
    graph: Callable[[], str],
    conventions: Callable[[], str],
    polynomials: Callable[[], str],
    representations: Callable[[Representations], str],
    polytope: Callable[[Polytope], str],
    torus: Callable[[TorusCount], str],
    gkz: Callable[[GKZ], str],
    resonance: Callable[[Resonance], str],
    symmetries: Callable[[Symmetries], str],
    landau: Callable[[Landau], str],
    schwinger: Callable[[Schwinger], str],
) -> list[tuple[str, str]]:
    """The heading and body of each section the report carries, in document order.

    Each keyword renders the body of one section. The first four sections are
    always present; each of the others is rendered from its data, and only
    when the report carries it. The sections are rendered in document order,
    so citations made while rendering are recorded in order of first use.
    """
    sections = [
        ("Summary", summary()),
        ("Graph", graph()),
        ("Conventions", conventions()),
        ("Symanzik polynomials", polynomials()),
    ]
    if report.representations is not None:
        sections.append(("Parametric representations", representations(report.representations)))
    if report.polytope is not None:
        sections.append(("Newton polytope", polytope(report.polytope)))
    if report.torus is not None:
        sections.append((TORUS_HEADING, torus(report.torus)))
    if report.gkz is not None:
        sections.append(("GKZ system", gkz(report.gkz)))
    if report.resonance is not None:
        sections.append(("Resonance", resonance(report.resonance)))
    if report.symmetries is not None:
        sections.append(("Symmetries", symmetries(report.symmetries)))
    if report.landau is not None:
        sections.append(("Landau surfaces", landau(report.landau)))
    if report.schwinger is not None:
        sections.append(("Schwinger-representation system", schwinger(report.schwinger)))
    return sections


def _number(value: Fraction, latex: bool) -> str:
    """A rational as the text prints it, -1/2, or in LaTeX, -\\tfrac{1}{2}."""
    if value.denominator == 1 or not latex:
        return str(value)
    sign = "-" if value < 0 else ""
    return f"{sign}\\tfrac{{{abs(value.numerator)}}}{{{value.denominator}}}"


def epsilon_set(found: EpsilonSet, *, latex: bool) -> str:
    """An EpsilonSet as a table cell: every eps, a progression, one value, or none.

    A progression is written offset + period Z with the offset eps_F as stored,
    Z/q for the period 1/q, and without the offset when it is 0.
    """
    eps = "$\\varepsilon$" if latex else "epsilon"
    if found.kind == "all":
        return f"every {eps}"
    if found.kind == "never":
        return f"no {eps}"
    assert found.offset is not None
    value = _number(found.offset, latex)
    if found.kind == "point":
        return f"$\\varepsilon = {value}$" if latex else f"epsilon = {value}"
    period = found.period
    assert period is not None
    if latex:
        lattice = ("" if period == 1 else _number(period, True)) + "\\mathbb{Z}"
    elif period == 1:
        lattice = "Z"
    elif period.numerator == 1:
        lattice = f"Z/{period.denominator}"
    else:
        lattice = f"({period})Z"
    text = lattice if found.offset == 0 else f"{value} + {lattice}"
    return f"${text}$" if latex else text


def resonance_forms(
    report: AnalysisReport, section: Resonance
) -> list[tuple[int, sp.Expr, int, sp.Expr]]:
    """Per facet: its number k in F_k, the left side m . x and right side b of its
    inequality, and l_F(beta) in D and the nu_e.

    The coordinates x_e and the powers nu_e are named by the edge indices.
    """
    edges = report.identity.edge_indices
    x = [sp.Symbol(f"x_{e}") for e in edges]
    nu = [sp.Symbol(f"nu_{e}") for e in edges]
    dimension = sp.Symbol("D")
    return [
        (
            k,
            sp.Add(*(m * v for m, v in zip(record.facet.normal, x, strict=True))),
            record.facet.offset,
            record.form.expression(dimension, nu),
        )
        for k, record in enumerate(section.facets, start=1)
    ]


def resonance_windows(section: Resonance, *, latex: bool) -> list[tuple[int, str]]:
    """The facets resonant on a progression or at one value, and their resonant values in
    RESONANCE_WINDOW, with k as in F_k; "none" when no value falls in it."""
    rows = []
    for k, record in enumerate(section.facets, start=1):
        if record.resonant.kind in ("progression", "point"):
            values = record.resonant.window(*RESONANCE_WINDOW)
            text = ", ".join(_number(v, latex) for v in values) or "none"
            rows.append((k, f"${text}$" if latex and values else text))
    return rows


def resonance_rows(section: Resonance, *, latex: bool) -> list[tuple[str, str, str, str]]:
    """Per facet: where it is resonant, whether at eps = 0, where admissible, reducible or not.

    A dash marks a facet that does not decide reducibility.
    """

    def row(record: FacetResonance) -> tuple[str, str, str, str]:
        return (
            epsilon_set(record.resonant, latex=latex),
            "yes" if record.resonant_at_zero else "no",
            epsilon_set(record.admissible, latex=latex),
            "yes" if record.reducible else "-",
        )

    return [row(record) for record in section.facets]


# The maths of the resonance section, as the text prints it and in LaTeX.
_RESONANCE_MATHS = {
    "eps": ("epsilon", r"\varepsilon"),
    "D": ("D = D_0 - 2 epsilon", r"D = D_0 - 2\varepsilon"),
    "nu_e": ("nu_e = 1", r"\nu_e = 1"),
    "F": ("F", "F"),
    "P": ("P", "P"),
    "A": ("A", "A"),
    "G": ("G", "G"),
    "A_F": ("A_F", "A_F"),
    "beta": ("beta", r"\beta"),
    "resonant": ("span(A_F) + ZA", r"\operatorname{span}_{\mathbb{C}} A_F + \mathbb{Z}A"),
    "span": ("span(A_F)", r"\operatorname{span}_{\mathbb{C}} A_F"),
    "system": ("(A_F, beta)", r"(A_F, \beta)"),
    "facet": ("m . x <= b", r"m \cdot x \le b"),
    "g_F": ("g_F", "g_F"),
    "l_F": ("l_F", "l_F"),
    "functional": ("l_F = (b, -m)/g_F", "l_F = (b, -m)/g_F"),
    "ZA": ("ZA", r"\mathbb{Z}A"),
    "Z": ("Z", r"\mathbb{Z}"),
    "value": ("l_F(beta) = (m . nu - b D/2)/g_F", r"l_F(\beta) = (m \cdot \nu - bD/2)/g_F"),
    "full": ("ZA = Z^(N+1)", r"\mathbb{Z}A = \mathbb{Z}^{N+1}"),
    "b0": ("b = 0", "b = 0"),
    "b": ("b != 0", r"b \ne 0"),
    "progression": ("epsilon_F + (g_F/|b|) Z", r"\varepsilon_F + (g_F/|b|)\mathbb{Z}"),
    "eps_F": ("epsilon_F = D_0/2 - m . nu/b", r"\varepsilon_F = D_0/2 - m \cdot \nu/b"),
    "centre": ("ZA + span(A_G)", r"\mathbb{Z}A + \operatorname{span}_{\mathbb{C}} A_G"),
    "hull": ("h_0 + h . x = 0", r"h_0 + h \cdot x = 0"),
    "asks": ("h_0 D/2 + h . nu = 0", r"h_0 D/2 + h \cdot \nu = 0"),
    "zero": ("epsilon = 0", r"\varepsilon = 0"),
    "D_0": ("D = D_0", "D = D_0"),
}


def resonance_paragraphs(
    section: Resonance, cite: Callable[..., str], *, latex: bool
) -> tuple[list[str], str, str]:
    """The paragraphs before the tables of the resonance section, and the two captions.

    Returns the opening paragraphs, the sentence before the table of where each
    facet is resonant, and the sentence before the list of resonant values in
    the window; the renderer prints the facets and their forms after the
    opening paragraphs.
    """

    def m(text: str, tex: str) -> str:
        return f"${tex}$" if latex else text

    x = {key: m(text, tex) for key, (text, tex) in _RESONANCE_MATHS.items()}
    d0 = _number(section.d0, latex)
    d0_is = m(f"D_0 = {d0}", f"D_0 = {d0}")
    if section.d0_source == "given":
        d0_clause = f"{d0_is} as given"
    elif section.d0_source == "dimension":
        d0_clause = f"{d0_is}, read from the dimension of the integral"
    else:
        two_eps = m("2 epsilon", "2\\varepsilon")
        d0_clause = (
            f"{d0_is} by default, since the dimension of the integral is not a number minus "
            f"{two_eps}"
        )
    if section.unit_powers:
        powers = (
            f"{x['nu_e']} on every edge, since the exponents of the integral are not all "
            "integers"
        )
    else:
        vector = "(" + ", ".join(str(p) for p in section.powers) + ")"
        nu = m(f"nu = {vector}", r"\nu = " + vector)
        powers = f"the powers {nu} of the integral"
    opening = (
        f"Let {x['D']} with {d0_clause}, and {powers}. A face {x['F']} of {x['P']}, with columns "
        f"{x['A_F']}, is resonant when {x['beta']} lies in {x['resonant']}, and admissible when "
        f"it lies in {x['span']}; the face system {x['system']} is then a true subsystem, its "
        f"solutions solving the full system{cite('britto2026')}. For a facet {x['facet']} with "
        f"lattice index {x['g_F']}, the functional {x['functional']} is zero on the facet, "
        f"positive on the other columns of {x['A']} and maps {x['ZA']} onto {x['Z']}. The facet "
        f"is resonant exactly when {x['value']} is an integer and admissible exactly when it is "
        f"zero; Britto, Grimm and Hoefnagels prove this for {x['full']}, and the proof needs "
        f"only that {x['l_F']} maps {x['ZA']} onto {x['Z']}{cite('britto2026')}. With the "
        f"powers fixed, a facet with {x['b0']} is resonant for every {x['eps']} or for none, "
        f"and one with {x['b']} exactly on the progression {x['progression']}, where "
        f"{x['eps_F']} is the one value of {x['eps']} at which it is admissible."
    )
    paragraphs = [opening]
    if section.full_dimensional:
        paragraphs.append(
            f"A resonant facet with at least two columns of {x['A']} off it makes the GKZ "
            f"system reducible{cite('britto2026')}: it contains a resonance centre, a minimal "
            f"face {x['G']} with {x['beta']} in {x['centre']}, over which {x['A']} is not a "
            f"pyramid either, and Theorem 4.1 of{cite('schulze2012')} applies. When one column "
            f"lies off the facet, {x['A']} is a pyramid over it and the facet does not decide "
            "reducibility; a dash in the table marks such a facet, and one that is never "
            "resonant."
        )
    else:
        if section.span.kind == "all":
            where = f"for every {x['eps']}"
        elif section.span.kind == "never":
            where = f"for no {x['eps']}"
        else:
            assert section.span.offset is not None
            value = _number(section.span.offset, latex)
            where = "only at " + m(f"epsilon = {value}", r"\varepsilon = " + value)
        paragraphs.append(
            f"{x['P']} is not full-dimensional, so {x['beta']} must first lie in the span of "
            f"{x['A']}: every equation {x['hull']} of the affine hull of {x['P']} asks "
            f"{x['asks']}, and elsewhere the Euler equations are inconsistent and the GKZ "
            f"system has no non-zero solutions. Here {x['beta']} lies in the span of {x['A']} "
            f"{where}. The facets below are relative to the affine hull, their functionals "
            f"fixed modulo its equations, and the sets hold only where {x['beta']} lies in the "
            "span. Below full dimension the report does not decide reducibility, and the table "
            "shows a dash."
        )
    classes = (
        f"The table gives, for each facet, the values of {x['eps']} at which it is resonant, "
        f"whether {x['zero']}, that is {x['D_0']}, is one of them, where it is admissible and "
        "whether it makes the system reducible:"
    )
    low, high = (_number(v, latex) for v in RESONANCE_WINDOW)
    interval = m(f"{low} <= epsilon <= {high}", f"{low} \\le \\varepsilon \\le {high}")
    window = (
        f"In the window {interval}, the facets resonant on a progression or at one value are "
        "resonant at:"
    )
    return paragraphs, classes, window


def f_block_sentence(schwinger: Schwinger, cite: Callable[..., str], *, latex: bool) -> str:
    """When the F~-block restriction is a true subsystem, and whether it is one here.

    The condition is that beta_Cayley lies in the span of the block's columns;
    it reads nu = (L+1)D/2 only when those columns span the hyperplane y_0 = 0.
    """

    def m(text: str, tex: str) -> str:
        return f"${tex}$" if latex else text

    beta = m("beta_Cayley", r"\beta_{\text{Cayley}}")
    hyperplane = m("y_0 = 0", "y_0 = 0")
    condition = m("nu = (L+1)D/2", r"\nu = (L+1)D/2")
    head = (
        f"its solutions solve the full system when {beta} lies in the span of the face's "
        f"columns{cite('britto2026')}; if those columns span the hyperplane {hyperplane}, as "
        f"they do when the block is a facet, the condition reads {condition}."
    )
    if schwinger.f_block_admissible:
        return f"{head} Here {beta} lies in that span, so the restriction is a true subsystem."
    symbolic = any(sp.sympify(b).free_symbols for b in schwinger.system.beta_parameters)
    generic = " for generic values of its symbols" if symbolic else ""
    return (
        f"{head} Here {beta} does not lie in that span{generic}, and the relation between the "
        "two systems is not established."
    )


def not_computed(report: AnalysisReport, pointer: str) -> str:
    """What the Newton polytope section says feynkit leaves uncomputed.

    Without the point-count section this is NOT_COMPUTED. With it, ``pointer``
    names that section as the renderer refers to it, and the sentence says that
    the Euler characteristic there is only a candidate, or that the counts give
    no candidate. It does not say why: the section gives the reason, and the
    volume bound and the guard on characters of higher order refuse counts
    that may well be polynomial.
    """
    if report.torus is None:
        return NOT_COMPUTED
    rest = "It produces no series solutions, Pfaffian system or restriction to physical kinematics."
    if report.torus.candidate_master_count is not None:
        return (
            "feynkit does not compute the holonomic rank at the physical point, and gives the "
            f"Euler characteristic only as a candidate from the point counts of {pointer}. {rest}"
        )
    return (
        "feynkit computes neither the holonomic rank at the physical point nor the Euler "
        f"characteristic, and the point counts of {pointer} give no candidate. {rest}"
    )


def count_polynomial(coefficients: Sequence[int]) -> sp.Expr:
    """P(q) from its coefficients, constant term first."""
    q = sp.Symbol("q")
    return sp.Add(*(c * q**i for i, c in enumerate(coefficients)))


def primes_left_out(torus: TorusCount) -> str:
    """The sentence listing the primes the counts leave out, up to the largest they could use."""
    primes = torus.excluded_primes
    if len(primes) == 1:
        return f"Up to {torus.max_prime} only {primes[0]} is left out."
    listed = join_words([str(p) for p in primes])
    return f"Up to {torus.max_prime} the primes left out are {listed}."


def in_squared_masses(torus: TorusCount) -> str:
    """The clause ", written in the squared masses," if the point has a squared mass, else "".

    The counts write the face discriminants in the squares of the symbols that
    occur in G only to even powers, the masses of a Feynman graph, which the
    point lists as m_e**2. A factor odd in a mass is covered through its norm
    f(m) f(-m), so the check's sentence says so, but only where a mass occurs.
    """
    squared = any(isinstance(key, sp.Pow) for key, _ in torus.point)
    return ", written in the squared masses," if squared else ""


def torus_skipped_faces(torus: TorusCount) -> str | None:
    """The sentence naming the faces the Landau analysis skipped and the steps of the count
    that miss their discriminants, or None if none was skipped.

    Only the steps that ran are named: the draw for a drawn point, the test for a
    vanishing discriminant for a given one, and the check at further primes when
    the fit reached it.
    """
    if not torus.skipped_faces:
        return None
    drawn = torus.seed is not None
    steps = [
        *(["the draw" if drawn else "the test of the given point"] if torus.point else []),
        "the choice of excluded primes",
        *(["the check"] if torus.verification_primes else []),
    ]
    whose = "whose discriminant is" if torus.skipped_faces == 1 else "whose discriminants are"
    return (
        f"The Landau analysis skipped {count_noun(torus.skipped_faces, 'face')}, {whose} "
        f"left out of {join_words(steps)}."
    )


# --- the representations and the polynomials --------------------------------


class Templates(NamedTuple):
    """The integrands of the three representations in the symbols U, F, G and nu."""

    schwinger: sp.Expr
    feynman: sp.Expr
    lee_pomeransky: sp.Expr


def integrand_templates(loop_count: int, dimension: sp.Expr) -> Templates:
    """The integrands written in U, F, G and nu, the sum of the exponents.

    The Feynman integrand leaves out the delta function, which the document
    writes into the measure, matching ``ParametrisationResult.integrand``.
    """
    u, f, g, nu = sp.symbols("U F G nu")
    loops = sp.Integer(loop_count)
    return Templates(
        schwinger=u ** (-dimension / 2) * sp.exp(-f / u),
        feynman=u ** (nu - (loops + 1) * dimension / 2) * f ** (loops * dimension / 2 - nu),
        lee_pomeransky=g ** (-dimension / 2),
    )


def split_g(g: sp.Expr, scale: sp.Symbol) -> tuple[sp.Expr, sp.Expr, int]:
    """G as ``u_part + numerator / scale**power``, the second part its F terms.

    G carries the same power of the energy scale on its F terms as F does, and
    the documents factor it out the same way.
    """
    terms = sp.Add.make_args(sp.expand(g))
    u_part = sp.Add(*[t for t in terms if scale not in t.free_symbols])
    numerator, power = factor_energy_scale(
        sp.Add(*[t for t in terms if scale in t.free_symbols]), scale
    )
    return u_part, numerator, power


# --- the Landau factors ------------------------------------------------------


def display_factors(expr: sp.Expr, scale: sp.Symbol) -> list[sp.Expr]:
    """The factors of a face discriminant that the document lists, one per line.

    This is a display rule; the discriminants stored in ``Landau.by_dimension``
    stay exact. The product is split into its sums, or powers of sums, and a
    monomial. A factor free of every symbol but the energy scale mu, that is a
    number or a power of mu, is dropped: it only reflects the normalisation of
    the coefficients z_j = c / mu^k and vanishes nowhere. The monomial
    therefore loses its numerical coefficient and its power of mu, so that
    -p_1^2 / mu^2 is listed as p_1^2 and mu s as s. A sum is never altered,
    even one that contains mu alongside kinematic symbols.
    """
    sums: list[sp.Expr] = []
    monomial: list[sp.Expr] = []
    for arg in sp.Mul.make_args(expr):
        if arg.free_symbols <= {scale}:
            continue
        base = arg.base if isinstance(arg, sp.Pow) else arg
        (sums if isinstance(base, sp.Add) else monomial).append(arg)
    if monomial:
        return [sp.Mul(*monomial), *sums]
    return sums


def sorted_factors(factors: Sequence[sp.Expr]) -> list[sp.Expr]:
    """Distinct factors in a deterministic order."""
    return sorted(dict.fromkeys(factors), key=sp.default_sort_key)


class LandauFactors(NamedTuple):
    """The factors the Landau section lists.

    Attributes
    ----------
    by_dimension
        The distinct factors of the face discriminants of each dimension,
        ascending, for the dimensions that have any.
    closed_form
        Whether the one-loop closed form gave first-type or second-type
        factors or bridge poles, so that the section compares against it.
    first_type, second_type
        The distinct Cayley and Gram factors.
    in_both
        How many factors appear in both lists.
    bridge_poles
        The distinct factors of the poles of the bridges.
    """

    by_dimension: list[tuple[int, list[sp.Expr]]]
    closed_form: bool
    first_type: list[sp.Expr]
    second_type: list[sp.Expr]
    in_both: int
    bridge_poles: list[sp.Expr]


def landau_factors(landau: Landau, scale: sp.Symbol) -> LandauFactors:
    """The factors the Landau section lists, through :func:`display_factors`."""

    def factors(expressions: Sequence[sp.Expr]) -> list[sp.Expr]:
        return sorted_factors([f for x in expressions for f in display_factors(x, scale)])

    by_dimension = [
        (dimension, factors(discriminants)) for dimension, discriminants in landau.by_dimension
    ]
    first = factors(landau.first_type)
    second = factors(landau.second_type)
    return LandauFactors(
        by_dimension=[(dimension, listed) for dimension, listed in by_dimension if listed],
        closed_form=bool(landau.first_type or landau.second_type or landau.bridge_poles),
        first_type=first,
        second_type=second,
        in_both=len(set(first) & set(second)),
        bridge_poles=factors(landau.bridge_poles),
    )


class LimitFactors(NamedTuple):
    """The factors of the parent family's surfaces, restricted, that the Landau section
    lists apart from the principal Landau determinant.

    Attributes
    ----------
    surfaces, candidates
        The limit surfaces and the candidates, each sorted by its factor.
    parent_skipped
        How many faces the analysis of the parent family skipped.
    """

    surfaces: list[LimitSurface]
    candidates: list[LimitSurface]
    parent_skipped: int


def limit_factors(landau: Landau) -> LimitFactors | None:
    """The limit surfaces and candidates of the section, or None without a parent family."""
    analysis = landau.analysis
    if analysis.parent is None:
        return None

    def ordered(records: Sequence[LimitSurface]) -> list[LimitSurface]:
        return sorted(records, key=lambda record: sp.default_sort_key(record.surface))

    return LimitFactors(
        surfaces=ordered(analysis.limit_surfaces),
        candidates=ordered(analysis.limit_candidates),
        parent_skipped=len(analysis.parent.skipped_faces),
    )


class LimitSentences(NamedTuple):
    """The prose around the lists of limit surfaces and candidates, with ``{chi}`` and
    ``{function}`` and ``{complement}`` for the renderer's maths, and ``{cite}``."""

    intro: str
    surfaces: str | None
    counts: str | None
    candidates: str | None
    reasons: str | None
    closing: str | None


def limit_sentences(limits: LimitFactors) -> LimitSentences:
    """The sentences of the limit-surface paragraphs, with placeholders for the maths."""
    intro = (
        "These kinematics restrict those of the same graph and masses with generic external "
        "momenta. The factors above form the principal Landau determinant of the family as "
        "given{cite}, which can leave out a component whose singular points leave the torus as the "
        "kinematics specialise; the surfaces of the generic family, restricted here, keep such "
        "limits."
    )
    surfaces = counts = candidates = reasons = closing = None
    if limits.surfaces:
        surfaces = (
            "The following factors of those restrictions are not among the factors above, and "
            "each is a limit surface: the number of critical points of {function} on {complement}, "
            "which is {chi} for generic exponents, is lower at two random rational points of it "
            "than at a random point of the family. That is evidence that the Euler characteristic "
            "drops there, not a proof: the points are random, and the counts are taken modulo two "
            "primes."
        )
        generic = limits.surfaces[0].generic_count
        pairs = ", ".join(" and ".join(str(c) for c in record.counts) for record in limits.surfaces)
        counts = f"The counts at the two points of each, in the order listed, are {pairs}, against {generic}."
    if limits.candidates:
        either = " either" if limits.surfaces else ""
        candidates = (
            f"The following factors of those restrictions are not among the factors above{either}, "
            "and each is only a candidate:"
        )
        reasons = (
            "Why each is not confirmed, in the order listed: "
            + "; ".join(record.reason or "" for record in limits.candidates)
            + "."
        )
    if not limits.surfaces and not limits.candidates:
        closing = (
            "Every factor of those restrictions is among the factors above, or the restriction "
            "vanishes identically."
        )
    if limits.parent_skipped:
        n = limits.parent_skipped
        skipped = (
            f"The analysis of the generic family skipped {count_noun(n, 'face')}, too large to "
            "eliminate or past the time limit, so the limit surfaces may be incomplete."
        )
        closing = skipped if closing is None else f"{closing} {skipped}"
    return LimitSentences(intro, surfaces, counts, candidates, reasons, closing)


def skipped_faces(landau: Landau) -> str | None:
    """The sentence naming the faces the Landau analysis skipped, or None if none was."""
    timed_out = landau.timed_out or (False,) * len(landau.skipped)
    skipped = sorted(zip(landau.skipped, timed_out, strict=True))
    if not skipped:
        return None
    names = [
        (
            f"the whole polytope, {points} points"
            if whole
            else f"a face of dimension {dimension} with {points} points"
        )
        + (" (past the time limit)" if late else "")
        for (dimension, points, whole), late in skipped
    ]
    n = len(skipped)
    why = (
        ", too large to eliminate or past the time limit,"
        if any(timed_out)
        else " as too large to eliminate,"
    )
    return (
        f"{count_noun(n, 'face')} {'was' if n == 1 else 'were'} skipped{why} and "
        f"{'its discriminant is' if n == 1 else 'their discriminants are'} missing from the "
        f"list: {join_words(names)}."
    )


# --- wording -----------------------------------------------------------------


def join_words(items: Sequence[str]) -> str:
    """Join as 'a, b and c'."""
    if not items:
        return "none"
    if len(items) == 1:
        return items[0]
    return ", ".join(items[:-1]) + " and " + items[-1]


def lattice_normality(polytope: Polytope, cite: Callable[..., str], *, latex: bool) -> str:
    """The sentence on the normality of NA: the certificate, or why there is none.

    NA is normal exactly when the monomials of G are all the lattice points of
    P and P has IDP. Then C[NA] is Cohen-Macaulay, and when P is
    full-dimensional there are no rank jumps; a monoid that is not normal can
    still be Cohen-Macaulay.
    """
    found = polytope.invariants
    assert found is not None
    if latex:
        na, ring = "$\\mathbb{N}A$", "$\\mathbb{C}[\\mathbb{N}A]$"
        p, g, beta = "$P$", "$G$", "$\\beta$"
    else:
        na, ring, p, g, beta = "NA", "C[NA]", "P", "G", "beta"
    if found.normal is None:
        call = "\\texttt{lattice\\_invariants}" if latex else "lattice_invariants"
        return (
            f"Whether {p} has the integer decomposition property{cite('bgt1997')}, and so "
            f"whether {na} is normal, was not computed within the report's budget: install "
            f"PyNormaliz, or call {call} directly."
        )
    if found.normal:
        head = (
            f"{p} has the integer decomposition property{cite('bgt1997')} and the monomials of "
            f"{g} are all its lattice points, so {na} is normal"
        )
        if not polytope.data.is_full_dimensional:
            return f"{head} and {ring} is Cohen-Macaulay{cite('hochster1972')}."
        return (
            f"{head}, {ring} is Cohen-Macaulay{cite('hochster1972')} and there are no rank "
            f"jumps: the holonomic rank is the normalised volume for every {beta}"
            f"{cite('mmw2005')}."
        )
    reasons = []
    if found.idp is False:
        reasons.append(f"{p} lacks the integer decomposition property{cite('bgt1997')}")
    if not found.support_is_saturated:
        missing = found.lattice_points - len(set(polytope.data.points))
        reasons.append(f"the monomials of {g} miss {missing} of its lattice points")
    return (
        f"{na} is not normal, since {' and '.join(reasons)}; this does not decide whether "
        f"{ring} is Cohen-Macaulay."
    )


def count_noun(n: int, singular: str, plural: str | None = None) -> str:
    """'1 edge', '3 edges'."""
    return f"{n} {singular if n == 1 else (plural or singular + 's')}"


def face_names(dimension: int) -> list[tuple[str, str]]:
    """Singular and plural names of the faces of each dimension below the top."""
    names = []
    for k in range(dimension):
        if k == 0:
            names.append(("vertex", "vertices"))
        elif k == 1:
            names.append(("edge", "edges"))
        elif k == dimension - 1:
            names.append(("facet", "facets"))
        else:
            names.append((f"{k}-face", f"{k}-faces"))
    return names


def signed_terms(terms: Sequence[tuple[int, str]]) -> str:
    """Join (coefficient, symbol) pairs into a signed sum, omitting zeros."""
    out = ""
    for coefficient, symbol in terms:
        if coefficient == 0:
            continue
        magnitude = abs(coefficient)
        term = symbol if magnitude == 1 else f"{magnitude} {symbol}"
        if not out:
            out = term if coefficient > 0 else f"- {term}"
        else:
            out += f" + {term}" if coefficient > 0 else f" - {term}"
    return out


def append_signed(sum_text: str, expr: sp.Expr, printer: Callable[[sp.Expr], str]) -> str:
    """Append ``expr``, printed by ``printer``, with its sign to a printed sum."""
    if expr == 0:
        return sum_text or "0"
    term = printer(expr)
    if not sum_text:
        return term
    if term.startswith("-"):
        return f"{sum_text} - {term[1:].lstrip()}"
    return f"{sum_text} + {term}"


# What each kinematic axis says, for a class that is "other". Maths is written as LaTeX and
# passed through the renderer's ``math``.
_INTERNAL_AXES = {
    "zero": "every propagator is massless",
    "equal": "every propagator has the same mass",
    "generic": "the masses are generic",
    "other": "the masses are neither all zero, all equal nor distinct symbols",
}
_EXTERNAL_AXES = {
    "off_shell": "the legs are off shell",
    "on_shell": "every leg is on shell",
    "equal": "every leg has the same {p2}",
    "other": "the invariants are neither free, on shell nor of equal mass",
}


def kinematic_class_sentence(
    conventions: Conventions,
    external_legs: int,
    masses: Sequence[sp.Expr],
    *,
    name: Callable[[str], str],
    math: Callable[[str], str],
    printer: Callable[[sp.Expr], str],
) -> str:
    """The sentence of the conventions naming the kinematic class and what it imposes.

    ``name`` sets the class as code, ``math`` a LaTeX fragment as the
    renderer writes maths and ``printer`` an expression. With fewer than two
    legs there are no invariants, and the sentence says nothing of the legs.
    """
    kinematic_class = conventions.kinematic_class
    internal, external = conventions.kinematic_axes
    legs = external_legs >= 2
    free = ", and no relation among the invariants is imposed" if legs else ""
    if kinematic_class == "generic":
        what = f"the nonzero masses {math('m_e')} are distinct symbols{free}"
    elif kinematic_class == "massless_off_shell":
        what = f"every propagator is massless{free}"
    elif kinematic_class == "equal_masses":
        what = f"every propagator has the mass {printer(masses[0])}{free}"
    elif kinematic_class == "massless_on_shell":
        left = sorted(
            {x for _, value in conventions.momentum_products for x in value.free_symbols},
            key=sp.default_sort_key,
        )
        dot, zero = math("p_i \\cdot p_j"), math("p_i^2 = 0")
        rest = (
            f"leaving {join_words([printer(x) for x in left])}"
            if left
            else f"so every product {dot} vanishes"
        )
        what = f"every propagator is massless and every leg on shell, {zero}, {rest}"
    else:
        what = _INTERNAL_AXES.get(internal, _INTERNAL_AXES["other"])
        if legs or external != "off_shell":
            phrase = _EXTERNAL_AXES.get(external, _EXTERNAL_AXES["other"])
            what += " and " + phrase.format(p2=math("p_i^2"))
    return f"The kinematic class is {name(kinematic_class)}: {what}."
