"""
Decisions the LaTeX and text renderers of an analysis report share.

The two renderers state the same facts in the same order with the same
citations. What they have to agree on lives here, so that they cannot drift
apart: the sections a report shows and their headings, the bibliography and
the order of first citation, the integrands written in U, F and G, the split
of G into its U and F parts, the factors the Landau section lists and the
sentences free of maths that both print verbatim. The wording helpers join
lists and count nouns the same way for both.

The bibliography entries are LaTeX source; the text renderer strips the
markup.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from typing import NamedTuple

import sympy as sp

from ..point_count import TorusCount
from .latex import factor_energy_scale
from .report import (
    GKZ,
    AnalysisReport,
    Conventions,
    Landau,
    Polytope,
    Representations,
    Schwinger,
    Symmetries,
)

__all__ = [
    "CITATIONS",
    "MAX_PAIRS_SHOWN",
    "NOT_COMPUTED",
    "TORUS_HEADING",
    "Citations",
    "LandauFactors",
    "Templates",
    "append_signed",
    "count_noun",
    "count_polynomial",
    "display_factors",
    "face_names",
    "in_squared_masses",
    "integrand_templates",
    "join_words",
    "kinematic_class_sentence",
    "landau_factors",
    "not_computed",
    "primes_left_out",
    "render_sections",
    "signed_terms",
    "skipped_faces",
    "sorted_factors",
    "split_g",
    "torus_skipped_faces",
]


CITATIONS: dict[str, str] = {
    "weinzierl2022": (
        "S. Weinzierl, \\emph{Feynman Integrals: A Comprehensive Treatment for Students and "
        "Researchers}, Springer, 2022, arXiv:2201.03593."
    ),
    "leepomeransky2013": (
        "R.N. Lee and A.A. Pomeransky, \\emph{Critical points and number of master integrals}, "
        "JHEP 11 (2013) 165, arXiv:1308.6676."
    ),
    "lee2013": (
        "R.N. Lee, \\emph{LiteRed 1.4: a powerful tool for the reduction of the multiloop "
        "integrals}, J. Phys. Conf. Ser. 523 (2014) 012059, arXiv:1310.1145."
    ),
    "klausen2020": (
        "R.P. Klausen, \\emph{Hypergeometric series representations of Feynman integrals by "
        "GKZ hypergeometric systems}, JHEP 04 (2020) 121, arXiv:1910.08651."
    ),
    "klausen2023": (
        "R.P. Klausen, \\emph{Hypergeometric Feynman Integrals}, PhD thesis, Johannes Gutenberg "
        "University Mainz, arXiv:2302.13184 (2023)."
    ),
    "delacruz2019": (
        "L. de la Cruz, \\emph{Feynman integrals as A-hypergeometric functions}, "
        "JHEP 12 (2019) 123, arXiv:1907.00507."
    ),
    "fms2019": (
        "J. Forsg\\aa rd, L.F. Matusevich and A. Sobieska, \\emph{On transformations of "
        "A-hypergeometric functions}, Funkcialaj Ekvacioj 62 (2019) 319, arXiv:1703.03036."
    ),
    "delacruz2024": (
        "L. de la Cruz, \\emph{Polytope symmetries of Feynman integrals}, "
        "Phys. Lett. B 854 (2024) 138744, arXiv:2404.03564."
    ),
    "bbkp2017": (
        "T. Bitoun, C. Bogner, R.P. Klausen and E. Panzer, \\emph{Feynman integral relations "
        "from parametric annihilators}, Lett. Math. Phys. 109 (2019) 497--564, "
        "arXiv:1712.09215."
    ),
    "chestnov2022": (
        "V. Chestnov, F. Gasparotto, M.K. Mandal, P. Mastrolia, S.J. Matsubara-Heo, "
        "H.J. Munch and N. Takayama, \\emph{Macaulay matrix for Feynman integrals: linear "
        "relations and intersection numbers}, JHEP 09 (2022) 187, arXiv:2204.12983."
    ),
    "adolphson1994": (
        "A. Adolphson, \\emph{Hypergeometric functions and rings generated by monomials}, "
        "Duke Math. J. 73 (1994) 269--290."
    ),
    "mmw2005": (
        "L.F. Matusevich, E. Miller and U. Walther, \\emph{Homological methods for "
        "hypergeometric families}, J. Amer. Math. Soc. 18 (2005) 919, arXiv:math/0406383."
    ),
    "tellander2023": (
        "F. Tellander and M. Helmer, \\emph{Cohen-Macaulay property of Feynman integrals}, "
        "Commun. Math. Phys. 399 (2023) 1021--1037, arXiv:2108.01410."
    ),
    "walther2022": (
        "U. Walther, \\emph{On Feynman graphs, matroids, and GKZ-systems}, "
        "Lett. Math. Phys. 112 (2022) 120, arXiv:2206.05378."
    ),
    "gkz1994": (
        "I.M. Gelfand, M.M. Kapranov and A.V. Zelevinsky, \\emph{Discriminants, Resultants, "
        'and Multidimensional Determinants}, Birkh\\"auser, 1994.'
    ),
    "dhpt2023": (
        "C. Dlapa, M. Helmer, G. Papathanasiou and F. Tellander, \\emph{Symbol alphabets from "
        "the Landau singular locus}, JHEP 10 (2023) 161, arXiv:2304.02629."
    ),
    "fmt2023": (
        "C. Fevola, S. Mizera and S. Telen, \\emph{Landau singularities revisited: "
        "computational algebraic geometry for Feynman integrals}, Phys. Rev. Lett. 132 (2024) "
        "101601, arXiv:2311.14669."
    ),
    "jimenez2026": (
        "M. Jimenez-Santacruz, C. Lopez-Arcos and A. Quintero Velez, \\emph{Canonical "
        "differential equations for Feynman integrals from $\\mathcal{A}$-hypergeometric "
        "systems in the Schwinger representation}, arXiv:2609.16107."
    ),
    "katz2008": (
        "T. Hausel and F. Rodriguez-Villegas, \\emph{Mixed Hodge polynomials of character "
        "varieties}, with an appendix by N.M. Katz, Invent. Math. 174 (2008) 555--624, "
        "arXiv:math/0612668."
    ),
    "fmt2024": (
        "C. Fevola, S. Mizera and S. Telen, \\emph{Principal Landau determinants}, "
        "Comput. Phys. Commun. 303 (2024) 109278, arXiv:2311.16219."
    ),
    "britto2026": (
        "R. Britto, T.W. Grimm and A. Hoefnagels, \\emph{Resonance and differential reduction "
        "of Feynman integrals}, JHEP 09 (2026) 018, arXiv:2606.09978."
    ),
}

# The symmetry section writes out at most this many symmetry pairs.
MAX_PAIRS_SHOWN = 10

# What the Newton polytope section says feynkit leaves uncomputed when P is full-dimensional.
NOT_COMPUTED = (
    "feynkit computes neither the holonomic rank at the physical point nor the Euler "
    "characteristic, and produces no series solutions, Pfaffian system or restriction to "
    "physical kinematics."
)

# The heading of the point-count section, which the text report also uses to refer to it.
TORUS_HEADING = "Candidate Euler characteristic from point counts"


class Citations:
    """The works a document cites, in the order of first citation."""

    def __init__(self) -> None:
        self.keys: list[str] = []

    def add(self, *keys: str) -> None:
        """Record a citation of ``keys``, each of which needs a bibliography entry."""
        for key in keys:
            if key not in CITATIONS:
                raise KeyError(f"No bibliography entry for {key!r}")
            if key not in self.keys:
                self.keys.append(key)


def render_sections(
    report: AnalysisReport,
    *,
    summary: Callable[[], str],
    graph: Callable[[], str],
    conventions: Callable[[], str],
    polynomials: Callable[[], str],
    representations: Callable[[Representations], str],
    polytope: Callable[[Polytope], str],
    torus: Callable[[TorusCount], str],
    gkz: Callable[[GKZ], str],
    symmetries: Callable[[Symmetries], str],
    landau: Callable[[Landau], str],
    schwinger: Callable[[Schwinger], str],
) -> list[tuple[str, str]]:
    """The heading and body of each section the report carries, in document order.

    Each keyword renders the body of one section. The first four sections are
    always present; each of the others is rendered from its data, and only
    when the report carries it. The sections are rendered in document order,
    so citations made while rendering are recorded in order of first use.
    """
    sections = [
        ("Summary", summary()),
        ("Graph", graph()),
        ("Conventions", conventions()),
        ("Symanzik polynomials", polynomials()),
    ]
    if report.representations is not None:
        sections.append(("Parametric representations", representations(report.representations)))
    if report.polytope is not None:
        sections.append(("Newton polytope", polytope(report.polytope)))
    if report.torus is not None:
        sections.append((TORUS_HEADING, torus(report.torus)))
    if report.gkz is not None:
        sections.append(("GKZ system", gkz(report.gkz)))
    if report.symmetries is not None:
        sections.append(("Symmetries", symmetries(report.symmetries)))
    if report.landau is not None:
        sections.append(("Landau surfaces", landau(report.landau)))
    if report.schwinger is not None:
        sections.append(("Schwinger-representation system", schwinger(report.schwinger)))
    return sections


def not_computed(report: AnalysisReport, pointer: str) -> str:
    """What the Newton polytope section says feynkit leaves uncomputed.

    Without the point-count section this is NOT_COMPUTED. With it, ``pointer``
    names that section as the renderer refers to it, and the sentence says that
    the Euler characteristic there is only a candidate, or that the counts give
    no candidate. It does not say why: the section gives the reason, and the
    volume bound and the guard on characters of higher order refuse counts
    that may well be polynomial.
    """
    if report.torus is None:
        return NOT_COMPUTED
    rest = "It produces no series solutions, Pfaffian system or restriction to physical kinematics."
    if report.torus.candidate_master_count is not None:
        return (
            "feynkit does not compute the holonomic rank at the physical point, and gives the "
            f"Euler characteristic only as a candidate from the point counts of {pointer}. {rest}"
        )
    return (
        "feynkit computes neither the holonomic rank at the physical point nor the Euler "
        f"characteristic, and the point counts of {pointer} give no candidate. {rest}"
    )


def count_polynomial(coefficients: Sequence[int]) -> sp.Expr:
    """P(q) from its coefficients, constant term first."""
    q = sp.Symbol("q")
    return sp.Add(*(c * q**i for i, c in enumerate(coefficients)))


def primes_left_out(torus: TorusCount) -> str:
    """The sentence listing the primes the counts leave out, up to the largest they could use."""
    primes = torus.excluded_primes
    if len(primes) == 1:
        return f"Up to {torus.max_prime} only {primes[0]} is left out."
    listed = join_words([str(p) for p in primes])
    return f"Up to {torus.max_prime} the primes left out are {listed}."


def in_squared_masses(torus: TorusCount) -> str:
    """The clause ", written in the squared masses," if the point has a squared mass, else "".

    The counts write the face discriminants in the squares of the symbols that
    occur in G only to even powers, the masses of a Feynman graph, which the
    point lists as m_e**2. A factor odd in a mass is covered through its norm
    f(m) f(-m), so the check's sentence says so, but only where a mass occurs.
    """
    squared = any(isinstance(key, sp.Pow) for key, _ in torus.point)
    return ", written in the squared masses," if squared else ""


def torus_skipped_faces(torus: TorusCount) -> str | None:
    """The sentence naming the faces the Landau analysis skipped and the steps of the count
    that miss their discriminants, or None if none was skipped.

    Only the steps that ran are named: the draw for a drawn point, the test for a
    vanishing discriminant for a given one, and the check at further primes when
    the fit reached it.
    """
    if not torus.skipped_faces:
        return None
    drawn = torus.seed is not None
    steps = [
        *(["the draw" if drawn else "the test of the given point"] if torus.point else []),
        "the choice of excluded primes",
        *(["the check"] if torus.verification_primes else []),
    ]
    whose = "whose discriminant is" if torus.skipped_faces == 1 else "whose discriminants are"
    return (
        f"The Landau analysis skipped {count_noun(torus.skipped_faces, 'face')}, {whose} "
        f"left out of {join_words(steps)}."
    )


# --- the representations and the polynomials --------------------------------


class Templates(NamedTuple):
    """The integrands of the three representations in the symbols U, F, G and nu."""

    schwinger: sp.Expr
    feynman: sp.Expr
    lee_pomeransky: sp.Expr


def integrand_templates(loop_count: int, dimension: sp.Expr) -> Templates:
    """The integrands written in U, F, G and nu, the sum of the exponents.

    The Feynman integrand leaves out the delta function, which the document
    writes into the measure, matching ``ParametrisationResult.integrand``.
    """
    u, f, g, nu = sp.symbols("U F G nu")
    loops = sp.Integer(loop_count)
    return Templates(
        schwinger=u ** (-dimension / 2) * sp.exp(-f / u),
        feynman=u ** (nu - (loops + 1) * dimension / 2) * f ** (loops * dimension / 2 - nu),
        lee_pomeransky=g ** (-dimension / 2),
    )


def split_g(g: sp.Expr, scale: sp.Symbol) -> tuple[sp.Expr, sp.Expr, int]:
    """G as ``u_part + numerator / scale**power``, the second part its F terms.

    G carries the same power of the energy scale on its F terms as F does, and
    the documents factor it out the same way.
    """
    terms = sp.Add.make_args(sp.expand(g))
    u_part = sp.Add(*[t for t in terms if scale not in t.free_symbols])
    numerator, power = factor_energy_scale(
        sp.Add(*[t for t in terms if scale in t.free_symbols]), scale
    )
    return u_part, numerator, power


# --- the Landau factors ------------------------------------------------------


def display_factors(expr: sp.Expr, scale: sp.Symbol) -> list[sp.Expr]:
    """The factors of a face discriminant that the document lists, one per line.

    This is a display rule; the discriminants stored in ``Landau.by_dimension``
    stay exact. The product is split into its sums, or powers of sums, and a
    monomial. A factor free of every symbol but the energy scale mu, that is a
    number or a power of mu, is dropped: it only reflects the normalisation of
    the coefficients z_j = c / mu^k and vanishes nowhere. The monomial
    therefore loses its numerical coefficient and its power of mu, so that
    -p_1^2 / mu^2 is listed as p_1^2 and mu s as s. A sum is never altered,
    even one that contains mu alongside kinematic symbols.
    """
    sums: list[sp.Expr] = []
    monomial: list[sp.Expr] = []
    for arg in sp.Mul.make_args(expr):
        if arg.free_symbols <= {scale}:
            continue
        base = arg.base if isinstance(arg, sp.Pow) else arg
        (sums if isinstance(base, sp.Add) else monomial).append(arg)
    if monomial:
        return [sp.Mul(*monomial), *sums]
    return sums


def sorted_factors(factors: Sequence[sp.Expr]) -> list[sp.Expr]:
    """Distinct factors in a deterministic order."""
    return sorted(dict.fromkeys(factors), key=sp.default_sort_key)


class LandauFactors(NamedTuple):
    """The factors the Landau section lists.

    Attributes
    ----------
    by_dimension
        The distinct factors of the face discriminants of each dimension,
        ascending, for the dimensions that have any.
    closed_form
        Whether the one-loop closed form gave first-type or second-type
        factors or bridge poles, so that the section compares against it.
    first_type, second_type
        The distinct Cayley and Gram factors.
    in_both
        How many factors appear in both lists.
    bridge_poles
        The distinct factors of the poles of the bridges.
    """

    by_dimension: list[tuple[int, list[sp.Expr]]]
    closed_form: bool
    first_type: list[sp.Expr]
    second_type: list[sp.Expr]
    in_both: int
    bridge_poles: list[sp.Expr]


def landau_factors(landau: Landau, scale: sp.Symbol) -> LandauFactors:
    """The factors the Landau section lists, through :func:`display_factors`."""

    def factors(expressions: Sequence[sp.Expr]) -> list[sp.Expr]:
        return sorted_factors([f for x in expressions for f in display_factors(x, scale)])

    by_dimension = [
        (dimension, factors(discriminants)) for dimension, discriminants in landau.by_dimension
    ]
    first = factors(landau.first_type)
    second = factors(landau.second_type)
    return LandauFactors(
        by_dimension=[(dimension, listed) for dimension, listed in by_dimension if listed],
        closed_form=bool(landau.first_type or landau.second_type or landau.bridge_poles),
        first_type=first,
        second_type=second,
        in_both=len(set(first) & set(second)),
        bridge_poles=factors(landau.bridge_poles),
    )


def skipped_faces(landau: Landau) -> str | None:
    """The sentence naming the faces the Landau analysis skipped, or None if none was."""
    skipped = sorted(landau.skipped)
    if not skipped:
        return None
    names = [
        (
            f"the whole polytope, {points} points"
            if whole
            else f"a face of dimension {dimension} with {points} points"
        )
        for dimension, points, whole in skipped
    ]
    n = len(skipped)
    return (
        f"{count_noun(n, 'face')} {'was' if n == 1 else 'were'} skipped as too large to "
        f"eliminate, and {'its discriminant is' if n == 1 else 'their discriminants are'} "
        f"missing from the list: {join_words(names)}."
    )


# --- wording -----------------------------------------------------------------


def join_words(items: Sequence[str]) -> str:
    """Join as 'a, b and c'."""
    if not items:
        return "none"
    if len(items) == 1:
        return items[0]
    return ", ".join(items[:-1]) + " and " + items[-1]


def count_noun(n: int, singular: str, plural: str | None = None) -> str:
    """'1 edge', '3 edges'."""
    return f"{n} {singular if n == 1 else (plural or singular + 's')}"


def face_names(dimension: int) -> list[tuple[str, str]]:
    """Singular and plural names of the faces of each dimension below the top."""
    names = []
    for k in range(dimension):
        if k == 0:
            names.append(("vertex", "vertices"))
        elif k == 1:
            names.append(("edge", "edges"))
        elif k == dimension - 1:
            names.append(("facet", "facets"))
        else:
            names.append((f"{k}-face", f"{k}-faces"))
    return names


def signed_terms(terms: Sequence[tuple[int, str]]) -> str:
    """Join (coefficient, symbol) pairs into a signed sum, omitting zeros."""
    out = ""
    for coefficient, symbol in terms:
        if coefficient == 0:
            continue
        magnitude = abs(coefficient)
        term = symbol if magnitude == 1 else f"{magnitude} {symbol}"
        if not out:
            out = term if coefficient > 0 else f"- {term}"
        else:
            out += f" + {term}" if coefficient > 0 else f" - {term}"
    return out


def append_signed(sum_text: str, expr: sp.Expr, printer: Callable[[sp.Expr], str]) -> str:
    """Append ``expr``, printed by ``printer``, with its sign to a printed sum."""
    if expr == 0:
        return sum_text or "0"
    term = printer(expr)
    if not sum_text:
        return term
    if term.startswith("-"):
        return f"{sum_text} - {term[1:].lstrip()}"
    return f"{sum_text} + {term}"


# What each kinematic axis says, for a class that is "other". Maths is written as LaTeX and
# passed through the renderer's ``math``.
_INTERNAL_AXES = {
    "zero": "every propagator is massless",
    "equal": "every propagator has the same mass",
    "generic": "the masses are generic",
    "other": "the masses are neither all zero, all equal nor distinct symbols",
}
_EXTERNAL_AXES = {
    "off_shell": "the legs are off shell",
    "on_shell": "every leg is on shell",
    "equal": "every leg has the same {p2}",
    "other": "the invariants are neither free, on shell nor of equal mass",
}


def kinematic_class_sentence(
    conventions: Conventions,
    external_legs: int,
    masses: Sequence[sp.Expr],
    *,
    name: Callable[[str], str],
    math: Callable[[str], str],
    printer: Callable[[sp.Expr], str],
) -> str:
    """The sentence of the conventions naming the kinematic class and what it imposes.

    ``name`` sets the class as code, ``math`` a LaTeX fragment as the
    renderer writes maths and ``printer`` an expression. With fewer than two
    legs there are no invariants, and the sentence says nothing of the legs.
    """
    kinematic_class = conventions.kinematic_class
    internal, external = conventions.kinematic_axes
    legs = external_legs >= 2
    free = ", and no relation among the invariants is imposed" if legs else ""
    if kinematic_class == "generic":
        what = f"the nonzero masses {math('m_e')} are distinct symbols{free}"
    elif kinematic_class == "massless_off_shell":
        what = f"every propagator is massless{free}"
    elif kinematic_class == "equal_masses":
        what = f"every propagator has the mass {printer(masses[0])}{free}"
    elif kinematic_class == "massless_on_shell":
        left = sorted(
            {x for _, value in conventions.momentum_products for x in value.free_symbols},
            key=sp.default_sort_key,
        )
        dot, zero = math("p_i \\cdot p_j"), math("p_i^2 = 0")
        rest = (
            f"leaving {join_words([printer(x) for x in left])}"
            if left
            else f"so every product {dot} vanishes"
        )
        what = f"every propagator is massless and every leg on shell, {zero}, {rest}"
    else:
        what = _INTERNAL_AXES.get(internal, _INTERNAL_AXES["other"])
        if legs or external != "off_shell":
            phrase = _EXTERNAL_AXES.get(external, _EXTERNAL_AXES["other"])
            what += " and " + phrase.format(p2=math("p_i^2"))
    return f"The kinematic class is {name(kinematic_class)}: {what}."
