"""
Decisions the LaTeX and text renderers of an analysis report share.

The two renderers state the same facts in the same order with the same
citations. What they have to agree on lives here, so that they cannot drift
apart: the sections a report shows and their headings, the bibliography and
the order of first citation, the integrands written in U, F and G, the split
of G into its U and F parts, the factors the Landau section lists and the
sentences free of maths that both print verbatim. The wording helpers join
lists and count nouns the same way for both.

The bibliography entries are LaTeX source; the text renderer strips the
markup.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from typing import NamedTuple

import sympy as sp

from .latex import factor_energy_scale
from .report import GKZ, AnalysisReport, Landau, Polytope, Representations, Schwinger, Symmetries

__all__ = [
    "CITATIONS",
    "MAX_PAIRS_SHOWN",
    "NOT_COMPUTED",
    "Citations",
    "LandauFactors",
    "Templates",
    "append_signed",
    "count_noun",
    "display_factors",
    "face_names",
    "integrand_templates",
    "join_words",
    "landau_factors",
    "render_sections",
    "signed_terms",
    "skipped_faces",
    "sorted_factors",
    "split_g",
    "symmetries_omitted",
]


CITATIONS: dict[str, str] = {
    "weinzierl2022": (
        "S. Weinzierl, \\emph{Feynman Integrals: A Comprehensive Treatment for Students and "
        "Researchers}, Springer, 2022, arXiv:2201.03593."
    ),
    "leepomeransky2013": (
        "R.N. Lee and A.A. Pomeransky, \\emph{Critical points and number of master integrals}, "
        "JHEP 11 (2013) 165, arXiv:1308.6676."
    ),
    "klausen2020": (
        "R.P. Klausen, \\emph{Hypergeometric series representations of Feynman integrals by "
        "GKZ hypergeometric systems}, JHEP 04 (2020) 121, arXiv:1910.08651."
    ),
    "klausen2023": (
        "R.P. Klausen, \\emph{Hypergeometric Feynman Integrals}, PhD thesis, Johannes Gutenberg "
        "University Mainz, arXiv:2302.13184 (2023)."
    ),
    "delacruz2019": (
        "L. de la Cruz, \\emph{Feynman integrals as A-hypergeometric functions}, "
        "JHEP 12 (2019) 123, arXiv:1907.00507."
    ),
    "fms2019": (
        "J. Forsg\\aa rd, L.F. Matusevich and A. Sobieska, \\emph{On transformations of "
        "A-hypergeometric functions}, Funkcialaj Ekvacioj 62 (2019) 319, arXiv:1703.03036."
    ),
    "delacruz2024": (
        "L. de la Cruz, \\emph{Polytope symmetries of Feynman integrals}, "
        "Phys. Lett. B 854 (2024) 138744, arXiv:2404.03564."
    ),
    "bbkp2017": (
        "T. Bitoun, C. Bogner, R.P. Klausen and E. Panzer, \\emph{Feynman integral relations "
        "from parametric annihilators}, Lett. Math. Phys. 109 (2019) 497--564, "
        "arXiv:1712.09215."
    ),
    "chestnov2022": (
        "V. Chestnov, F. Gasparotto, M.K. Mandal, P. Mastrolia, S.J. Matsubara-Heo, "
        "H.J. Munch and N. Takayama, \\emph{Macaulay matrix for Feynman integrals: linear "
        "relations and intersection numbers}, JHEP 09 (2022) 187, arXiv:2204.12983."
    ),
    "adolphson1994": (
        "A. Adolphson, \\emph{Hypergeometric functions and rings generated by monomials}, "
        "Duke Math. J. 73 (1994) 269--290."
    ),
    "mmw2005": (
        "L.F. Matusevich, E. Miller and U. Walther, \\emph{Homological methods for "
        "hypergeometric families}, J. Amer. Math. Soc. 18 (2005) 919, arXiv:math/0406383."
    ),
    "tellander2023": (
        "F. Tellander and M. Helmer, \\emph{Cohen-Macaulay property of Feynman integrals}, "
        "Commun. Math. Phys. 399 (2023) 1021--1037, arXiv:2108.01410."
    ),
    "walther2022": (
        "U. Walther, \\emph{On Feynman graphs, matroids, and GKZ-systems}, "
        "Lett. Math. Phys. 112 (2022) 120, arXiv:2206.05378."
    ),
    "gkz1994": (
        "I.M. Gelfand, M.M. Kapranov and A.V. Zelevinsky, \\emph{Discriminants, Resultants, "
        'and Multidimensional Determinants}, Birkh\\"auser, 1994.'
    ),
    "dhpt2023": (
        "C. Dlapa, M. Helmer, G. Papathanasiou and F. Tellander, \\emph{Symbol alphabets from "
        "the Landau singular locus}, JHEP 10 (2023) 161, arXiv:2304.02629."
    ),
    "fmt2023": (
        "C. Fevola, S. Mizera and S. Telen, \\emph{Landau singularities revisited: "
        "computational algebraic geometry for Feynman integrals}, Phys. Rev. Lett. 132 (2024) "
        "101601, arXiv:2311.14669."
    ),
    "jimenez2026": (
        "M. Jimenez-Santacruz, C. Lopez-Arcos and A. Quintero Velez, \\emph{Canonical "
        "differential equations for Feynman integrals from $\\mathcal{A}$-hypergeometric "
        "systems in the Schwinger representation}, arXiv:2609.16107."
    ),
    "britto2026": (
        "R. Britto, T.W. Grimm and A. Hoefnagels, \\emph{Resonance and differential reduction "
        "of Feynman integrals}, JHEP 09 (2026) 018, arXiv:2606.09978."
    ),
}

# The symmetry section writes out at most this many symmetry pairs.
MAX_PAIRS_SHOWN = 10

# What the Newton polytope section says feynkit leaves uncomputed, whatever the rank.
NOT_COMPUTED = (
    "feynkit computes neither the holonomic rank at the physical point nor the Euler "
    "characteristic, and produces no series solutions, Pfaffian system or restriction to "
    "physical kinematics."
)


class Citations:
    """The works a document cites, in the order of first citation."""

    def __init__(self) -> None:
        self.keys: list[str] = []

    def add(self, *keys: str) -> None:
        """Record a citation of ``keys``, each of which needs a bibliography entry."""
        for key in keys:
            if key not in CITATIONS:
                raise KeyError(f"No bibliography entry for {key!r}")
            if key not in self.keys:
                self.keys.append(key)


def render_sections(
    report: AnalysisReport,
    *,
    summary: Callable[[], str],
    graph: Callable[[], str],
    conventions: Callable[[], str],
    polynomials: Callable[[], str],
    representations: Callable[[Representations], str],
    polytope: Callable[[Polytope], str],
    gkz: Callable[[GKZ], str],
    symmetries: Callable[[Symmetries | None], str],
    landau: Callable[[Landau], str],
    schwinger: Callable[[Schwinger], str],
) -> list[tuple[str, str]]:
    """The heading and body of each section the report carries, in document order.

    Each keyword renders the body of one section. The first four sections are
    always present; each of the others is rendered from its data, and only
    when the report carries it. The symmetry section is rendered from None
    when the report left the symmetries out. The sections are rendered in
    document order, so citations made while rendering are recorded in order
    of first use.
    """
    sections = [
        ("Summary", summary()),
        ("Graph", graph()),
        ("Conventions", conventions()),
        ("Symanzik polynomials", polynomials()),
    ]
    if report.representations is not None:
        sections.append(("Parametric representations", representations(report.representations)))
    if report.polytope is not None:
        sections.append(("Newton polytope", polytope(report.polytope)))
    if report.gkz is not None:
        sections.append(("GKZ system", gkz(report.gkz)))
    if report.symmetries is not None or report.symmetries_omitted is not None:
        sections.append(("Symmetries", symmetries(report.symmetries)))
    if report.landau is not None:
        sections.append(("Landau surfaces", landau(report.landau)))
    if report.schwinger is not None:
        sections.append(("Schwinger-representation system", schwinger(report.schwinger)))
    return sections


def symmetries_omitted(report: AnalysisReport) -> str:
    """What the symmetry section says when the report left the symmetries out.

    The sentence names the reason ``report.symmetries_omitted`` records.
    """
    if report.symmetries_omitted == "not full-dimensional":
        return (
            "The symmetries are not computed for Newton polytopes that are not "
            "full-dimensional, such as this one."
        )
    return (
        "The symmetries are not computed for Newton polytopes of dimension below 2, such as "
        "this one."
    )


# --- the representations and the polynomials --------------------------------


class Templates(NamedTuple):
    """The integrands of the three representations in the symbols U, F, G and nu."""

    schwinger: sp.Expr
    feynman: sp.Expr
    lee_pomeransky: sp.Expr


def integrand_templates(loop_count: int, dimension: sp.Expr) -> Templates:
    """The integrands written in U, F, G and nu, the sum of the exponents.

    The Feynman integrand leaves out the delta function, which the document
    writes into the measure, matching ``ParametrisationResult.integrand``.
    """
    u, f, g, nu = sp.symbols("U F G nu")
    loops = sp.Integer(loop_count)
    return Templates(
        schwinger=u ** (-dimension / 2) * sp.exp(-f / u),
        feynman=u ** (nu - (loops + 1) * dimension / 2) * f ** (loops * dimension / 2 - nu),
        lee_pomeransky=g ** (-dimension / 2),
    )


def split_g(g: sp.Expr, scale: sp.Symbol) -> tuple[sp.Expr, sp.Expr, int]:
    """G as ``u_part + numerator / scale**power``, the second part its F terms.

    G carries the same power of the energy scale on its F terms as F does, and
    the documents factor it out the same way.
    """
    terms = sp.Add.make_args(sp.expand(g))
    u_part = sp.Add(*[t for t in terms if scale not in t.free_symbols])
    numerator, power = factor_energy_scale(
        sp.Add(*[t for t in terms if scale in t.free_symbols]), scale
    )
    return u_part, numerator, power


# --- the Landau factors ------------------------------------------------------


def display_factors(expr: sp.Expr, scale: sp.Symbol) -> list[sp.Expr]:
    """The factors of a face discriminant that the document lists, one per line.

    This is a display rule; the discriminants stored in ``Landau.by_dimension``
    stay exact. The product is split into its sums, or powers of sums, and a
    monomial. A factor free of every symbol but the energy scale mu, that is a
    number or a power of mu, is dropped: it only reflects the normalisation of
    the coefficients z_j = c / mu^k and vanishes nowhere. The monomial
    therefore loses its numerical coefficient and its power of mu, so that
    -p_1^2 / mu^2 is listed as p_1^2 and mu s as s. A sum is never altered,
    even one that contains mu alongside kinematic symbols.
    """
    sums: list[sp.Expr] = []
    monomial: list[sp.Expr] = []
    for arg in sp.Mul.make_args(expr):
        if arg.free_symbols <= {scale}:
            continue
        base = arg.base if isinstance(arg, sp.Pow) else arg
        (sums if isinstance(base, sp.Add) else monomial).append(arg)
    if monomial:
        return [sp.Mul(*monomial), *sums]
    return sums


def sorted_factors(factors: Sequence[sp.Expr]) -> list[sp.Expr]:
    """Distinct factors in a deterministic order."""
    return sorted(dict.fromkeys(factors), key=sp.default_sort_key)


class LandauFactors(NamedTuple):
    """The factors the Landau section lists.

    Attributes
    ----------
    by_dimension
        The distinct factors of the face discriminants of each dimension,
        ascending, for the dimensions that have any.
    closed_form
        Whether the one-loop closed form gave first-type or second-type
        factors, so that the section compares against it.
    first_type, second_type
        The distinct Cayley and Gram factors.
    in_both
        How many factors appear in both lists.
    """

    by_dimension: list[tuple[int, list[sp.Expr]]]
    closed_form: bool
    first_type: list[sp.Expr]
    second_type: list[sp.Expr]
    in_both: int


def landau_factors(landau: Landau, scale: sp.Symbol) -> LandauFactors:
    """The factors the Landau section lists, through :func:`display_factors`."""

    def factors(expressions: Sequence[sp.Expr]) -> list[sp.Expr]:
        return sorted_factors([f for x in expressions for f in display_factors(x, scale)])

    by_dimension = [
        (dimension, factors(discriminants)) for dimension, discriminants in landau.by_dimension
    ]
    first = factors(landau.first_type)
    second = factors(landau.second_type)
    return LandauFactors(
        by_dimension=[(dimension, listed) for dimension, listed in by_dimension if listed],
        closed_form=bool(landau.first_type or landau.second_type),
        first_type=first,
        second_type=second,
        in_both=len(set(first) & set(second)),
    )


def skipped_faces(landau: Landau) -> str | None:
    """The sentence naming the faces the Landau analysis skipped, or None if none was."""
    skipped = sorted(landau.skipped)
    if not skipped:
        return None
    names = [
        (
            f"the whole polytope, {points} points"
            if whole
            else f"a face of dimension {dimension} with {points} points"
        )
        for dimension, points, whole in skipped
    ]
    n = len(skipped)
    return (
        f"{count_noun(n, 'face')} {'was' if n == 1 else 'were'} skipped as too large to "
        f"eliminate, and {'its discriminant is' if n == 1 else 'their discriminants are'} "
        f"missing from the list: {join_words(names)}."
    )


# --- wording -----------------------------------------------------------------


def join_words(items: Sequence[str]) -> str:
    """Join as 'a, b and c'."""
    if not items:
        return "none"
    if len(items) == 1:
        return items[0]
    return ", ".join(items[:-1]) + " and " + items[-1]


def count_noun(n: int, singular: str, plural: str | None = None) -> str:
    """'1 edge', '3 edges'."""
    return f"{n} {singular if n == 1 else (plural or singular + 's')}"


def face_names(dimension: int) -> list[tuple[str, str]]:
    """Singular and plural names of the faces of each dimension below the top."""
    names = []
    for k in range(dimension):
        if k == 0:
            names.append(("vertex", "vertices"))
        elif k == 1:
            names.append(("edge", "edges"))
        elif k == dimension - 1:
            names.append(("facet", "facets"))
        else:
            names.append((f"{k}-face", f"{k}-faces"))
    return names


def signed_terms(terms: Sequence[tuple[int, str]]) -> str:
    """Join (coefficient, symbol) pairs into a signed sum, omitting zeros."""
    out = ""
    for coefficient, symbol in terms:
        if coefficient == 0:
            continue
        magnitude = abs(coefficient)
        term = symbol if magnitude == 1 else f"{magnitude} {symbol}"
        if not out:
            out = term if coefficient > 0 else f"- {term}"
        else:
            out += f" + {term}" if coefficient > 0 else f" - {term}"
    return out


def append_signed(sum_text: str, expr: sp.Expr, printer: Callable[[sp.Expr], str]) -> str:
    """Append ``expr``, printed by ``printer``, with its sign to a printed sum."""
    if expr == 0:
        return sum_text or "0"
    term = printer(expr)
    if not sum_text:
        return term
    if term.startswith("-"):
        return f"{sum_text} - {term[1:].lstrip()}"
    return f"{sum_text} + {term}"
