"""
LaTeX rendering of an analysis report.

:func:`render_latex` turns an :class:`AnalysisReport` into a complete
``article`` document: a summary table, the graph, the conventions, the
Symanzik polynomials, the parametric representations with the convergence
region, the Newton polytope with the rank statement, the GKZ system, the
symmetries, the Landau surfaces, the Schwinger-representation system and the
references. Each section is rendered by its own function and omitted when the
report does not carry it. Citations are collected while the sections are
rendered, so the bibliography lists exactly the works the text cites, in the
order of first citation.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from typing import NamedTuple

import sympy as sp

from .latex import factor_energy_scale, to_latex, to_latex_split
from .report import (
    GKZ,
    AnalysisReport,
    Conventions,
    Identity,
    Landau,
    Polytope,
    Representations,
    Schwinger,
    Symmetries,
)

__all__ = ["CITATIONS", "render_latex"]


CITATIONS: dict[str, str] = {
    "weinzierl2022": (
        "S. Weinzierl, \\emph{Feynman Integrals: A Comprehensive Treatment for Students and "
        "Researchers}, Springer, 2022, arXiv:2201.03593."
    ),
    "leepomeransky2013": (
        "R.N. Lee and A.A. Pomeransky, \\emph{Critical points and number of master integrals}, "
        "JHEP 11 (2013) 165, arXiv:1308.6676."
    ),
    "klausen2020": (
        "R.P. Klausen, \\emph{Hypergeometric series representations of Feynman integrals by "
        "GKZ hypergeometric systems}, JHEP 04 (2020) 121, arXiv:1910.08651."
    ),
    "klausen2023": (
        "R.P. Klausen, \\emph{Hypergeometric Feynman Integrals}, PhD thesis, 2023, "
        "arXiv:2302.13184."
    ),
    "delacruz2019": (
        "L. de la Cruz, \\emph{Feynman integrals as A-hypergeometric functions}, "
        "JHEP 12 (2019) 123, arXiv:1907.00507."
    ),
    "delacruz2024": (
        "L. de la Cruz, \\emph{Polytope symmetries of Feynman integrals}, "
        "Phys. Lett. B 854 (2024) 138744, arXiv:2404.03564."
    ),
    "bbkp2017": (
        "T. Bitoun, C. Bogner, R.P. Klausen and E. Panzer, \\emph{Feynman integral relations "
        "from parametric annihilators}, Lett. Math. Phys. 109 (2019) 497--564, "
        "arXiv:1712.09215."
    ),
    "chestnov2022": (
        "V. Chestnov, F. Gasparotto, M.K. Mandal, P. Mastrolia, S.J. Matsubara-Heo, "
        "H.J. Munch and N. Takayama, \\emph{Macaulay matrix for Feynman integrals: linear "
        "relations and intersection numbers}, JHEP 09 (2022) 187, arXiv:2204.12983."
    ),
    "adolphson1994": (
        "A. Adolphson, \\emph{Hypergeometric functions and rings generated by monomials}, "
        "Duke Math. J. 73 (1994) 269--290."
    ),
    "mmw2005": (
        "L.F. Matusevich, E. Miller and U. Walther, \\emph{Homological methods for "
        "hypergeometric families}, J. Amer. Math. Soc. 18 (2005) 919, arXiv:math/0406383."
    ),
    "tellander2023": (
        "F. Tellander and M. Helmer, \\emph{Cohen-Macaulay property of Feynman integrals}, "
        "Commun. Math. Phys. 399 (2023) 1021--1037, arXiv:2108.01410."
    ),
    "walther2022": (
        "U. Walther, \\emph{On Feynman graphs, matroids, and GKZ-systems}, "
        "Lett. Math. Phys. 112 (2022) 120, arXiv:2206.05378."
    ),
    "gkz1994": (
        "I.M. Gelfand, M.M. Kapranov and A.V. Zelevinsky, \\emph{Discriminants, Resultants, "
        'and Multidimensional Determinants}, Birkh\\"auser, 1994.'
    ),
    "dhpt2023": (
        "C. Dlapa, M. Helmer, G. Papathanasiou and F. Tellander, \\emph{Symbol alphabets from "
        "the Landau singular locus}, JHEP 10 (2023) 161, arXiv:2304.02629."
    ),
    "fmt2023": (
        "C. Fevola, S. Mizera and S. Telen, \\emph{Landau singularities revisited: "
        "computational algebraic geometry for Feynman integrals}, Phys. Rev. Lett. 132 (2024) "
        "101601, arXiv:2311.14669."
    ),
    "jimenez2026": (
        "M. Jimenez-Santacruz, C. Lopez-Arcos and A. Quintero Velez, \\emph{Canonical "
        "differential equations for Feynman integrals from $\\mathcal{A}$-hypergeometric "
        "systems in the Schwinger representation}, arXiv:2609.16107."
    ),
    "britto2026": (
        "R. Britto, T.W. Grimm and A. Hoefnagels, \\emph{Resonance and differential reduction "
        "of Feynman integrals}, JHEP 09 (2026) 018, arXiv:2606.09978."
    ),
}


_PREAMBLE = """\\documentclass[11pt,a4paper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{amsmath,amssymb}
\\setcounter{MaxMatrixCols}{64}
\\usepackage[margin=2.5cm]{geometry}
\\usepackage{booktabs,array,longtable}
\\usepackage{tikz}
\\usetikzlibrary{calc}
\\usepackage{tikz-3dplot}
\\usepackage[hidelinks]{hyperref}
\\allowdisplaybreaks"""

_MAX_PAIRS_SHOWN = 10

_ESCAPES: dict[int, str] = {
    ord("\\"): "\\textbackslash{}",
    ord("&"): "\\&",
    ord("%"): "\\%",
    ord("$"): "\\$",
    ord("#"): "\\#",
    ord("_"): "\\_",
    ord("{"): "\\{",
    ord("}"): "\\}",
    ord("~"): "\\textasciitilde{}",
    ord("^"): "\\textasciicircum{}",
}


# --- small helpers -----------------------------------------------------------


class _Cites:
    """Collect citation keys in the order the text first cites them."""

    def __init__(self) -> None:
        self.keys: list[str] = []

    def __call__(self, *keys: str) -> str:
        for key in keys:
            if key not in CITATIONS:
                raise KeyError(f"No bibliography entry for {key!r}")
            if key not in self.keys:
                self.keys.append(key)
        return "~\\cite{" + ",".join(keys) + "}"

    def bibliography(self) -> str:
        items = [f"\\bibitem{{{key}}} {CITATIONS[key]}" for key in self.keys]
        return "\\begin{thebibliography}{99}\n" + "\n".join(items) + "\n\\end{thebibliography}"


class _Templates(NamedTuple):
    """The integrands of the three representations in the symbols U, F, G and nu."""

    schwinger: sp.Expr
    feynman: sp.Expr
    lee_pomeransky: sp.Expr


def _integrand_templates(loop_count: int, dimension: sp.Expr) -> _Templates:
    """The integrands written in U, F, G and nu, the sum of the exponents.

    The Feynman integrand leaves out the delta function, which the document
    writes into the measure, matching ``ParametrisationResult.integrand``.
    """
    u, f, g, nu = sp.symbols("U F G nu")
    loops = sp.Integer(loop_count)
    return _Templates(
        schwinger=u ** (-dimension / 2) * sp.exp(-f / u),
        feynman=u ** (nu - (loops + 1) * dimension / 2) * f ** (loops * dimension / 2 - nu),
        lee_pomeransky=g ** (-dimension / 2),
    )


def _escape(text: str) -> str:
    """Escape the characters that LaTeX treats specially in running text."""
    return text.translate(_ESCAPES)


def _math(expr: sp.Expr) -> str:
    return "$" + to_latex(expr) + "$"


def _words(items: Sequence[str]) -> str:
    """Join as 'a, b and c'."""
    if not items:
        return "none"
    if len(items) == 1:
        return items[0]
    return ", ".join(items[:-1]) + " and " + items[-1]


def _count(n: int, singular: str, plural: str | None = None) -> str:
    return f"{n} {singular if n == 1 else (plural or singular + 's')}"


def _matrix(matrix: sp.Matrix) -> str:
    rows = [
        " & ".join(to_latex(matrix[r, c]) for c in range(matrix.cols)) for r in range(matrix.rows)
    ]
    return "\\begin{bmatrix}\n" + " \\\\\n".join(rows) + "\n\\end{bmatrix}"


def _vector(entries: Sequence[sp.Expr]) -> str:
    return "\\left(" + ", ".join(to_latex(e) for e in entries) + "\\right)"


def _lines(expr: sp.Expr) -> list[str]:
    """The lines :func:`to_latex_split` breaks a long sum into; one line if short.

    Every line after the first starts with its sign.
    """
    body = to_latex_split(expr)
    head, tail = "\\begin{split}\n", "\n\\end{split}"
    if body.startswith(head) and body.endswith(tail):
        return body[len(head) : -len(tail)].split(" \\\\\n& ")
    return [body]


def _scaled_lines(expr: sp.Expr, scale: sp.Expr) -> list[str]:
    """The lines of ``expr`` written as ``(1/scale)(...)``."""
    lines = _lines(expr)
    lines[0] = f"\\frac{{1}}{{{to_latex(scale)}}}\\bigl({lines[0]}"
    lines[-1] += "\\bigr)"
    return lines


def _equation(lhs: str, lines: Sequence[str]) -> str:
    """Display ``lhs = ...`` over the given lines, aligned after the equals sign."""
    if len(lines) == 1:
        body = f"{lhs} = {lines[0]}"
    else:
        continued = "".join(f" \\\\\n&\\quad {{}}{line}" for line in lines[1:])
        body = f"\\begin{{split}}\n{lhs} &= {lines[0]}{continued}\n\\end{{split}}"
    return "\\begin{equation*}\n" + body + "\n\\end{equation*}"


def _signed_terms(terms: Sequence[tuple[int, str]]) -> str:
    """Join (coefficient, symbol) pairs into a signed sum, omitting zeros."""
    out = ""
    for coefficient, symbol in terms:
        if coefficient == 0:
            continue
        magnitude = abs(coefficient)
        term = symbol if magnitude == 1 else f"{magnitude} {symbol}"
        if not out:
            out = term if coefficient > 0 else f"- {term}"
        else:
            out += f" + {term}" if coefficient > 0 else f" - {term}"
    return out


def _append_signed(sum_latex: str, expr: sp.Expr) -> str:
    """Append ``expr`` with its sign to a sum written in LaTeX."""
    if expr == 0:
        return sum_latex or "0"
    term = to_latex(expr)
    if not sum_latex:
        return term
    if term.startswith("-"):
        return f"{sum_latex} - {term[1:].lstrip()}"
    return f"{sum_latex} + {term}"


def _face_names(dimension: int) -> list[tuple[str, str]]:
    """Singular and plural names of the faces of each dimension below the top."""
    names = []
    for k in range(dimension):
        if k == 0:
            names.append(("vertex", "vertices"))
        elif k == 1:
            names.append(("edge", "edges"))
        elif k == dimension - 1:
            names.append(("facet", "facets"))
        else:
            names.append((f"{k}-face", f"{k}-faces"))
    return names


# --- sections ----------------------------------------------------------------


def _summary(report: AnalysisReport) -> str:
    rows = []
    for label, value in report.summary():
        text = re.sub(r"\b([FG])\b", r"$\1$", _escape(label))
        rows.append(f"{text} & {_escape(value)} \\\\")
    return "\n".join(
        [
            "\\section{Summary}",
            "\\begin{center}",
            "\\begin{tabular}{ll}",
            "\\toprule",
            *rows,
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{center}",
        ]
    )


def _graph(identity: Identity) -> str:
    label = re.search(r"\\label\{([^}]*)\}", identity.graph_tikz)
    shown = f"Figure~\\ref{{{label.group(1)}}} shows the graph. " if label else ""
    rows = [
        f"{e} & {_math(nu)} & {_math(mass)} \\\\"
        for e, (nu, mass) in enumerate(
            zip(identity.edge_exponents, identity.edge_masses, strict=True), start=1
        )
    ]
    return "\n".join(
        [
            "\\section{Graph}",
            identity.graph_tikz,
            "",
            f"{shown}It has $L = {identity.loop_count}$ "
            f"{'loop' if identity.loop_count == 1 else 'loops'}, "
            f"$N = {identity.propagators}$ propagators and "
            f"{_count(identity.external_legs, 'external leg')}.",
            "\\begin{center}",
            "\\begin{tabular}{ccc}",
            "\\toprule",
            "$e$ & $\\nu_e$ & $m_e$ \\\\",
            "\\midrule",
            *rows,
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{center}",
            "Propagator $e$ carries the exponent $\\nu_e$ and the mass $m_e$ shown in the table; "
            "massless propagators have $m_e = 0$.",
        ]
    )


def _kinematics(conventions: Conventions) -> str:
    invariants = conventions.invariants
    if invariants is None:
        return "the dot products $p_i \\cdot p_j$"
    symbols = list(dict.fromkeys(invariants.symbols))
    listed = _words([_math(s) for s in symbols])
    noun = "invariant" if len(symbols) == 1 else "invariants"
    if invariants.n_external == 2:
        return f"the {noun} {listed}: $s = p^2$ for $p = p_1 = -p_2$, so that $p_1 \\cdot p_2 = -s$"
    clause = "the external masses $p_i^2$"
    if invariants.mandelstam:
        clause += " and the planar invariants $s_{i \\ldots j-1} = (p_i + \\cdots + p_{j-1})^2$"
    return f"the {noun} {listed}: {clause}"


def _conventions(conventions: Conventions, cite: _Cites) -> str:
    dimension = conventions.dimension
    is_d = isinstance(dimension, sp.Symbol) and dimension.name == "D"
    in_d = "$D$" if is_d else f"$D = {to_latex(dimension)}$"
    return "\n".join(
        [
            "\\section{Conventions}",
            f"The integral $I$ is evaluated in {in_d} dimensions with the metric signature "
            "$(+,-,\\ldots,-)$ and propagators $1/(-q^2 + m^2)^{\\nu}$; dimensional "
            "regularisation sets $D = D_0 - 2\\epsilon$ for an even integer $D_0$ chosen when "
            "the result is expanded. The energy scale $\\mu$ keeps the Symanzik polynomials "
            "dimensionless. External momenta are incoming, and the kinematics is written in "
            f"{_kinematics(conventions)}. The second Symanzik polynomial is "
            "$F = -\\sum_{T_2} s_{T_2} \\prod_{e \\notin T_2} a_e + U \\sum_e m_e^2 a_e$, "
            "divided by $\\mu^2$, the sum running over spanning two-forests $T_2$ and "
            "$s_{T_2}$ being the square of the momentum flowing from one tree of $T_2$ to the "
            f"other{cite('weinzierl2022')}.",
        ]
    )


def _polynomials(report: AnalysisReport, cite: _Cites) -> str:
    polynomials = report.polynomials
    conventions = report.conventions
    power = polynomials.f_scale_power
    scale = conventions.energy_scale
    if power:
        f_lines = _scaled_lines(polynomials.f_numerator, scale**power)
        # G carries the same 1/mu^power on its F terms; factor it out the same way.
        terms = sp.Add.make_args(sp.expand(polynomials.g))
        u_part = sp.Add(*[t for t in terms if scale not in t.free_symbols])
        f_part, g_power = factor_energy_scale(
            sp.Add(*[t for t in terms if scale in t.free_symbols]), scale
        )
        g_f_lines = _scaled_lines(f_part, scale**g_power)
        g_lines = [*_lines(u_part), "+ " + g_f_lines[0], *g_f_lines[1:]]
    else:
        f_lines = _lines(polynomials.f_numerator)
        g_lines = _lines(polynomials.g)
    rows = [
        f"{entry.index} & {_math(entry.monomial)} & {_math(entry.coefficient)} \\\\"
        for entry in polynomials.z_table
    ]
    n_edges = report.identity.propagators
    return "\n".join(
        [
            "\\section{Symanzik polynomials}",
            "In the Schwinger parameters $a_e$ the first Symanzik polynomial, the sum over "
            "spanning trees $T$ of $\\prod_{e \\notin T} a_e$, is",
            _equation("U", _lines(polynomials.u)),
            "and the second is",
            _equation("F", f_lines),
            "In the Lee-Pomeransky parameters $u_e$ their sum is",
            _equation("G = U + F", g_lines),
            f"$U$ has degree $L = {polynomials.degree_u}$ and $F$ degree "
            f"$L+1 = {polynomials.degree_f}$; $F$ has "
            f"{_count(polynomials.monomials_f, 'monomial')} and $G$ has "
            f"{polynomials.monomials_g}. The coefficients of $G$ are the GKZ variables $z_j$, "
            "here at their physical values:",
            "\\begin{longtable}{rll}",
            "\\toprule",
            "$j$ & Monomial & $z_j$ \\\\",
            "\\midrule",
            "\\endhead",
            "\\bottomrule",
            "\\endlastfoot",
            *rows,
            "\\end{longtable}",
            f"The configuration has codimension ${polynomials.monomials_g} - {n_edges} - 1 = "
            f"{polynomials.codimension}$, against "
            f"{_count(polynomials.independent_invariants, 'independent kinematic invariant')} "
            f"in the coefficients{cite('klausen2023')}.",
        ]
    )


def _representation(
    prefactor: sp.Expr,
    parameters: Sequence[sp.Symbol],
    measure: sp.Expr,
    constraint: str,
    integrand: sp.Expr,
) -> str:
    differentials = "\\, ".join(f"\\mathrm{{d}}{to_latex(p)}" for p in parameters)
    factors = [f for f in (constraint, "" if measure == 1 else to_latex(measure)) if f]
    factors.append(to_latex(integrand, fold_short_frac=True))
    return "\n".join(
        [
            "\\begin{equation*}",
            "\\begin{split}",
            f"I &= {to_latex(prefactor)} \\\\",
            f"&\\quad \\times \\int_{{\\mathbb{{R}}_{{+}}^{{{len(parameters)}}}}} "
            f"{differentials}\\; " + "\\, ".join(factors),
            "\\end{split}",
            "\\end{equation*}",
        ]
    )


def _representations(
    representations: Representations, identity: Identity, dimension: sp.Expr, cite: _Cites
) -> str:
    schwinger = representations.schwinger
    feynman = representations.feynman
    lee_pomeransky = representations.lee_pomeransky
    templates = _integrand_templates(identity.loop_count, dimension)
    # The Schwinger result names its parameters alpha_e; the document uses a_e
    # throughout, the names of the Feynman result and of U and F.
    rename = dict(zip(schwinger.parameters, feynman.parameters, strict=True))
    nu_total = sp.Add(*identity.edge_exponents)

    parts = [
        "\\section{Parametric representations}",
        "\\subsection{Schwinger representation}",
        "With the Schwinger parameters $a_e$ integrated over $[0, \\infty)$"
        f"{cite('weinzierl2022')},",
        _representation(
            schwinger.prefactor,
            feynman.parameters,
            schwinger.measure.subs(rename),
            "",
            templates.schwinger,
        ),
        "\\subsection{Feynman representation}",
        "With the same parameters restricted to the simplex $\\sum_e a_e = 1$"
        f"{cite('weinzierl2022')},",
        _representation(
            feynman.prefactor,
            feynman.parameters,
            feynman.measure,
            "\\delta\\Bigl(1 - \\sum_{e} a_{e}\\Bigr)",
            templates.feynman,
        ),
        f"where $\\nu = {to_latex(nu_total)}$ is the sum of the exponents.",
        "\\subsection{Lee-Pomeransky representation}",
        "With the Lee-Pomeransky parameters $u_e$ integrated over $[0, \\infty)$"
        f"{cite('leepomeransky2013')},",
        _representation(
            lee_pomeransky.prefactor,
            lee_pomeransky.parameters,
            lee_pomeransky.measure,
            "",
            templates.lee_pomeransky,
        ),
        "\\paragraph{Convergence.}",
    ]
    if representations.convergence is None:
        parts.append(
            "The Newton polytope $P$ of $G$ is not full-dimensional, so the Lee-Pomeransky "
            f"integral converges nowhere{cite('klausen2023')}."
        )
        return "\n".join(parts)
    lines = " \\\\\n".join(f"{to_latex(c)} &> 0" for c in representations.convergence)
    parts += [
        "The Lee-Pomeransky integral converges when $(\\nu_1, \\ldots, \\nu_N)$ lies in the "
        "interior of $(D/2)\\,P$, with $P$ the Newton polytope of $G$, that is when for every "
        "facet $m_j \\cdot x \\le b_j$ of $P$ the real part of "
        "$b_j D/2 - \\sum_e m_{je} \\nu_e$ is positive:",
        "\\begin{align*}",
        lines,
        "\\end{align*}",
        f"It converges nowhere when $P$ is not full-dimensional{cite('klausen2023')}.",
    ]
    return "\n".join(parts)


def _polytope(polytope: Polytope, cite: _Cites) -> str:
    data = polytope.data
    counts = [
        _count(n, singular, plural)
        for n, (singular, plural) in zip(
            data.f_vector[:-1], _face_names(data.dimension), strict=True
        )
    ]
    shape = f", with {_words(counts)}" if counts else ""
    vertices = _words(
        [
            f"$v_{{{k}}} = ({', '.join(str(x) for x in vertex)})$"
            for k, vertex in enumerate(data.vertices, start=1)
        ]
    )
    volume = data.normalized_volume
    parts = [
        "\\section{Newton polytope}",
        "\\label{sec:newton-polytope}",
        "The Newton polytope $P$ of $G$ is the convex hull of the exponent vectors of its "
        f"monomials. It has dimension {data.dimension} in "
        f"$\\mathbb{{R}}^{{{data.ambient_dimension}}}$ and normalised volume {volume}{shape}. "
        f"Its vertices are {vertices}.",
    ]
    if polytope.figure is not None:
        parts += [
            "Figure~\\ref{fig:newton-polytope} draws it.",
            "\\begin{figure}[htbp]",
            "\\centering",
            polytope.figure,
            "\\caption{The Newton polytope $P$ of $G$.}",
            "\\label{fig:newton-polytope}",
            "\\end{figure}",
        ]
    parts += [
        "",
        "For generic coefficients and non-resonant $\\beta$ the holonomic rank of the GKZ "
        "system equals the normalised volume, here "
        f"{volume}{cite('adolphson1994', 'chestnov2022')}. The rank equals the volume for "
        "every $\\beta$ exactly when the toric ring $\\mathbb{C}[\\mathbb{N}A]$ is "
        "Cohen-Macaulay, with $A$ the matrix whose columns are the exponent vectors of $G$ "
        f"below a row of ones{cite('mmw2005')}. This holds when the graph is one-particle "
        "irreducible and one-vertex irreducible, its external momenta are generic enough that "
        "no monomial of "
        "$G$ cancels, and its propagators are all massive, all massless, or such that every "
        "vertex reaches an external leg along massive propagators alone; the configuration is "
        "then normal and so Cohen-Macaulay"
        f"{cite('klausen2023', 'tellander2023', 'walther2022')}. The number of master "
        "integrals is, up to sign, the Euler characteristic of the complement of "
        "$\\{G = 0\\}$ in the torus, at most the normalised volume and equal to it for "
        "generic coefficients; graph-polynomial coefficients are rarely generic"
        f"{cite('bbkp2017')}. feynkit computes neither the holonomic rank at the physical "
        "point nor the Euler characteristic, and produces no series solutions, Pfaffian "
        "system or restriction to physical kinematics.",
    ]
    return "\n".join(parts)


def _gkz(gkz: GKZ, cite: _Cites) -> str:
    operators = []
    for r, (row, beta_r) in enumerate(gkz.euler_rows):
        terms = _signed_terms([(a, f"\\theta_{{{j}}}") for j, a in enumerate(row, start=1)])
        operators.append(f"E_{{{r}}} &= {_append_signed(terms, -beta_r)}")
    parts = [
        "\\section{GKZ system}",
        "Writing $G = \\sum_j z_j u^{\\alpha_j}$ and treating the coefficients $z_j$ as "
        "independent variables turns $I$ into the generalised integral $I(\\beta, z)$. Its "
        "GKZ system has the matrix",
        "\\begin{equation*}",
        "A = " + _matrix(gkz.a_matrix),
        "\\end{equation*}",
        "whose column $j$ is $(1, \\alpha_j)$. The parameter vector is "
        "$\\beta = (-D/2, -\\nu_1, \\ldots, -\\nu_N)$, the value the Euler equations require "
        f"for the Lee-Pomeransky integral{cite('delacruz2019', 'klausen2020')}. Here",
        "\\begin{equation*}",
        "\\beta = " + _vector(gkz.beta) + ".",
        "\\end{equation*}",
        "The Euler operators are built from $\\theta_j = z_j \\partial_{z_j}$, which measures "
        "the degree in $z_j$. The operators $E_r = \\sum_j A_{rj}\\theta_j - \\beta_r$ "
        "annihilate the integral: row $0$ states that $I$ is homogeneous of degree $-D/2$ in "
        "the $z_j$, and row $i$ that it has degree $-\\nu_i$ under "
        "$z_j \\mapsto \\lambda^{A_{ij}} z_j$, which a rescaling of $u_i$ absorbs:",
        "\\begin{align*}",
        " \\\\\n".join(operators),
        "\\end{align*}",
    ]
    generators = gkz.toric_generators
    if not generators:
        parts.append("The toric ideal is trivial.")
        return "\n".join(parts)
    parts += [
        f"The toric ideal of $A$ is generated by {_count(len(generators), 'binomial')}. Each "
        "binomial $z^{k} - z^{l}$, with $Ak = Al$, gives the operator "
        "$\\partial^{k} - \\partial^{l}$; these annihilators of the generalised integral form "
        "an analogue of integration-by-parts relations for it"
        f"{cite('chestnov2022')}, and the specialisation to physical coefficients is a "
        "separate step. The generators are",
        "\\begin{gather*}",
        " \\\\\n".join(to_latex_split(g) for g in generators),
        "\\end{gather*}",
    ]
    return "\n".join(parts)


def _symmetries(symmetries: Symmetries, polytope: Polytope | None, cite: _Cites) -> str:
    orbits = symmetries.vertex_orbits
    if polytope is not None:
        listed = _words(
            ["$\\{" + ", ".join(f"v_{{{i + 1}}}" for i in orbit) + "\\}$" for orbit in orbits]
        )
        action = (
            f"acts on the vertices listed in Section~\\ref{{sec:newton-polytope}} with "
            f"{'the orbit' if len(orbits) == 1 else 'orbits'} {listed}"
        )
    else:
        sizes = _words([str(len(orbit)) for orbit in orbits])
        action = (
            f"acts on the vertices of $P$ with {_count(len(orbits), 'orbit')} of "
            f"{'size' if len(orbits) == 1 else 'sizes'} {sizes}"
        )
    preserving = symmetries.coefficient_preserving
    pairs = symmetries.symmetry_pairs
    parts = [
        "\\section{Symmetries}",
        "The group $\\mathrm{Aut}(P)$ of unimodular affine maps taking $P$ to itself has "
        f"order {symmetries.automorphism_order} and {action}. The graph has "
        f"{_count(len(symmetries.graph_automorphisms), 'automorphism')}. Of the polytope "
        f"automorphisms, {preserving} {'preserves' if preserving == 1 else 'preserve'} the "
        "coefficients of $G$.",
    ]
    if not pairs:
        parts.append("The configuration has no symmetry pairs.")
        return "\n".join(parts)
    shown = pairs[:_MAX_PAIRS_SHOWN]
    parts.append(
        f"The configuration has {_count(len(pairs), 'symmetry pair')} $(T, \\sigma)$: "
        "integer matrices $T$ and permutations $\\sigma$ of the columns of $A$ such that $T$ "
        "takes column $j$ of $A$ to column $\\sigma(j)$. Each gives the identity "
        "$I(\\beta, z) = I(T\\beta, z_\\sigma)$ with "
        "$z_\\sigma = (z_{\\sigma(1)}, z_{\\sigma(2)}, \\ldots)$"
        f"{cite('delacruz2024')}. "
        + ("They are" if len(pairs) == len(shown) else f"The first {len(shown)} are")
        + ", with $\\sigma$ listed as $(\\sigma(1), \\sigma(2), \\ldots)$:"
    )
    for k, pair in enumerate(shown, start=1):
        sigma = ", ".join(str(j + 1) for j in pair.column_permutation)
        parts += [
            "\\begin{equation*}",
            f"T_{{{k}}} = {_matrix(pair.homogenized_map)}, \\qquad \\sigma_{{{k}}} = ({sigma})",
            "\\end{equation*}",
        ]
    if len(pairs) > len(shown):
        rest = len(pairs) - len(shown)
        parts.append(f"and {rest} further {'pair' if rest == 1 else 'pairs'}.")
    return "\n".join(parts)


def _landau(landau: Landau, cite: _Cites) -> str:
    intro = (
        "The reduced principal $A$-determinant of $G$, each irreducible kinematic factor taken "
        "once, is the product of the discriminants of $G$ restricted to the faces of $P$"
        f"{cite('gkz1994', 'dhpt2023', 'fmt2023')}."
    )
    parts = ["\\section{Landau surfaces}"]
    if landau.by_dimension:
        parts += [intro + " Those other than one are, by face dimension:", "\\begin{itemize}"]
        for dimension, factors in landau.by_dimension:
            parts.append(f"\\item Dimension {dimension}: " + ", ".join(_math(f) for f in factors))
        parts.append("\\end{itemize}")
    else:
        parts.append(intro + " Every face discriminant is one.")
    if landau.first_type or landau.second_type:
        first = _words([_math(f) for f in landau.first_type])
        second = _words([_math(f) for f in landau.second_type])
        parts.append(
            "By comparison with the closed form from the modified Cayley matrix, the "
            f"first-type (Cayley) factors are {first}, and the second-type (Gram) factors are "
            f"{second}{cite('dhpt2023')}."
        )
    parts.append(
        "The factors are candidate codimension-one singular loci on all sheets of the "
        "integral: a point on one of them may or may not be singular on the physical sheet, "
        f"and the list is not guaranteed complete{cite('fmt2023')}. The coefficients are "
        "specialised to physical kinematics before each face discriminant is computed, so "
        "beyond one loop this is the principal Landau determinant rather than the principal "
        "$A$-determinant of the generic polynomial; multiplicities are dropped."
    )
    skipped = len(landau.analysis.skipped_faces)
    if skipped:
        parts.append(
            f"{_count(skipped, 'face')} {'was' if skipped == 1 else 'were'} skipped as too "
            "large to eliminate, and "
            f"{'its discriminant is' if skipped == 1 else 'their discriminants are'} missing "
            "from the list."
        )
    return "\n".join(parts)


def _schwinger(schwinger: Schwinger, identity: Identity, dimension: sp.Expr, cite: _Cites) -> str:
    system = schwinger.system
    f_block = schwinger.f_block
    loops = identity.loop_count
    condition = sp.Eq(sp.Add(*identity.edge_exponents), (loops + 1) * dimension / 2, evaluate=False)
    check = "verified" if schwinger.columns_match else "not verified"
    return "\n".join(
        [
            "\\section{Schwinger-representation system}",
            "The Schwinger representation gives a second GKZ system on the Cayley "
            "configuration of $(\\tilde U, \\tilde F)$, the Symanzik polynomials with "
            "$a_N = 1$ and $a_e = u_e$ otherwise"
            f"{cite('jimenez2026', 'klausen2023')}:",
            "\\begin{gather*}",
            "A_{\\text{Cayley}} = " + _matrix(system.a_matrix) + ", \\\\",
            "\\beta_{\\text{Cayley}} = " + _vector(system.beta_parameters) + ".",
            "\\end{gather*}",
            "It is unimodularly equivalent to the Lee-Pomeransky configuration, the matrix "
            "$A_{\\text{LP}}$ and parameter vector "
            "$\\beta_{\\text{LP}} = (-D/2, -\\nu_1, \\ldots, -\\nu_N)$ of the GKZ system of $G$, "
            "through",
            "\\begin{equation*}",
            "T = " + _matrix(schwinger.lp_to_cayley) + ",",
            "\\end{equation*}",
            "which maps the parameter vectors as $\\beta_{\\text{Cayley}} = T "
            "\\beta_{\\text{LP}}$ and the columns of $A_{\\text{LP}}$ to those of "
            "$A_{\\text{Cayley}}$ up to order; the column correspondence is "
            f"{check} for this integral. Restricting to the $\\tilde F$ block gives the system",
            "\\begin{gather*}",
            "A_F = " + _matrix(f_block.a_matrix) + ", \\\\",
            "\\beta_F = " + _vector(f_block.beta_parameters) + ";",
            "\\end{gather*}",
            "its solutions solve the full system when $\\beta_{\\text{Cayley}}$ lies in the span "
            "of the face's "
            "columns, which for the $\\tilde F$ block means $\\nu = (L+1)D/2$, with $\\nu$ the "
            f"sum of the exponents, here ${to_latex(condition)}${cite('britto2026')}. Away "
            "from that value the relation between the two systems is not established.",
        ]
    )


# --- the document ------------------------------------------------------------


def render_latex(report: AnalysisReport, *, title: str | None = None) -> str:
    """Render an analysis report as a complete LaTeX ``article``.

    Parameters
    ----------
    report
        The report to render; sections it does not carry are omitted.
    title
        Document title, escaped for LaTeX; by default "Feynman integral"
        followed by the CNickel string.

    Returns
    -------
    str
        The document source, ASCII only, compilable with pdflatex.
    """
    cite = _Cites()
    if title is None:
        heading = f"Feynman integral \\texttt{{{_escape(report.identity.cnickel)}}}"
    else:
        heading = _escape(title)

    sections = [
        _summary(report),
        _graph(report.identity),
        _conventions(report.conventions, cite),
        _polynomials(report, cite),
    ]
    if report.representations is not None:
        sections.append(
            _representations(
                report.representations, report.identity, report.conventions.dimension, cite
            )
        )
    if report.polytope is not None:
        sections.append(_polytope(report.polytope, cite))
    if report.gkz is not None:
        sections.append(_gkz(report.gkz, cite))
    if report.symmetries is not None:
        sections.append(_symmetries(report.symmetries, report.polytope, cite))
    if report.landau is not None:
        sections.append(_landau(report.landau, cite))
    if report.schwinger is not None:
        sections.append(
            _schwinger(report.schwinger, report.identity, report.conventions.dimension, cite)
        )

    document = [
        _PREAMBLE,
        "",
        f"\\title{{{heading}}}",
        "\\date{}",
        "",
        "\\begin{document}",
        "\\maketitle",
        "",
        "\n\n".join(sections),
        "",
        cite.bibliography(),
        "",
        "\\end{document}",
        "",
    ]
    return "\n".join(document)
